# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

# removed oldrel for now until R > 3.5.0
r:
- release
- devel

after_success:
  - Rscript -e 'covr::codecov()'

r_github_packages:
  - r-lib/covr
  - MIDFIELDR/midfielddata
