<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />


<meta name="date" content="2022-06-29" />

<title>Degree seeking (inner joins)</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Degree seeking (inner joins)</h1>
<h4 class="date">2022-06-29</h4>



<p>After subsetting longitudinal Student Unit Records (SURs) for data
sufficiency, a typical second step is to restrict a study to students
admitted as degree-seeking.</p>
<p>Within this context, this vignette illustrates using inner joins to
filter observations using data.table syntax. We use MIDFIELD data, but
no midfieldr functions are required.</p>
<div id="method" class="section level2">
<h2>Method</h2>
<p>We filter observations to retain degree-seeking students using an
inner join with the <code>student</code> data table. This works because
<code>student</code> (unlike <code>term</code>) contains degree-seeking
SURs only.</p>
</div>
<div id="population" class="section level2">
<h2>Population</h2>
<p>If you are writing your own script to follow along, we start with
these packages:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfieldr&quot;</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfielddata&quot;</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(<span class="st">&quot;data.table&quot;</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing options for data.table</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.nrows =</span> <span class="dv">55</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.topn =</span> <span class="dv">5</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.class =</span> <span class="cn">TRUE</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><strong>Importing.</strong> Load the midfielddata data tables.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data sets from midfielddata</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(student, term)</span></code></pre></div>
<p><strong>Data sufficiency.</strong> To set up for filtering for
degree-seeking, we start with the <code>term</code> data and filter for
data sufficiency as described in the <a href="art-010-data-sufficiency.html">Data sufficiency vignette</a>.
Those steps are reproduced here in condensed form without details.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for data sufficiency</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">copy</span>(term)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_timely_term</span>(DT, term)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_data_sufficiency</span>(DT, term)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[data_sufficiency <span class="sc">==</span> <span class="st">&quot;include&quot;</span>]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop unnecessary variables</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid, cip6)]</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">unique</span>(DT)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;                mcid   cip6
#&gt;              &lt;char&gt; &lt;char&gt;
#&gt;      1: MID25783135 520101
#&gt;      2: MID25783162 140102
#&gt;      3: MID25783162 520301
#&gt;      4: MID25783162 521401
#&gt;      5: MID25783178 140102
#&gt;     ---                   
#&gt; 111928: MID26697576 521401
#&gt; 111929: MID26697599 521201
#&gt; 111930: MID26697599 110401
#&gt; 111931: MID26697615 500901
#&gt; 111932: MID26697623 451001</code></pre>
<p>The result has 111,932 observations of 63,952 unique IDs. The number
of unique students is smaller than the number of observations because
some students change programs over their course of study. Here we have
one row per unique combination of student (mcid) and program code
(cip6).</p>
<p>Retaining the CIP variable is not strictly necessary for
degree-seeking filtering. We retain it here to assist in the inner-join
examples.</p>
</div>
<div id="inner-joins" class="section level2">
<h2>Inner joins</h2>
<p>An <em>inner join</em> is a merge operation between two data frame
which returns only those records that match on selected variables
between the two data frames.</p>
<p>We use inner joins regularly to subset observations of our working
data frames by shared columns in another data frame. To illustrate, we
will filter our <code>DT</code> data by the IDs in the “toy” (exercise)
data sets bundled with midfieldr. Using data.table syntax, we have two
approaches: <code>merge()</code> and the <code>X[Y, j]</code>
syntax.</p>
<p><strong>Using <code>merge()</code>.</strong> Using the data.table
<code>merge()</code> syntax, the <code>all = FALSE</code> argument
creates the inner join. We first isolate the ID column in
<code>toy_student</code>. Otherwise, all columns from both data frames
would be returned.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Isolate the IDs of the second data frame</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>toy_select <span class="ot">&lt;-</span> toy_student[, .(mcid)]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Inner join to filter the observations of the first data frame</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="fu">merge</span>(DT, toy_select, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), <span class="at">all =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>#&gt;             mcid   cip6
#&gt;           &lt;char&gt; &lt;char&gt;
#&gt;   1: MID25784187 010901
#&gt;   2: MID25784187 520801
#&gt;   3: MID25819358 511103
#&gt;   4: MID25819358 260502
#&gt;   5: MID25828870 140102
#&gt;  ---                   
#&gt; 131: MID26692025 500702
#&gt; 132: MID26692025 131202
#&gt; 133: MID26692254 520201
#&gt; 134: MID26692254 400404
#&gt; 135: MID26692254 450701</code></pre>
<p>The result has 135 observations of 74 unique IDs.</p>
<p>Alternatively, one can include the ID selection within the merge
operation.</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Isolating the IDs inside the merge function</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">merge</span>(DT, toy_student[, .(mcid)], <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), <span class="at">all =</span> <span class="cn">FALSE</span>)</span></code></pre></div>
<pre><code>#&gt;             mcid   cip6
#&gt;           &lt;char&gt; &lt;char&gt;
#&gt;   1: MID25784187 010901
#&gt;   2: MID25784187 520801
#&gt;   3: MID25819358 511103
#&gt;   4: MID25819358 260502
#&gt;   5: MID25828870 140102
#&gt;  ---                   
#&gt; 131: MID26692025 500702
#&gt; 132: MID26692025 131202
#&gt; 133: MID26692254 520201
#&gt; 134: MID26692254 400404
#&gt; 135: MID26692254 450701</code></pre>
<p><strong>Using <code>X[Y, j]</code>.</strong> The second
approach—computationally more efficient—uses the data.table
<code>X[Y, j]</code> syntax.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A more computationally efficient approach</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>DT[toy_student, .(mcid, cip6), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span></code></pre></div>
<pre><code>#&gt;             mcid   cip6
#&gt;           &lt;char&gt; &lt;char&gt;
#&gt;   1: MID25784187 010901
#&gt;   2: MID25784187 520801
#&gt;   3: MID25819358 511103
#&gt;   4: MID25819358 260502
#&gt;   5: MID25828870 140102
#&gt;  ---                   
#&gt; 131: MID26692025 500702
#&gt; 132: MID26692025 131202
#&gt; 133: MID26692254 520201
#&gt; 134: MID26692254 400404
#&gt; 135: MID26692254 450701</code></pre>
<p>The <code>nomatch = NULL</code> argument makes the merge an inner
join, the <code>on</code> argument defines the shared column to use in
matching, and the <code>j</code> argument,<code>.(mcid, cip6)</code>,
defines the columns from both data frames to return.</p>
<p>The way to read this code out loud is: “Take <code>DT</code>, retain
rows where <code>toy_student$mcid == DT$mcid</code>, then select columns
<code>mcid</code> and <code>cip6</code>.”</p>
<p>For inner joins, <code>X[Y, j]</code> and <code>Y[X, j]</code>
produce the same result.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Swap the roles of the two data frames</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>toy_student[DT, .(mcid, cip6), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span></code></pre></div>
<pre><code>#&gt;             mcid   cip6
#&gt;           &lt;char&gt; &lt;char&gt;
#&gt;   1: MID25784187 010901
#&gt;   2: MID25784187 520801
#&gt;   3: MID25819358 511103
#&gt;   4: MID25819358 260502
#&gt;   5: MID25828870 140102
#&gt;  ---                   
#&gt; 131: MID26692025 500702
#&gt; 132: MID26692025 131202
#&gt; 133: MID26692254 520201
#&gt; 134: MID26692254 400404
#&gt; 135: MID26692254 450701</code></pre>
<p><strong>Confirm results.</strong> We nullify the key automatically
assigned by <code>merge()</code> and then compare the equality of
results.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Three equivalent inner joins</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">merge</span>(DT, toy_student[, .(mcid)], <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), <span class="at">all =</span> <span class="cn">FALSE</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setkey</span>(x, <span class="cn">NULL</span>)</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> DT[toy_student, .(mcid, cip6), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> toy_student[DT, .(mcid, cip6), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Check equality</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(x, y)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(x, z)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span></code></pre></div>
<p><strong>Selecting columns.</strong> In either method, we can select
columns from both data frames. The difference being that with
<code>merge()</code> we select the columns by explicitly subsetting the
two data frames.</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecting columns from both data frames using merge()</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">merge</span>(DT[, .(mcid)], toy_student[, .(mcid, institution)], <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), <span class="at">all =</span> <span class="cn">FALSE</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setkey</span>(x, <span class="cn">NULL</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>x[]</span></code></pre></div>
<pre><code>#&gt;             mcid   institution
#&gt;           &lt;char&gt;        &lt;char&gt;
#&gt;   1: MID25784187 Institution M
#&gt;   2: MID25784187 Institution M
#&gt;   3: MID25819358 Institution M
#&gt;   4: MID25819358 Institution M
#&gt;   5: MID25828870 Institution M
#&gt;  ---                          
#&gt; 131: MID26692025 Institution L
#&gt; 132: MID26692025 Institution L
#&gt; 133: MID26692254 Institution L
#&gt; 134: MID26692254 Institution L
#&gt; 135: MID26692254 Institution L</code></pre>
<p>In the <code>X[Y, j]</code> syntax, however, we can list the columns
to be returned from both data frames in the <code>j</code> list, that
is, <code>.(var1, var2, etc.)</code>, without subsetting the original
two data frames.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Repeat using X[Y, j] syntax</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> DT[toy_student, .(mcid, institution), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check equality</span></span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(x, y)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span></code></pre></div>
</div>
<div id="degree-seeking" class="section level2">
<h2>Degree seeking</h2>
<p>Returning to the original context, we require only the IDs from our
data sufficient data frame.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Unique IDs that are data sufficient</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid)]</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">unique</span>(DT)</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;               mcid
#&gt;             &lt;char&gt;
#&gt;     1: MID25783135
#&gt;     2: MID25783162
#&gt;     3: MID25783178
#&gt;     4: MID25783195
#&gt;     5: MID25783220
#&gt;    ---            
#&gt; 63948: MID26697574
#&gt; 63949: MID26697576
#&gt; 63950: MID26697599
#&gt; 63951: MID26697615
#&gt; 63952: MID26697623</code></pre>
<p>We now filter for degree seeking using the <code>student</code> data
table.</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[student, .(mcid), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;               mcid
#&gt;             &lt;char&gt;
#&gt;     1: MID25783135
#&gt;     2: MID25783162
#&gt;     3: MID25783178
#&gt;     4: MID25783195
#&gt;     5: MID25783220
#&gt;    ---            
#&gt; 63948: MID26697574
#&gt; 63949: MID26697576
#&gt; 63950: MID26697599
#&gt; 63951: MID26697615
#&gt; 63952: MID26697623</code></pre>
<p>The number of observations doesn’t change because the practice data
sets in midfielddata are all degree-seeking. This is not true of the
research data available to MIDFIELD partners.</p>
</div>
<div id="closing" class="section level2">
<h2>Closing</h2>
<p>Using data.table syntax, we demonstrate inner joins to add columns
from midfielddata tables to a working data frame and filter for matching
rows.</p>
<p>Filtering for degree seeking is typical in MIDFIELD research because
non-degree-seeking students are of little interest in most studies.</p>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<div id="refs">

</div>
</div>
<div id="appendix" class="section level2">
<h2>Appendix</h2>
<p>We conclude each vignette by collecting its code chunks in a single,
condensed script for the convenience of those who wish to copy it into
their own R file.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Packages</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfieldr&quot;</span>)</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfielddata&quot;</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(<span class="st">&quot;data.table&quot;</span>))</span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing options for data.table</span></span>
<span id="cb21-7"><a href="#cb21-7" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(</span>
<span id="cb21-8"><a href="#cb21-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.nrows =</span> <span class="dv">55</span>,</span>
<span id="cb21-9"><a href="#cb21-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.topn =</span> <span class="dv">5</span>,</span>
<span id="cb21-10"><a href="#cb21-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.class =</span> <span class="cn">TRUE</span></span>
<span id="cb21-11"><a href="#cb21-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb21-12"><a href="#cb21-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-13"><a href="#cb21-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data sets from midfielddata</span></span>
<span id="cb21-14"><a href="#cb21-14" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(student, term)</span>
<span id="cb21-15"><a href="#cb21-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-16"><a href="#cb21-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for data sufficiency</span></span>
<span id="cb21-17"><a href="#cb21-17" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">copy</span>(term)</span>
<span id="cb21-18"><a href="#cb21-18" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_timely_term</span>(DT, term)</span>
<span id="cb21-19"><a href="#cb21-19" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_data_sufficiency</span>(DT, term)</span>
<span id="cb21-20"><a href="#cb21-20" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[data_sufficiency <span class="sc">==</span> <span class="st">&quot;include&quot;</span>]</span>
<span id="cb21-21"><a href="#cb21-21" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid, cip6)]</span>
<span id="cb21-22"><a href="#cb21-22" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">unique</span>(DT)</span>
<span id="cb21-23"><a href="#cb21-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-24"><a href="#cb21-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Three equivalent inner joins</span></span>
<span id="cb21-25"><a href="#cb21-25" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">merge</span>(DT, toy_student[, .(mcid)], <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), <span class="at">all =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-26"><a href="#cb21-26" aria-hidden="true" tabindex="-1"></a><span class="fu">setkey</span>(x, <span class="cn">NULL</span>)</span>
<span id="cb21-27"><a href="#cb21-27" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> DT[toy_student, .(mcid, cip6), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb21-28"><a href="#cb21-28" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> toy_student[DT, .(mcid, cip6), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb21-29"><a href="#cb21-29" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(x, y)</span>
<span id="cb21-30"><a href="#cb21-30" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(x, z)</span>
<span id="cb21-31"><a href="#cb21-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-32"><a href="#cb21-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Selecting columns</span></span>
<span id="cb21-33"><a href="#cb21-33" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">merge</span>(DT[, .(mcid)], toy_student[, .(mcid, institution)], <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), <span class="at">all =</span> <span class="cn">FALSE</span>)</span>
<span id="cb21-34"><a href="#cb21-34" aria-hidden="true" tabindex="-1"></a><span class="fu">setkey</span>(x, <span class="cn">NULL</span>)</span>
<span id="cb21-35"><a href="#cb21-35" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> DT[toy_student, .(mcid, institution), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb21-36"><a href="#cb21-36" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(x, y)</span>
<span id="cb21-37"><a href="#cb21-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-38"><a href="#cb21-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Degree seeking</span></span>
<span id="cb21-39"><a href="#cb21-39" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid)]</span>
<span id="cb21-40"><a href="#cb21-40" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">unique</span>(DT)</span>
<span id="cb21-41"><a href="#cb21-41" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[student, .(mcid), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span></code></pre></div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
