<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />

<meta name="author" content="Richard Layton" />

<meta name="date" content="2022-06-21" />

<title>Case study: Data</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Case study: Data</h1>
<h4 class="author">Richard Layton</h4>
<h4 class="date">2022-06-21</h4>



<p>Part 2 of a case study in four parts:</p>
<ul>
<li><a href="art-001-case-goals.html">Goals.</a> Describing the study
parameters.<br />
</li>
<li><a href="art-002-case-data.html">Data.</a> Transforming the data to
yield the observations of interest.</li>
<li><a href="art-003-case-metrics.html">Metrics.</a> Calculating summary
statistics and metrics.</li>
<li><a href="art-004-case-displays.html">Displays.</a> Creating tables
and charts to display results.</li>
</ul>
<div id="preface" class="section level2">
<h2>Preface</h2>
<p>Our data processing goal is to reduce the source data tables to the
specific observations needed to compute our metrics. The data processing
tasks include a combination of filtering observations (rows), creating,
renaming, and recoding variables (columns), and joining data frames.</p>
<p>The analysis is organized to produce two data frames—students ever
enrolled in the programs and students graduating from the programs—that
are joined and written to file as a starting point for the next section
of the case study.</p>
<p>If you are writing your own script to follow along, we start with
these packages:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfieldr&quot;</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfielddata&quot;</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(<span class="st">&quot;data.table&quot;</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing options for data.table</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.nrows =</span> <span class="dv">15</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.topn =</span> <span class="dv">5</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.class =</span> <span class="cn">TRUE</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
</div>
<div id="import-data" class="section level2">
<h2>Import data</h2>
<p>All MIDFIELD data are in block-record form, that is, every row is an
observation (keyed by student ID) and every column is a variable. Data
structure is explored in greater detail in the <a href="art-000-getting-started.html">Getting started</a> vignette.</p>
<p><strong>Importing.</strong> Load three of the midfielddata data
tables.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load three data sets from midfielddata</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(student, term, degree)</span></code></pre></div>
</div>
<div id="gather-ever-enrolled" class="section level2">
<h2>Gather ever enrolled</h2>
<p><strong>Copying.</strong> Copy the <code>term</code> data set to
create the working data frame (<code>DT</code>), leaving
<code>term</code> unaltered for later use.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a working data frame</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">copy</span>(term)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(DT)</span></code></pre></div>
<pre><code>#&gt; Classes &#39;data.table&#39; and &#39;data.frame&#39;:   710841 obs. of  13 variables:
#&gt;  $ mcid               : chr  &quot;MID25783135&quot; &quot;MID25783135&quot; &quot;MID25783156&quot; &quot;MID25783156&quot; ...
#&gt;  $ institution        : chr  &quot;Institution M&quot; &quot;Institution M&quot; &quot;Institution M&quot; &quot;Institution M&quot; ...
#&gt;  $ term               : chr  &quot;19911&quot; &quot;19913&quot; &quot;20011&quot; &quot;20013&quot; ...
#&gt;  $ cip6               : chr  &quot;520101&quot; &quot;520101&quot; &quot;040201&quot; &quot;040201&quot; ...
#&gt;  $ level              : chr  &quot;01 Freshman&quot; &quot;02 Sophomore&quot; &quot;01 Freshman&quot; &quot;02 Sophomore&quot; ...
#&gt;  $ standing           : chr  &quot;Good Standing&quot; &quot;Good Standing&quot; &quot;Good Standing&quot; &quot;Good Standing&quot; ...
#&gt;  $ coop               : chr  &quot;No&quot; &quot;No&quot; &quot;No&quot; &quot;No&quot; ...
#&gt;  $ hours_term         : num  19 14 14 16 16 17 18 18 17 9 ...
#&gt;  $ hours_term_attempt : num  19 14 14 16 16 17 18 18 17 13 ...
#&gt;  $ hours_cumul        : num  19 33 14 30 46 63 81 99 17 26 ...
#&gt;  $ hours_cumul_attempt: num  19 33 14 30 46 63 81 99 17 30 ...
#&gt;  $ gpa_term           : num  2.47 3.21 3.07 3.62 3.13 3.82 4 3.5 2.53 1.61 ...
#&gt;  $ gpa_cumul          : num  2.47 2.79 3.07 3.36 3.28 3.42 3.55 3.54 2.53 2.13 ...
#&gt;  - attr(*, &quot;.internal.selfref&quot;)=&lt;externalptr&gt; 
#&gt;  - attr(*, &quot;index&quot;)= int(0)</code></pre>
<p>The result has 710,841 observations. We will usually note the number
of observations as they change.</p>
<p><strong>Filtering.</strong> In this study, only two variables from
the <code>term</code> data are needed to start: student ID
<code>mcid</code> and program code <code>cip6</code>. We drop
unnecessary columns then remove duplicate rows such that we have unique
combinations of student ID and program CIP.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Minimize the dimensions of the data</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid, cip6)]</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">unique</span>(DT)</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;                mcid   cip6
#&gt;              &lt;char&gt; &lt;char&gt;
#&gt;      1: MID25783135 520101
#&gt;      2: MID25783156 040201
#&gt;      3: MID25783162 140102
#&gt;      4: MID25783162 520301
#&gt;      5: MID25783162 521401
#&gt;     ---                   
#&gt; 161692: MID26697682 240101
#&gt; 161693: MID26697685 300000
#&gt; 161694: MID26697685 521201
#&gt; 161695: MID26697689 240101
#&gt; 161696: MID26697702 240101</code></pre>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Count unique IDs</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(DT<span class="sc">$</span>mcid))</span></code></pre></div>
<pre><code>#&gt; [1] 94028</code></pre>
<p>The result has 161,696 observations of 94,028 unique students. The
number of unique students is smaller than the number of observations
because some students change programs over their course of study. Here
we have one row per unique combination of student (<code>mcid</code>)
and program code (<code>cip6</code>).</p>
</div>
<div id="filter-for-data-sufficiency" class="section level2">
<h2>Filter for data sufficiency</h2>
<p>Some student records near the lower and upper terms that bound the
available data must be excluded to prevent false summaries involving
timely program completion. To apply this filter, we determine the timely
completion term then data sufficiency.</p>
<p><strong>Creating variables.</strong> Using information in
<code>term</code>, we add the <code>timely_term</code> variable as well
as supporting variables used in its construction.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate a timely completion term for every student</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_timely_term</span>(DT, <span class="at">midfield_term =</span> term)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;                mcid   cip6 term_i     level_i adj_span timely_term
#&gt;              &lt;char&gt; &lt;char&gt; &lt;char&gt;      &lt;char&gt;    &lt;num&gt;      &lt;char&gt;
#&gt;      1: MID25783135 520101  19911 01 Freshman        6       19963
#&gt;      2: MID25783156 040201  20011 01 Freshman        6       20063
#&gt;      3: MID25783162 140102  19921 01 Freshman        6       19973
#&gt;      4: MID25783162 520301  19921 01 Freshman        6       19973
#&gt;      5: MID25783162 521401  19921 01 Freshman        6       19973
#&gt;     ---                                                           
#&gt; 161692: MID26697682 240101  20163 01 Freshman        6       20221
#&gt; 161693: MID26697685 300000  20151 01 Freshman        6       20203
#&gt; 161694: MID26697685 521201  20151 01 Freshman        6       20203
#&gt; 161695: MID26697689 240101  20163   04 Senior        3       20191
#&gt; 161696: MID26697702 240101  20161 01 Freshman        6       20213</code></pre>
<p><strong>Creating variables.</strong> Using information in
<code>term</code>, we add the <code>data_sufficiency</code> variable as
well as supporting variables used in its construction.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine data sufficiency for every student</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_data_sufficiency</span>(DT, <span class="at">midfield_term =</span> term)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;                mcid   cip6     level_i adj_span timely_term term_i lower_limit
#&gt;              &lt;char&gt; &lt;char&gt;      &lt;char&gt;    &lt;num&gt;      &lt;char&gt; &lt;char&gt;      &lt;char&gt;
#&gt;      1: MID25783135 520101 01 Freshman        6       19963  19911       19871
#&gt;      2: MID25783156 040201 01 Freshman        6       20063  20011       19871
#&gt;      3: MID25783162 140102 01 Freshman        6       19973  19921       19871
#&gt;      4: MID25783162 520301 01 Freshman        6       19973  19921       19871
#&gt;      5: MID25783162 521401 01 Freshman        6       19973  19921       19871
#&gt;     ---                                                                       
#&gt; 161692: MID26697682 240101 01 Freshman        6       20221  20163       20021
#&gt; 161693: MID26697685 300000 01 Freshman        6       20203  20151       20021
#&gt; 161694: MID26697685 521201 01 Freshman        6       20203  20151       20021
#&gt; 161695: MID26697689 240101   04 Senior        3       20191  20163       20021
#&gt; 161696: MID26697702 240101 01 Freshman        6       20213  20161       20021
#&gt;         upper_limit data_sufficiency
#&gt;              &lt;char&gt;           &lt;char&gt;
#&gt;      1:       20036          include
#&gt;      2:       20036    exclude-upper
#&gt;      3:       20036          include
#&gt;      4:       20036          include
#&gt;      5:       20036          include
#&gt;     ---                             
#&gt; 161692:       20164    exclude-upper
#&gt; 161693:       20164    exclude-upper
#&gt; 161694:       20164    exclude-upper
#&gt; 161695:       20164    exclude-upper
#&gt; 161696:       20164    exclude-upper</code></pre>
<p><strong>Filtering.</strong> We filter to retain observations for
which the data are sufficient then drop unnecessary columns.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Retain observations having sufficient data </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[data_sufficiency <span class="sc">==</span> <span class="st">&quot;include&quot;</span>]</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid, cip6)]</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;                mcid   cip6
#&gt;              &lt;char&gt; &lt;char&gt;
#&gt;      1: MID25783135 520101
#&gt;      2: MID25783162 140102
#&gt;      3: MID25783162 520301
#&gt;      4: MID25783162 521401
#&gt;      5: MID25783178 140102
#&gt;     ---                   
#&gt; 111928: MID26697576 521401
#&gt; 111929: MID26697599 110401
#&gt; 111930: MID26697599 521201
#&gt; 111931: MID26697615 500901
#&gt; 111932: MID26697623 451001</code></pre>
<p>The result has 111,932 observations of 63,952 unique students.</p>
</div>
<div id="filter-for-degree-seeking" class="section level2">
<h2>Filter for degree-seeking</h2>
<p>In studying stickiness, we exclude non-degree-seeking students. We
filter such students using the <code>student</code> data which contains
only degree seeking students.</p>
<p><strong>Filtering.</strong> Retain degree-seeking students only.</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Retain degree-seeking students</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">filter_match</span>(DT, <span class="at">match_to =</span> student, <span class="at">by_col =</span> <span class="st">&quot;mcid&quot;</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;                mcid   cip6
#&gt;              &lt;char&gt; &lt;char&gt;
#&gt;      1: MID25783135 520101
#&gt;      2: MID25783162 140102
#&gt;      3: MID25783162 520301
#&gt;      4: MID25783162 521401
#&gt;      5: MID25783178 140102
#&gt;     ---                   
#&gt; 111928: MID26697576 521401
#&gt; 111929: MID26697599 110401
#&gt; 111930: MID26697599 521201
#&gt; 111931: MID26697615 500901
#&gt; 111932: MID26697623 451001</code></pre>
<p>The result has 111,932 observations. (No change is expected in this
example because all students in the midfielddata practice data are
degree-seeking.)</p>
</div>
<div id="filter-by-program" class="section level2">
<h2>Filter by program</h2>
<p>To filter by program, we have to construct a data frame of labels for
our four engineering programs keyed by the US <em>Classification of
Instructional Programs</em> (CIP) codes. These codes are bundled with
midfieldr in the <code>cip</code> data set.</p>
<p>The <code>cip6</code> variable in our data is the 6-digit code for
programs in which students are enrolled in a given term.</p>
<p>Having already searched the <code>cip</code> data set for our
programs, we report the results: Civil Engineering CIPs start with 1408,
Electrical Engineering 1410, Mechanical Engineering 1419, and
Industrial/Systems Engineering 1427, 1435, 1436, and 1437.</p>
<p><strong>Filtering</strong> Gather the 6-digit CIP codes for the
programs in the case study. Drop unnecessary variables.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Gather program CIP codes</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>study_program <span class="ot">&lt;-</span> <span class="fu">filter_search</span>(cip, <span class="at">keep_text =</span> <span class="fu">c</span>(<span class="st">&quot;^1408&quot;</span>, <span class="st">&quot;^1410&quot;</span>, <span class="st">&quot;^1419&quot;</span>, <span class="st">&quot;^1427&quot;</span>, <span class="st">&quot;^1435&quot;</span>, <span class="st">&quot;^1436&quot;</span>, <span class="st">&quot;^1437&quot;</span>))</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>study_program <span class="ot">&lt;-</span> study_program[, .(cip6, cip6name)]</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>study_program[]</span></code></pre></div>
<pre><code>#&gt;       cip6                                                      cip6name
#&gt;     &lt;char&gt;                                                        &lt;char&gt;
#&gt;  1: 140801                                    Civil Engineering, General
#&gt;  2: 140802                                      Geotechnical Engineering
#&gt;  3: 140803                                        Structural Engineering
#&gt;  4: 140804                        Transportation and Highway Engineering
#&gt;  5: 140805                                   Water Resources Engineering
#&gt;  6: 140899                                      Civil Engineering, Other
#&gt;  7: 141001        Electrical, Electronics and Communications Engineering
#&gt;  8: 141003                                 Laser and Optical Engineering
#&gt;  9: 141004                                Telecommunications Engineering
#&gt; 10: 141099 Electrical, Electronics and Communications Engineering, Other
#&gt; 11: 141901                                        Mechanical Engineering
#&gt; 12: 142701                                           Systems Engineering
#&gt; 13: 143501                                        Industrial Engineering
#&gt; 14: 143601                                     Manufacturing Engineering
#&gt; 15: 143701                                           Operations Research</code></pre>
<p><strong>Creating variables.</strong> Add a variable to label each of
these 15 programs with one of the four conventional program
abbreviations we will use in comparing metrics, i.e., Civil (CE),
Electrical (EE), Mechanical (ME), and Industrial/Systems Engineering
(ISE).</p>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign four program names by 6-digit CIP code</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>study_program[, program <span class="sc">:</span><span class="er">=</span> <span class="fu">fcase</span>(</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%like%</span> <span class="st">&quot;^1408&quot;</span>, <span class="st">&quot;CE&quot;</span>, </span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%like%</span> <span class="st">&quot;^1410&quot;</span>, <span class="st">&quot;EE&quot;</span>, </span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%like%</span> <span class="st">&quot;^1419&quot;</span>, <span class="st">&quot;ME&quot;</span>, </span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%between%</span> <span class="fu">c</span>(<span class="st">&quot;142701&quot;</span>, <span class="st">&quot;143701&quot;</span>), <span class="st">&quot;ISE&quot;</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>)]</span>
<span id="cb19-8"><a href="#cb19-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb19-9"><a href="#cb19-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Confirm that abbreviations match the longer program names</span></span>
<span id="cb19-10"><a href="#cb19-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(study_program[, .(cip6name, program)])</span></code></pre></div>
<pre><code>#&gt;                                                          cip6name program
#&gt;                                                            &lt;char&gt;  &lt;char&gt;
#&gt;  1:                                    Civil Engineering, General      CE
#&gt;  2:                                      Geotechnical Engineering      CE
#&gt;  3:                                        Structural Engineering      CE
#&gt;  4:                        Transportation and Highway Engineering      CE
#&gt;  5:                                   Water Resources Engineering      CE
#&gt;  6:                                      Civil Engineering, Other      CE
#&gt;  7:        Electrical, Electronics and Communications Engineering      EE
#&gt;  8:                                 Laser and Optical Engineering      EE
#&gt;  9:                                Telecommunications Engineering      EE
#&gt; 10: Electrical, Electronics and Communications Engineering, Other      EE
#&gt; 11:                                        Mechanical Engineering      ME
#&gt; 12:                                           Systems Engineering     ISE
#&gt; 13:                                        Industrial Engineering     ISE
#&gt; 14:                                     Manufacturing Engineering     ISE
#&gt; 15:                                           Operations Research     ISE</code></pre>
<p><strong>Joining.</strong> Having checked that the new abbreviations
correctly represent the programs, we drop the <code>cip6name</code>
variable and join the program names to the working data frame.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Join program names to working data </span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>study_program[, cip6name <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">merge</span>(DT, study_program, <span class="at">by =</span> <span class="st">&quot;cip6&quot;</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;           cip6        mcid program
#&gt;         &lt;char&gt;      &lt;char&gt;  &lt;char&gt;
#&gt;      1: 010000 MID25787629    &lt;NA&gt;
#&gt;      2: 010000 MID25788554    &lt;NA&gt;
#&gt;      3: 010000 MID25788738    &lt;NA&gt;
#&gt;      4: 010000 MID25790164    &lt;NA&gt;
#&gt;      5: 010000 MID25793224    &lt;NA&gt;
#&gt;     ---                           
#&gt; 111928: 999999 MID26613031    &lt;NA&gt;
#&gt; 111929: 999999 MID26613035    &lt;NA&gt;
#&gt; 111930: 999999 MID26613108    &lt;NA&gt;
#&gt; 111931: 999999 MID26613476    &lt;NA&gt;
#&gt; 111932: 999999 MID26622821    &lt;NA&gt;</code></pre>
<p><strong>Filtering.</strong> All instances of NA programs are
dropped.</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Retain observations in our four programs </span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[<span class="sc">!</span><span class="fu">is.na</span>(program)]</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;         cip6        mcid program
#&gt;       &lt;char&gt;      &lt;char&gt;  &lt;char&gt;
#&gt;    1: 140801 MID25783441      CE
#&gt;    2: 140801 MID25784209      CE
#&gt;    3: 140801 MID25784489      CE
#&gt;    4: 140801 MID25784709      CE
#&gt;    5: 140801 MID25784742      CE
#&gt;   ---                           
#&gt; 7657: 143501 MID26692926     ISE
#&gt; 7658: 143501 MID26693368     ISE
#&gt; 7659: 143501 MID26695626     ISE
#&gt; 7660: 143501 MID26696116     ISE
#&gt; 7661: 143501 MID26696429     ISE</code></pre>
<p>The result has 7661 observations of 7133 unique students.</p>
<p><strong>Filtering.</strong> A program label can be associated with
multiple CIP codes. We drop the code and filter to remove duplicates to
ensure unique combinations of ID and program.</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop duplicate rows</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a>DT[, cip6 <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">unique</span>(DT)</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;              mcid program
#&gt;            &lt;char&gt;  &lt;char&gt;
#&gt;    1: MID25783441      CE
#&gt;    2: MID25784209      CE
#&gt;    3: MID25784489      CE
#&gt;    4: MID25784709      CE
#&gt;    5: MID25784742      CE
#&gt;   ---                    
#&gt; 7656: MID26692926     ISE
#&gt; 7657: MID26693368     ISE
#&gt; 7658: MID26695626     ISE
#&gt; 7659: MID26696116     ISE
#&gt; 7660: MID26696429     ISE</code></pre>
<p>The result has 7660 observations of 7133 unique students.</p>
<p><strong>Creating variables.</strong> Add a variable to label this
group as “ever” enrolled to distinguish them from the group of graduates
to be created next. Copy the data frame to a new name to save for
later.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conclude development of the ever-enrolled observations</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>DT[, group <span class="sc">:</span><span class="er">=</span> <span class="st">&quot;ever&quot;</span>]</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>ever <span class="ot">&lt;-</span> <span class="fu">copy</span>(DT)</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>ever[]</span></code></pre></div>
<pre><code>#&gt;              mcid program  group
#&gt;            &lt;char&gt;  &lt;char&gt; &lt;char&gt;
#&gt;    1: MID25783441      CE   ever
#&gt;    2: MID25784209      CE   ever
#&gt;    3: MID25784489      CE   ever
#&gt;    4: MID25784709      CE   ever
#&gt;    5: MID25784742      CE   ever
#&gt;   ---                           
#&gt; 7656: MID26692926     ISE   ever
#&gt; 7657: MID26693368     ISE   ever
#&gt; 7658: MID26695626     ISE   ever
#&gt; 7659: MID26696116     ISE   ever
#&gt; 7660: MID26696429     ISE   ever</code></pre>
</div>
<div id="gather-graduate-subset" class="section level2">
<h2>Gather graduate subset</h2>
<p><strong>Copying.</strong> Copy the <code>degree</code> data set to
create a new working data frame (DT), leaving <code>degree</code>
unaltered for later use.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Begin development of the graduate observations</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">copy</span>(degree)</span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(DT)</span></code></pre></div>
<pre><code>#&gt; Classes &#39;data.table&#39; and &#39;data.frame&#39;:   47499 obs. of  5 variables:
#&gt;  $ mcid       : chr  &quot;MID25783162&quot; &quot;MID25783178&quot; &quot;MID25783188&quot; &quot;MID25783195&quot; ...
#&gt;  $ institution: chr  &quot;Institution M&quot; &quot;Institution M&quot; &quot;Institution M&quot; &quot;Institution M&quot; ...
#&gt;  $ term_degree: chr  &quot;19963&quot; &quot;20001&quot; &quot;20023&quot; &quot;19966&quot; ...
#&gt;  $ cip6       : chr  &quot;521401&quot; &quot;143501&quot; &quot;230101&quot; &quot;521401&quot; ...
#&gt;  $ degree     : chr  &quot;Bachelor of Science&quot; &quot;Bachelor of Science&quot; &quot;Bachelor of Arts&quot; &quot;Bachelor of Science&quot; ...
#&gt;  - attr(*, &quot;.internal.selfref&quot;)=&lt;externalptr&gt;</code></pre>
<p><strong>Filtering.</strong> Students potentially counted as graduates
must be a subset of those in ever enrolled population.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Graduates must be a subset of ever-enrolled students</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">filter_match</span>(DT, <span class="at">match_to =</span> ever, <span class="at">by_col =</span> <span class="st">&quot;mcid&quot;</span>)</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;              mcid   institution term_degree   cip6              degree
#&gt;            &lt;char&gt;        &lt;char&gt;      &lt;char&gt; &lt;char&gt;              &lt;char&gt;
#&gt;    1: MID25783178 Institution M       20001 143501 Bachelor of Science
#&gt;    2: MID25783441 Institution M       19963 140801 Bachelor of Science
#&gt;    3: MID25783491 Institution M       20001 141001 Bachelor of Science
#&gt;    4: MID25783912 Institution M       20001 143501 Bachelor of Science
#&gt;    5: MID25784489 Institution M       19931 140801 Bachelor of Science
#&gt;   ---                                                                 
#&gt; 5386: MID26696771 Institution L       20143 141001 Bachelor of Science
#&gt; 5387: MID26696967 Institution L       20141 141901 Bachelor of Science
#&gt; 5388: MID26697163 Institution L       20133 141901 Bachelor of Science
#&gt; 5389: MID26697444 Institution L       20151 240199 Bachelor of Science
#&gt; 5390: MID26697447 Institution L       20154 141001 Bachelor of Science</code></pre>
<p>The result has 5390 observations of 5390 unique students. These IDs
have already been filtered for data sufficiency and degree-seeking.</p>
</div>
<div id="filter-by-completion-status" class="section level2">
<h2>Filter by completion status</h2>
<p>To be counted as a graduate in the stickiness metric, a student must
complete their program in a timely manner (default 6 years after
admission, with reduced spans for some transfer students).</p>
<p><strong>Add variables.</strong> Completion status requires the timely
completion term variable.</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate a timely completion term for every student</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_timely_term</span>(DT, <span class="at">midfield_term =</span> term)</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;              mcid   institution term_degree   cip6              degree term_i
#&gt;            &lt;char&gt;        &lt;char&gt;      &lt;char&gt; &lt;char&gt;              &lt;char&gt; &lt;char&gt;
#&gt;    1: MID25783178 Institution M       20001 143501 Bachelor of Science  19946
#&gt;    2: MID25783441 Institution M       19963 140801 Bachelor of Science  19921
#&gt;    3: MID25783491 Institution M       20001 141001 Bachelor of Science  19961
#&gt;    4: MID25783912 Institution M       20001 143501 Bachelor of Science  19971
#&gt;    5: MID25784489 Institution M       19931 140801 Bachelor of Science  19891
#&gt;   ---                                                                        
#&gt; 5386: MID26696771 Institution L       20143 141001 Bachelor of Science  20101
#&gt; 5387: MID26696967 Institution L       20141 141901 Bachelor of Science  20101
#&gt; 5388: MID26697163 Institution L       20133 141901 Bachelor of Science  20101
#&gt; 5389: MID26697444 Institution L       20151 240199 Bachelor of Science  20101
#&gt; 5390: MID26697447 Institution L       20154 141001 Bachelor of Science  20111
#&gt;            level_i adj_span timely_term
#&gt;             &lt;char&gt;    &lt;num&gt;      &lt;char&gt;
#&gt;    1:  01 Freshman        6       20003
#&gt;    2:  01 Freshman        6       19973
#&gt;    3:  01 Freshman        6       20013
#&gt;    4:  01 Freshman        6       20023
#&gt;    5:  01 Freshman        6       19943
#&gt;   ---                                  
#&gt; 5386: 02 Sophomore        5       20143
#&gt; 5387:  01 Freshman        6       20153
#&gt; 5388: 02 Sophomore        5       20143
#&gt; 5389:  01 Freshman        6       20153
#&gt; 5390:  01 Freshman        6       20163</code></pre>
<p><strong>Creating variables.</strong> Using information in
<code>degree</code>, we add the <code>completion_status</code> variable
as well as supporting variables used in its construction.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine program completion status for every student</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(DT, <span class="at">midfield_degree =</span> degree)</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;              mcid   institution   cip6              degree term_i      level_i
#&gt;            &lt;char&gt;        &lt;char&gt; &lt;char&gt;              &lt;char&gt; &lt;char&gt;       &lt;char&gt;
#&gt;    1: MID25783178 Institution M 143501 Bachelor of Science  19946  01 Freshman
#&gt;    2: MID25783441 Institution M 140801 Bachelor of Science  19921  01 Freshman
#&gt;    3: MID25783491 Institution M 141001 Bachelor of Science  19961  01 Freshman
#&gt;    4: MID25783912 Institution M 143501 Bachelor of Science  19971  01 Freshman
#&gt;    5: MID25784489 Institution M 140801 Bachelor of Science  19891  01 Freshman
#&gt;   ---                                                                         
#&gt; 5386: MID26696771 Institution L 141001 Bachelor of Science  20101 02 Sophomore
#&gt; 5387: MID26696967 Institution L 141901 Bachelor of Science  20101  01 Freshman
#&gt; 5388: MID26697163 Institution L 141901 Bachelor of Science  20101 02 Sophomore
#&gt; 5389: MID26697444 Institution L 240199 Bachelor of Science  20101  01 Freshman
#&gt; 5390: MID26697447 Institution L 141001 Bachelor of Science  20111  01 Freshman
#&gt;       adj_span timely_term term_degree completion completion_status
#&gt;          &lt;num&gt;      &lt;char&gt;      &lt;char&gt;     &lt;lgcl&gt;            &lt;char&gt;
#&gt;    1:        6       20003       20001       TRUE          positive
#&gt;    2:        6       19973       19963       TRUE          positive
#&gt;    3:        6       20013       20001       TRUE          positive
#&gt;    4:        6       20023       20001       TRUE          positive
#&gt;    5:        6       19943       19931       TRUE          positive
#&gt;   ---                                                              
#&gt; 5386:        5       20143       20143       TRUE          positive
#&gt; 5387:        6       20153       20141       TRUE          positive
#&gt; 5388:        5       20143       20133       TRUE          positive
#&gt; 5389:        6       20153       20151       TRUE          positive
#&gt; 5390:        6       20163       20154       TRUE          positive</code></pre>
<p><strong>Filtering.</strong> Retain records with “positive” completion
status (i.e. completion in 6 years or less) and drop unnecessary
variables.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Retain timely completers</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[completion_status <span class="sc">==</span> <span class="st">&quot;positive&quot;</span>]</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid, cip6)]</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;              mcid   cip6
#&gt;            &lt;char&gt; &lt;char&gt;
#&gt;    1: MID25783178 143501
#&gt;    2: MID25783441 140801
#&gt;    3: MID25783491 141001
#&gt;    4: MID25783912 143501
#&gt;    5: MID25784489 140801
#&gt;   ---                   
#&gt; 4610: MID26696771 141001
#&gt; 4611: MID26696967 141901
#&gt; 4612: MID26697163 141901
#&gt; 4613: MID26697444 240199
#&gt; 4614: MID26697447 141001</code></pre>
<p>The result has 4614 unique observations.</p>
</div>
<div id="filter-by-program-1" class="section level2">
<h2>Filter by program</h2>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Join program names to working data </span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">merge</span>(DT, study_program, <span class="at">by =</span> <span class="st">&quot;cip6&quot;</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[<span class="sc">!</span><span class="fu">is.na</span>(program)]</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Unique observations</span></span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid, program)]</span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">unique</span>(DT)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;              mcid program
#&gt;            &lt;char&gt;  &lt;char&gt;
#&gt;    1: MID25783441      CE
#&gt;    2: MID25784489      CE
#&gt;    3: MID25784709      CE
#&gt;    4: MID25784742      CE
#&gt;    5: MID25784843      CE
#&gt;   ---                    
#&gt; 3548: MID26689274     ISE
#&gt; 3549: MID26692926     ISE
#&gt; 3550: MID26695626     ISE
#&gt; 3551: MID26696116     ISE
#&gt; 3552: MID26696429     ISE</code></pre>
<p>The result has 3552 unique observations.</p>
<p><strong>Creating variables.</strong> Add a variable to label this
group as “grad” to distinguish them from the group of ever enrolled
students created earlier.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Conclude development of the graduate observations</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>DT[, group <span class="sc">:</span><span class="er">=</span> <span class="st">&quot;grad&quot;</span>]</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;              mcid program  group
#&gt;            &lt;char&gt;  &lt;char&gt; &lt;char&gt;
#&gt;    1: MID25783441      CE   grad
#&gt;    2: MID25784489      CE   grad
#&gt;    3: MID25784709      CE   grad
#&gt;    4: MID25784742      CE   grad
#&gt;    5: MID25784843      CE   grad
#&gt;   ---                           
#&gt; 3548: MID26689274     ISE   grad
#&gt; 3549: MID26692926     ISE   grad
#&gt; 3550: MID26695626     ISE   grad
#&gt; 3551: MID26696116     ISE   grad
#&gt; 3552: MID26696429     ISE   grad</code></pre>
</div>
<div id="join-ever-and-grad" class="section level2">
<h2>Join ever and grad</h2>
<p><strong>Joining.</strong> Combine the data frames of ever-enrolled
and graduates.</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Join the two data frames </span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">rbindlist</span>(<span class="fu">list</span>(DT, ever))</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;               mcid program  group
#&gt;             &lt;char&gt;  &lt;char&gt; &lt;char&gt;
#&gt;     1: MID25783441      CE   grad
#&gt;     2: MID25784489      CE   grad
#&gt;     3: MID25784709      CE   grad
#&gt;     4: MID25784742      CE   grad
#&gt;     5: MID25784843      CE   grad
#&gt;    ---                           
#&gt; 11208: MID26692926     ISE   ever
#&gt; 11209: MID26693368     ISE   ever
#&gt; 11210: MID26695626     ISE   ever
#&gt; 11211: MID26696116     ISE   ever
#&gt; 11212: MID26696429     ISE   ever</code></pre>
</div>
<div id="add-demographics" class="section level2">
<h2>Add demographics</h2>
<p><strong>Creating variables.</strong> Using information in
<code>student</code>, we add variables for race/ethnicity and sex.</p>
<div class="sourceCode" id="cb45"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add columns for student race/ethnicity and sex</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_race_sex</span>(DT, <span class="at">midfield_student =</span> student)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;               mcid program  group            race    sex
#&gt;             &lt;char&gt;  &lt;char&gt; &lt;char&gt;          &lt;char&gt; &lt;char&gt;
#&gt;     1: MID25783178     ISE   ever           Black   Male
#&gt;     2: MID25783178     ISE   grad           Black   Male
#&gt;     3: MID25783441      CE   ever           White   Male
#&gt;     4: MID25783441      CE   grad           White   Male
#&gt;     5: MID25783491      EE   ever           White   Male
#&gt;    ---                                                  
#&gt; 11208: MID26697163      ME   ever Hispanic/Latinx   Male
#&gt; 11209: MID26697163      ME   grad Hispanic/Latinx   Male
#&gt; 11210: MID26697444      ME   ever           White   Male
#&gt; 11211: MID26697447      EE   ever           Asian   Male
#&gt; 11212: MID26697447      EE   grad           Asian   Male</code></pre>
<p>The result has 11,212 observations of 7133 unique students. IDs
labeled “grad” are a subset of those labeled “ever”.</p>
<p><strong>Write to file.</strong> Results like these, used as inputs
for calculating summary statistics and metrics, are often written to
file as an intermediate result. In this case, the data frame above is
bundled with midfieldr as <code>study_stickiness_observ</code>.</p>
</div>
<div id="closing" class="section level2">
<h2>Closing</h2>
<p>Starting with the <code>student</code>, <code>term</code>, and
<code>degree</code> data tables, we processed the data to obtain the
observations needed to determine stickiness. This intermediate result is
written to file.</p>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<div id="refs">

</div>
</div>
<div id="appendix" class="section level2">
<h2>Appendix</h2>
<div id="complete-script" class="section level3">
<h3>Complete script</h3>
<p>We conclude each vignette by collecting its code chunks in a single,
condensed script for the convenience of those who wish to copy it into
their own R file.</p>
<div class="sourceCode" id="cb47"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Packages</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfieldr&quot;</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfielddata&quot;</span>)</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(<span class="st">&quot;data.table&quot;</span>))</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Import data</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(student, term, degree)</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Gather ever enrolled</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">copy</span>(term)</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid, cip6)]</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">unique</span>(DT)</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for data sufficiency</span></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_timely_term</span>(DT, <span class="at">midfield_term =</span> term)</span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_data_sufficiency</span>(DT, <span class="at">midfield_term =</span> term)</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[data_sufficiency <span class="sc">==</span> <span class="st">&quot;include&quot;</span>]</span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid, cip6)]</span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for degree-seeking</span></span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">filter_match</span>(DT, <span class="at">match_to =</span> student, <span class="at">by_col =</span> <span class="st">&quot;mcid&quot;</span>)</span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter by program</span></span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a>study_program <span class="ot">&lt;-</span> <span class="fu">filter_search</span>(cip, <span class="at">keep_text =</span> <span class="fu">c</span>(<span class="st">&quot;^1408&quot;</span>, <span class="st">&quot;^1410&quot;</span>, <span class="st">&quot;^1419&quot;</span>, <span class="st">&quot;^1427&quot;</span>, <span class="st">&quot;^1435&quot;</span>, <span class="st">&quot;^1436&quot;</span>, <span class="st">&quot;^1437&quot;</span>))</span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a>study_program <span class="ot">&lt;-</span> study_program[, .(cip6, cip6name)]</span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a>study_program[, program <span class="sc">:</span><span class="er">=</span> <span class="fu">fcase</span>(</span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%like%</span> <span class="st">&quot;^1408&quot;</span>, <span class="st">&quot;CE&quot;</span>, </span>
<span id="cb47-28"><a href="#cb47-28" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%like%</span> <span class="st">&quot;^1410&quot;</span>, <span class="st">&quot;EE&quot;</span>, </span>
<span id="cb47-29"><a href="#cb47-29" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%like%</span> <span class="st">&quot;^1419&quot;</span>, <span class="st">&quot;ME&quot;</span>, </span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%between%</span> <span class="fu">c</span>(<span class="st">&quot;142701&quot;</span>, <span class="st">&quot;143701&quot;</span>), <span class="st">&quot;ISE&quot;</span></span>
<span id="cb47-31"><a href="#cb47-31" aria-hidden="true" tabindex="-1"></a>)]</span>
<span id="cb47-32"><a href="#cb47-32" aria-hidden="true" tabindex="-1"></a>study_program[, cip6name <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb47-33"><a href="#cb47-33" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">merge</span>(DT, study_program, <span class="at">by =</span> <span class="st">&quot;cip6&quot;</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-34"><a href="#cb47-34" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[<span class="sc">!</span><span class="fu">is.na</span>(program)]</span>
<span id="cb47-35"><a href="#cb47-35" aria-hidden="true" tabindex="-1"></a>DT[, cip6 <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb47-36"><a href="#cb47-36" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">unique</span>(DT)</span>
<span id="cb47-37"><a href="#cb47-37" aria-hidden="true" tabindex="-1"></a>DT[, group <span class="sc">:</span><span class="er">=</span> <span class="st">&quot;ever&quot;</span>]</span>
<span id="cb47-38"><a href="#cb47-38" aria-hidden="true" tabindex="-1"></a>ever <span class="ot">&lt;-</span> <span class="fu">copy</span>(DT)</span>
<span id="cb47-39"><a href="#cb47-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-40"><a href="#cb47-40" aria-hidden="true" tabindex="-1"></a><span class="co"># Gather graduate subset</span></span>
<span id="cb47-41"><a href="#cb47-41" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">copy</span>(degree)</span>
<span id="cb47-42"><a href="#cb47-42" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">filter_match</span>(DT, <span class="at">match_to =</span> ever, <span class="at">by_col =</span> <span class="st">&quot;mcid&quot;</span>)</span>
<span id="cb47-43"><a href="#cb47-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-44"><a href="#cb47-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter by completion status</span></span>
<span id="cb47-45"><a href="#cb47-45" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_timely_term</span>(DT, <span class="at">midfield_term =</span> term)</span>
<span id="cb47-46"><a href="#cb47-46" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(DT, <span class="at">midfield_degree =</span> degree)</span>
<span id="cb47-47"><a href="#cb47-47" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[completion_status <span class="sc">==</span> <span class="st">&quot;positive&quot;</span>]</span>
<span id="cb47-48"><a href="#cb47-48" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid, cip6)]</span>
<span id="cb47-49"><a href="#cb47-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-50"><a href="#cb47-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter by program</span></span>
<span id="cb47-51"><a href="#cb47-51" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">merge</span>(DT, study_program, <span class="at">by =</span> <span class="st">&quot;cip6&quot;</span>, <span class="at">all.x =</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-52"><a href="#cb47-52" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[<span class="sc">!</span><span class="fu">is.na</span>(program)]</span>
<span id="cb47-53"><a href="#cb47-53" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid, program)]</span>
<span id="cb47-54"><a href="#cb47-54" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">unique</span>(DT)</span>
<span id="cb47-55"><a href="#cb47-55" aria-hidden="true" tabindex="-1"></a>DT[, group <span class="sc">:</span><span class="er">=</span> <span class="st">&quot;grad&quot;</span>]</span>
<span id="cb47-56"><a href="#cb47-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-57"><a href="#cb47-57" aria-hidden="true" tabindex="-1"></a><span class="co"># Join ever and grad</span></span>
<span id="cb47-58"><a href="#cb47-58" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">rbindlist</span>(<span class="fu">list</span>(DT, ever))</span>
<span id="cb47-59"><a href="#cb47-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-60"><a href="#cb47-60" aria-hidden="true" tabindex="-1"></a><span class="co"># Add demographics</span></span>
<span id="cb47-61"><a href="#cb47-61" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_race_sex</span>(DT, <span class="at">midfield_student =</span> student)</span></code></pre></div>
</div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
