---
title: "Case study---goals"
author: "Richard Layton"
date: "`r Sys.Date()`"
link-citations: yes
bibliography: ../inst/REFERENCES.bib
output: rmarkdown::html_vignette
csl: ../inst/information-science-and-technology.csl
vignette: >
  %\VignetteIndexEntry{Case study---goals}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
nocite: | 
resource_files: |
---

```{r setup, include = FALSE}
# code chunks
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = "#>",
  error = FALSE
)

# figures
knitr::opts_chunk$set(
    fig.path = "../man/figures/art-001-case-goals-", 
    fig.width = 6,
    fig.asp = 1 / 1.6,
    out.width = "70%",
    fig.align = "center"
)

# inline numbers
knitr::knit_hooks$set(inline = function(x) {
  if (!is.numeric(x)) {
    x
  } else if (x >= 10000) {
    prettyNum(round(x, 2), big.mark = ",")
  } else {
    prettyNum(round(x, 2))
  }
})
```

Part 1 of a condensed study illustrating how we work with longitudinal Student Unit Records (SUR). 

For reproducibility, we provide all the case-study code but without detailed explanations of syntax, functions, or arguments. Instead, we focus on the rationale underlying our process.  

We use these R packages:

- [midfieldr](https://midfieldr.github.io/midfieldr/) for tools to work with SURs
- [midfielddata](https://midfieldr.github.io/midfielddata/) for practice data
- [data.table](https://rdatatable.gitlab.io/data.table/) for manipulating data 
- [ggplot2](https://ggplot2.tidyverse.org/) for creating charts

For detailed discussion of midfieldr functions, see the collection of package [vignettes](https://midfieldr.github.io/midfieldr/articles/). 

## Outline

We present the study in four parts: 

- [Goals.](art-001-case-goals.html) Describing the study parameters.  
- [Data.](art-002-case-data.html) Transforming the data to yield the observations of interest.
- [Metrics.](art-003-case-metrics.html) Calculating summary statistics and metrics.
- [Displays.](art-004-case-displays.html) Creating tables and charts to display results.

## Goals

The goal of the case study is to compare the "stickiness" of Civil, Electrical, Industrial, and Mechanical Engineering programs with students grouped by race/ethnicity and sex. 

*Program stickiness* is the ratio of the number of students graduating from a program to the number of students ever enrolled in the program---a measure of a program's success in attracting, keeping, and graduating their undergraduates. 







