---
title: "Case study---introduction"
author: "Richard Layton"
date: "`r Sys.Date()`"
link-citations: yes
bibliography: ../inst/REFERENCES.bib
output: rmarkdown::html_vignette
csl: ../inst/information-science-and-technology.csl
vignette: >
  %\VignetteIndexEntry{Case study---introduction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
nocite: | 
resource_files: |
---

```{r setup, include = FALSE}
# code chunks
knitr::opts_chunk$set(
  echo = TRUE,
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = "#>",
  error = FALSE
)

# figures
knitr::opts_chunk$set(
    fig.path = "../man/figures/art-001-case-introduction-", 
    fig.width = 6,
    fig.asp = 1 / 1.6,
    out.width = "70%",
    fig.align = "center"
)

# inline numbers
knitr::knit_hooks$set(inline = function(x) {
  if (!is.numeric(x)) {
    x
  } else if (x >= 10000) {
    prettyNum(round(x, 2), big.mark = ",")
  } else {
    prettyNum(round(x, 2))
  }
})
```

Part 1 of a condensed study illustrating how we work with longitudinal Student Unit Records (SUR). 

Overall, we use R packages midfieldr, midfielddata, data.table, and ggplot2 without detailed explanation.  We provide those details in separate vignettes.  

## Goals

The analytical goal of the case study is to compare the "stickiness" of four engineering programs with students grouped by race/ethnicity, sex, and program using data from the midfielddata package. The programs are Civil, Electrical, Industrial, and Mechanical Engineering.

*Program stickiness* is the ratio of the number of students graduating from a program to the number of students ever enrolled in the program---a measure of a program's success in attracting, keeping, and graduating their undergraduates. 

The rhetorical goal of the case study is to illustrate our process of working with SURs. 

## Outline

In a typical workflow, we filter student unit records to retain desired observations, assign classifications such as program, sex, or race/ethnicity, select variables, group and summarize, and display the results in graphs or tables. Results are typically a comparative metric such as graduation rate, stickiness, migration yield, etc. 

We present the study in five parts: 

- [Introduction.](art-001-case-introduction.html) Goals.  
- [Subsetting.](art-002-case-filter.html) Filter observations and select variables.  
- [Classifying.](art-003-case-classify.html) Construct variables that characterize or classify the record. 
- [Summarizing.](art-004-case-summarize.html) Group variables and count observations.
- [Displaying.](art-005-case-display.html) Create charts and tables for discussion.

These activities are not strictly sequential. At any point in the process, additional subsetting, classifying, summarizing, or displaying may be needed depending on the goals of the study and the shape of the data at that point. 

