<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />


<meta name="date" content="2022-06-27" />

<title>Programs</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>
<script>$(document).ready(function(){
    if (typeof $('[data-toggle="tooltip"]').tooltip === 'function') {
        $('[data-toggle="tooltip"]').tooltip();
    }
    if ($('[data-toggle="popover"]').popover === 'function') {
        $('[data-toggle="popover"]').popover();
    }
});
</script>
<style type="text/css">
.lightable-minimal {
border-collapse: separate;
border-spacing: 16px 1px;
width: 100%;
margin-bottom: 10px;
}
.lightable-minimal td {
margin-left: 5px;
margin-right: 5px;
}
.lightable-minimal th {
margin-left: 5px;
margin-right: 5px;
}
.lightable-minimal thead tr:last-child th {
border-bottom: 2px solid #00000050;
empty-cells: hide;
}
.lightable-minimal tbody tr:first-child td {
padding-top: 0.5em;
}
.lightable-minimal.lightable-hover tbody tr:hover {
background-color: #f5f5f5;
}
.lightable-minimal.lightable-striped tbody tr:nth-child(even) {
background-color: #f5f5f5;
}
.lightable-classic {
border-top: 0.16em solid #111111;
border-bottom: 0.16em solid #111111;
width: 100%;
margin-bottom: 10px;
margin: 10px 5px;
}
.lightable-classic tfoot tr td {
border: 0;
}
.lightable-classic tfoot tr:first-child td {
border-top: 0.14em solid #111111;
}
.lightable-classic caption {
color: #222222;
}
.lightable-classic td {
padding-left: 5px;
padding-right: 5px;
color: #222222;
}
.lightable-classic th {
padding-left: 5px;
padding-right: 5px;
font-weight: normal;
color: #222222;
}
.lightable-classic thead tr:last-child th {
border-bottom: 0.10em solid #111111;
}
.lightable-classic.lightable-hover tbody tr:hover {
background-color: #F9EEC1;
}
.lightable-classic.lightable-striped tbody tr:nth-child(even) {
background-color: #f5f5f5;
}
.lightable-classic-2 {
border-top: 3px double #111111;
border-bottom: 3px double #111111;
width: 100%;
margin-bottom: 10px;
}
.lightable-classic-2 tfoot tr td {
border: 0;
}
.lightable-classic-2 tfoot tr:first-child td {
border-top: 3px double #111111;
}
.lightable-classic-2 caption {
color: #222222;
}
.lightable-classic-2 td {
padding-left: 5px;
padding-right: 5px;
color: #222222;
}
.lightable-classic-2 th {
padding-left: 5px;
padding-right: 5px;
font-weight: normal;
color: #222222;
}
.lightable-classic-2 tbody tr:last-child td {
border-bottom: 3px double #111111;
}
.lightable-classic-2 thead tr:last-child th {
border-bottom: 1px solid #111111;
}
.lightable-classic-2.lightable-hover tbody tr:hover {
background-color: #F9EEC1;
}
.lightable-classic-2.lightable-striped tbody tr:nth-child(even) {
background-color: #f5f5f5;
}
.lightable-material {
min-width: 100%;
white-space: nowrap;
table-layout: fixed;
font-family: Roboto, sans-serif;
border: 1px solid #EEE;
border-collapse: collapse;
margin-bottom: 10px;
}
.lightable-material tfoot tr td {
border: 0;
}
.lightable-material tfoot tr:first-child td {
border-top: 1px solid #EEE;
}
.lightable-material th {
height: 56px;
padding-left: 16px;
padding-right: 16px;
}
.lightable-material td {
height: 52px;
padding-left: 16px;
padding-right: 16px;
border-top: 1px solid #eeeeee;
}
.lightable-material.lightable-hover tbody tr:hover {
background-color: #f5f5f5;
}
.lightable-material.lightable-striped tbody tr:nth-child(even) {
background-color: #f5f5f5;
}
.lightable-material.lightable-striped tbody td {
border: 0;
}
.lightable-material.lightable-striped thead tr:last-child th {
border-bottom: 1px solid #ddd;
}
.lightable-material-dark {
min-width: 100%;
white-space: nowrap;
table-layout: fixed;
font-family: Roboto, sans-serif;
border: 1px solid #FFFFFF12;
border-collapse: collapse;
margin-bottom: 10px;
background-color: #363640;
}
.lightable-material-dark tfoot tr td {
border: 0;
}
.lightable-material-dark tfoot tr:first-child td {
border-top: 1px solid #FFFFFF12;
}
.lightable-material-dark th {
height: 56px;
padding-left: 16px;
padding-right: 16px;
color: #FFFFFF60;
}
.lightable-material-dark td {
height: 52px;
padding-left: 16px;
padding-right: 16px;
color: #FFFFFF;
border-top: 1px solid #FFFFFF12;
}
.lightable-material-dark.lightable-hover tbody tr:hover {
background-color: #FFFFFF12;
}
.lightable-material-dark.lightable-striped tbody tr:nth-child(even) {
background-color: #FFFFFF12;
}
.lightable-material-dark.lightable-striped tbody td {
border: 0;
}
.lightable-material-dark.lightable-striped thead tr:last-child th {
border-bottom: 1px solid #FFFFFF12;
}
.lightable-paper {
width: 100%;
margin-bottom: 10px;
color: #444;
}
.lightable-paper tfoot tr td {
border: 0;
}
.lightable-paper tfoot tr:first-child td {
border-top: 1px solid #00000020;
}
.lightable-paper thead tr:last-child th {
color: #666;
vertical-align: bottom;
border-bottom: 1px solid #00000020;
line-height: 1.15em;
padding: 10px 5px;
}
.lightable-paper td {
vertical-align: middle;
border-bottom: 1px solid #00000010;
line-height: 1.15em;
padding: 7px 5px;
}
.lightable-paper.lightable-hover tbody tr:hover {
background-color: #F9EEC1;
}
.lightable-paper.lightable-striped tbody tr:nth-child(even) {
background-color: #00000008;
}
.lightable-paper.lightable-striped tbody td {
border: 0;
}
</style>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Programs</h1>
<h4 class="date">2022-06-27</h4>



<p>After subsetting longitudinal Student Unit Records (SURs) for data
sufficiency and degree seeking, a typical third step is to restrict a
study to students enrolled in specific programs.</p>
<p>Programs are encoded in the MIDFIELD data sets in the
<code>cip6</code> variable. To filter for programs under study, it is
necessary to know the 6-digit codes for the desired programs. The
<code>cip</code> data set in midfieldr provides a searchable source of
CIP program names and codes.</p>
<div id="preface" class="section level2">
<h2>Preface</h2>
<p>In the US, instructional programs are encoded by “CIP” codes. CIP is
the acronym for <em>Classification of Instructional Programs</em>, a
taxonomy of academic programs curated by the US Department of Education
<span class="citation">(<a href="#ref-NCES:2010" role="doc-biblioref">NCES, 2010</a>)</span>. The 2010 CIP codes are
included with midfieldr in the data set <code>cip</code>.</p>
<p>The IPEDS standard encoding format is a two-digit number followed by
a period, followed by a four-digit number, for example, 14.0102 <span class="citation">(<a href="#ref-NCES:2020" role="doc-biblioref">NCES,
2020</a>)</span>. MIDFIELD uses the same numerals, but omits the period,
i.e., 140102, and stores the variable as a character string.</p>
</div>
<div id="method" class="section level2">
<h2>Method</h2>
<p>We practice strategies of searching the <code>cip</code> data set for
programs and grouping programs with user-assigned program names.</p>
</div>
<div id="taxonomy" class="section level2">
<h2>Taxonomy</h2>
<p>Academic programs have three levels of codes and names:</p>
<ul>
<li>6-digit code, a specific program</li>
<li>4-digit code, a group of 6-digit programs of comparable content</li>
<li>2-digit code, a grouping of 4-digit groups of related content</li>
</ul>
<p>Specialties within a discipline are encoded at the 6-digit level, the
discipline itself is represented by one or more 4-digit codes (roughly
corresponding to an academic department), and a collection of
disciplines are represented by one or more 2-digit codes (roughly
corresponding to an academic college).</p>
<p>For example, Geotechnical Engineering (140802) is a specialty in
Civil Engineering (1408) which is a department in the college of
Engineering (14).</p>
<p>To illustrate the taxonomy in a little more detail, we show in the
table the programs assigned to the 2-digit code 41, “Science
Technologies, Technicians”. This 2-digit grouping is subdivided into 5
groups at the 4-digit level (codes 4100–4199) which are further
subdivided into 9 programs at the 6-digit level (codes
410000–419999).</p>
<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip2
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip2name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip4
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip4name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip6
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip6name
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
41
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Science Technologies, Technicians
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4100
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Science Technologies, Technicians, General
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
410000
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Science Technologies, Technicians, General
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
41
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
↓
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4101
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Biology Technician, Biotechnology Laboratory Technician
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
410101
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Biology Technician, Biotechnology Laboratory Technician
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
41
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
↓
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4102
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Nuclear and Industrial Radiologic Technologies, Technicians
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
410204
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Industrial Radiologic Technology, Technician
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
41
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
↓
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4102
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
↓
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
410205
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Nuclear, Nuclear Power Technology, Technician
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
41
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
↓
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4102
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
↓
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
410299
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Nuclear and Industrial Radiologic Technologies, Technicians, Other
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
41
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
↓
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4103
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Physical Science Technologies, Technicians
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
410301
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Chemical Technology, Technician
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
41
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
↓
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4103
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
↓
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
410303
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Chemical Process Technology
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
41
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
↓
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4103
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
↓
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
410399
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Physical Science Technologies, Technicians, Other
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
41
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
↓
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4199
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Science Technologies, Technicians, Other
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
419999
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Science Technologies, Technicians, Other
</td>
</tr>
</tbody>
</table>
<p>A 2-digit program can include anywhere from four 4-digit programs
(e.g., code 24 Liberal Arts and Sciences, General Studies and
Humanities) to 238 4-digit programs (e.g., code 51 Health Professions
and Related Clinical Sciences).</p>
<p>And 4-digit programs include anywhere from one 6-digit program (e.g.,
code 4100 above) to 37 6-digit programs (e.g., code 1313 Education).</p>
<p>Unfortunately, some disciplines can comprise more than one 4-digit
code. For example, the programs that comprise the broad discipline of
Industrial and Systems Engineering encompass four distinct 4-digit
codes: 1427 Systems Engineering, 1435 Industrial Engineering, 1436
Manufacturing Engineering, and 1437 Operations Research. Hence the
importance of being able to search all CIP data for programs of
interest.</p>
</div>
<div id="introduction-to-cip" class="section level2">
<h2>Introduction to <code>cip</code></h2>
<p>If you are writing your own script to follow along, we start with
these packages:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfieldr&quot;</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(<span class="st">&quot;data.table&quot;</span>))</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing options for data.table</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.nrows =</span> <span class="dv">55</span>,</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.topn =</span> <span class="dv">3</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.class =</span> <span class="cn">TRUE</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p>The CIP data is bundled with midfieldr.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Names of the CIP variables</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cip)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] &quot;cip2&quot;     &quot;cip2name&quot; &quot;cip4&quot;     &quot;cip4name&quot; &quot;cip6&quot;     &quot;cip6name&quot;</span></span></code></pre></div>
<p>All variables in <code>cip</code> are character strings, which
protects the leading zeros of some CIP codes.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View cip</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>cip</span></code></pre></div>
<pre><code>#&gt;         cip2                                                  cip2name   cip4
#&gt;       &lt;char&gt;                                                    &lt;char&gt; &lt;char&gt;
#&gt;    1:     01 Agriculture, Agricultural Operations and Related Sciences   0100
#&gt;    2:     01 Agriculture, Agricultural Operations and Related Sciences   0101
#&gt;    3:     01 Agriculture, Agricultural Operations and Related Sciences   0101
#&gt;   ---                                                                        
#&gt; 1580:     54                                                   History   5401
#&gt; 1581:     54                                                   History   5401
#&gt; 1582:     99                         NonIPEDS - Undecided, Unspecified   9999
#&gt;                                   cip4name   cip6
#&gt;                                     &lt;char&gt; &lt;char&gt;
#&gt;    1:                 Agriculture, General 010000
#&gt;    2: Agricultural Business and Management 010101
#&gt;    3: Agricultural Business and Management 010102
#&gt;   ---                                            
#&gt; 1580:                              History 540108
#&gt; 1581:                              History 540199
#&gt; 1582:    NonIPEDS - Undecided, Unspecified 999999
#&gt;                                             cip6name
#&gt;                                               &lt;char&gt;
#&gt;    1:                           Agriculture, General
#&gt;    2:  Agricultural Business and Management, General
#&gt;    3: Agribusiness, Agricultural Business Operations
#&gt;   ---                                               
#&gt; 1580:                               Military History
#&gt; 1581:                                 History, Other
#&gt; 1582:              NonIPEDS - Undecided, Unspecified</code></pre>
<p>View the data set help page by running</p>
<pre><code># Run in Console to view help page
? cip</code></pre>
<p>The number of unique programs.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2-digit level</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">unique</span>(cip<span class="sc">$</span>cip2))</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [1] &quot;01&quot; &quot;03&quot; &quot;04&quot; &quot;05&quot; &quot;09&quot; &quot;10&quot; &quot;11&quot; &quot;12&quot; &quot;13&quot; &quot;14&quot; &quot;15&quot; &quot;16&quot; &quot;19&quot; &quot;22&quot; &quot;23&quot;</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [16] &quot;24&quot; &quot;25&quot; &quot;26&quot; &quot;27&quot; &quot;28&quot; &quot;29&quot; &quot;30&quot; &quot;31&quot; &quot;32&quot; &quot;33&quot; &quot;34&quot; &quot;35&quot; &quot;36&quot; &quot;37&quot; &quot;38&quot;</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [31] &quot;39&quot; &quot;40&quot; &quot;41&quot; &quot;42&quot; &quot;43&quot; &quot;44&quot; &quot;45&quot; &quot;46&quot; &quot;47&quot; &quot;48&quot; &quot;49&quot; &quot;50&quot; &quot;51&quot; &quot;52&quot; &quot;54&quot;</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [46] &quot;99&quot;</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 4-digit level</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(cip<span class="sc">$</span>cip4))</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 394</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co"># 6-digit level</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(cip<span class="sc">$</span>cip6))</span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] 1582</span></span></code></pre></div>
<p>A sample of program names (<code>sample()</code> uses a random number
generator, so your result will differ from that shown).</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2-digit name sample</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(cip[, cip2name], <span class="dv">10</span>)</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [1] &quot;Education&quot;                                                   </span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [2] &quot;Foreign Languages, Literatures and Linguistics&quot;              </span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [3] &quot;Business, Management, Marketing and Related Support Services&quot;</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [4] &quot;Engineering&quot;                                                 </span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [5] &quot;Family and Consumer Sciences, Human Sciences&quot;                </span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [6] &quot;Engineering Technology&quot;                                      </span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [7] &quot;Health Professions and Related Clinical Sciences&quot;            </span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [8] &quot;Business, Management, Marketing and Related Support Services&quot;</span></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [9] &quot;Health Professions and Related Clinical Sciences&quot;            </span></span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [10] &quot;Physical Sciences&quot;</span></span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a><span class="co"># 4-digit name sample</span></span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(cip[, cip4name], <span class="dv">10</span>)</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [1] &quot;Allied Health Diagnostic, Intervention Treatment Professions&quot;          </span></span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [2] &quot;Applied Horticulture, Horticultural Business Services&quot;                 </span></span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [3] &quot;Ophthalmic and Optometric Support Services and Allied Professions&quot;     </span></span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [4] &quot;Specialized Sales, Merchandising and Marketing Operations&quot;             </span></span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [5] &quot;Engineering-Related Fields&quot;                                            </span></span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [6] &quot;Teacher Education and Professional Development, Specific Subject Areas&quot;</span></span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [7] &quot;Allied Health Diagnostic, Intervention Treatment Professions&quot;          </span></span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [8] &quot;Leatherworking and Upholstery&quot;                                         </span></span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [9] &quot;Health, Medical Preparatory Programs&quot;                                  </span></span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [10] &quot;Research and Experimental Psychology&quot;</span></span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a><span class="co"># 6-digit name sample</span></span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(cip[, cip6name], <span class="dv">10</span>)</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [1] &quot;Soil Sciences, Other&quot;                                 </span></span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [2] &quot;Health, Medical Physics&quot;                              </span></span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [3] &quot;Adult Literacy Tutor, Instructor&quot;                     </span></span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [4] &quot;Environmental Design, Architecture&quot;                   </span></span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [5] &quot;Advanced, Graduate Dentistry and Oral Sciences, Other&quot;</span></span>
<span id="cb7-34"><a href="#cb7-34" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [6] &quot;Dental Materials (MS, PhD)&quot;                           </span></span>
<span id="cb7-35"><a href="#cb7-35" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [7] &quot;Drafting and Design Technology, Technician, General&quot;  </span></span>
<span id="cb7-36"><a href="#cb7-36" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [8] &quot;Chemical Engineering Technology, Technician&quot;          </span></span>
<span id="cb7-37"><a href="#cb7-37" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  [9] &quot;Social Science Teacher Education&quot;                     </span></span>
<span id="cb7-38"><a href="#cb7-38" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [10] &quot;Sports and Exercise&quot;</span></span></code></pre></div>
</div>
<div id="using-a-keyword-search" class="section level2">
<h2>Using a keyword search</h2>
<p><code>filter_search()</code> is the midfieldr function for searching
the <code>cip</code> data set. View the help page by running</p>
<pre><code>? filter_search()</code></pre>
<p>The variables in <code>cip</code> are all characters and
<code>filter_search()</code> subsets a data frame using character search
terms. The arguments are:</p>
<ul>
<li><code>dframe</code> data frame to be subset</li>
<li><code>keep_text</code> character vector of search text for retaining
rows, not case-sensitive</li>
<li><code>drop_text</code> (optional) character vector of search text
for dropping rows</li>
<li><code>select</code> (optional) character vector of column names to
search and return, default all columns</li>
</ul>
<p>For example, filtering the CIP data for all programs containing the
word “engineering” yields 119 observations.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter basics</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(<span class="at">dframe =</span> cip, <span class="at">keep_text =</span> <span class="st">&quot;engineering&quot;</span>)</span></code></pre></div>
<pre><code>#&gt;        cip2                                         cip2name   cip4
#&gt;      &lt;char&gt;                                           &lt;char&gt; &lt;char&gt;
#&gt;   1:     14                                      Engineering   1401
#&gt;   2:     14                                      Engineering   1401
#&gt;   3:     14                                      Engineering   1402
#&gt;  ---                                                               
#&gt; 117:     29                            Military Technologies   2903
#&gt; 118:     29                            Military Technologies   2903
#&gt; 119:     51 Health Professions and Related Clinical Sciences   5123
#&gt;                                                   cip4name   cip6
#&gt;                                                     &lt;char&gt; &lt;char&gt;
#&gt;   1:                                  Engineering, General 140101
#&gt;   2:                                  Engineering, General 140102
#&gt;   3: Aerospace, Aeronautical and Astronautical Engineering 140201
#&gt;  ---                                                             
#&gt; 117:                             Military Applied Sciences 290301
#&gt; 118:                             Military Applied Sciences 290303
#&gt; 119:            Rehabilitation and Therapeutic Professions 512312
#&gt;                                                              cip6name
#&gt;                                                                &lt;char&gt;
#&gt;   1:                                             Engineering, General
#&gt;   2:                                                  Pre-Engineering
#&gt;   3:     Aerospace, Aeronautical and Astronautical, Space Engineering
#&gt;  ---                                                                 
#&gt; 117:                                       Combat Systems Engineering
#&gt; 118:                                            Engineering Acoustics
#&gt; 119: Assistive, Augmentative Technology and Rehabiliation Engineering</code></pre>
<p>The first two arguments in <code>filter_search()</code> do not have
to be named explicitly, but the optional <code>drop_text</code> and
<code>select</code> arguments do.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Optional arguments drop_text and select</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, </span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>              <span class="st">&quot;engineering&quot;</span>, </span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>              <span class="at">drop_text =</span> <span class="fu">c</span>(<span class="st">&quot;related&quot;</span>, <span class="st">&quot;technology&quot;</span>, <span class="st">&quot;technologies&quot;</span>), </span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>              <span class="at">select =</span> <span class="fu">c</span>(<span class="st">&quot;cip6&quot;</span>, <span class="st">&quot;cip6name&quot;</span>))</span></code></pre></div>
<pre><code>#&gt;       cip6                                                      cip6name
#&gt;     &lt;char&gt;                                                        &lt;char&gt;
#&gt;  1: 140101                                          Engineering, General
#&gt;  2: 140102                                               Pre-Engineering
#&gt;  3: 140201  Aerospace, Aeronautical and Astronautical, Space Engineering
#&gt;  4: 140301       Agricultural, Biological Engineering and Bioengineering
#&gt;  5: 140401                                     Architectural Engineering
#&gt;  6: 140501                               Biomedical, Medical Engineering
#&gt;  7: 140601                              Ceramic Sciences and Engineering
#&gt;  8: 140701                                          Chemical Engineering
#&gt;  9: 140702                         Chemical and Biomolecular Engineering
#&gt; 10: 140799                                   Chemical Engineering, Other
#&gt; 11: 140801                                    Civil Engineering, General
#&gt; 12: 140802                                      Geotechnical Engineering
#&gt; 13: 140803                                        Structural Engineering
#&gt; 14: 140804                        Transportation and Highway Engineering
#&gt; 15: 140805                                   Water Resources Engineering
#&gt; 16: 140899                                      Civil Engineering, Other
#&gt; 17: 140901                                 Computer Engineering, General
#&gt; 18: 140902                                 Computer Hardware Engineering
#&gt; 19: 140903                                 Computer Software Engineering
#&gt; 20: 140999                                   Computer Engineering, Other
#&gt; 21: 141001        Electrical, Electronics and Communications Engineering
#&gt; 22: 141003                                 Laser and Optical Engineering
#&gt; 23: 141004                                Telecommunications Engineering
#&gt; 24: 141099 Electrical, Electronics and Communications Engineering, Other
#&gt; 25: 141101                                         Engineering Mechanics
#&gt; 26: 141201                                           Engineering Physics
#&gt; 27: 141301                                           Engineering Science
#&gt; 28: 141401               Environmental, Environmental Health Engineering
#&gt; 29: 141801                                         Materials Engineering
#&gt; 30: 141901                                        Mechanical Engineering
#&gt; 31: 142001                                     Metallurgical Engineering
#&gt; 32: 142101                                Mining and Mineral Engineering
#&gt; 33: 142201                     Naval Architecture and Marine Engineering
#&gt; 34: 142301                                           Nuclear Engineering
#&gt; 35: 142401                                             Ocean Engineering
#&gt; 36: 142501                                         Petroleum Engineering
#&gt; 37: 142701                                           Systems Engineering
#&gt; 38: 142801                              Textile Sciences and Engineering
#&gt; 39: 143101                                             Materials Science
#&gt; 40: 143201                                 Polymer, Plastics Engineering
#&gt; 41: 143301                                      Construction Engineering
#&gt; 42: 143401                                            Forest Engineering
#&gt; 43: 143501                                        Industrial Engineering
#&gt; 44: 143601                                     Manufacturing Engineering
#&gt; 45: 143701                                           Operations Research
#&gt; 46: 143801                                         Surveying Engineering
#&gt; 47: 143901                           Geological, Geophysical Engineering
#&gt; 48: 144001                                 Paper Science and Engineering
#&gt; 49: 144101                                 Electromechanical Engineering
#&gt; 50: 144201             Mechatronics, Robotics and Automation Engineering
#&gt; 51: 144301                                       Biochemical Engineering
#&gt; 52: 144401                                         Engineering Chemistry
#&gt; 53: 144501                            Biological, Biosystems Engineering
#&gt; 54: 149999                                            Engineering, Other
#&gt;       cip6                                                      cip6name</code></pre>
<p>Columns in <code>select</code> are subset after filtering for
<code>keep_text</code> and <code>drop_text</code></p>
<p>Suppose we want to find the CIP codes and names for all programs in
Civil Engineering. The search is insensitive to case, so we start with
the following code chunk.</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Example 1 filter using keywords</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="st">&quot;civil&quot;</span>)</span></code></pre></div>
<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip2
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip2name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip4
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip4name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip6
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip6name
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
05
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Area, Ethnic, Cultural and Gender and Group Studies
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
0501
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Area Studies
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
050102
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
American, United States Studies, Civilization
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
05
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Area, Ethnic, Cultural and Gender and Group Studies
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
0501
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Area Studies
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
050103
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Asian Studies, Civilization
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
05
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Area, Ethnic, Cultural and Gender and Group Studies
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
0501
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Area Studies
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
050106
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
European Studies, Civilization
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1408
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
140801
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering, General
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1408
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
140802
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Geotechnical Engineering
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1408
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
140803
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Structural Engineering
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1408
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
140804
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Transportation and Highway Engineering
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1408
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
140805
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Water Resources Engineering
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1408
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
140899
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering, Other
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
15
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering Technology
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1502
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering Technologies, Technicians
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
150201
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering Technology, Technician
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
15
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering Technology
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1513
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Drafting, Design Engineering Technologies, Technicians
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
151304
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Drafting and Civil Engineering CAD, CADD
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
30
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Muti, Interdisciplinary Studies
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
3022
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Classical and Ancient, Oriental Studies - Multi, Interdisciplinary
Studies
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
302201
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Multi, Interdisciplinary Studies - Ancient Studies, Civilization
</td>
</tr>
</tbody>
</table>
<p>The search returns some programs with Civilization in their names as
well as Engineering Technology. If we wanted Civil Engineering only, we
can use a sequence of function calls, where the outcome of the one
operation is assigned to the first argument of the next operation.</p>
<p>The following code chunk could be read as, “Start with the
<code>cip</code> data frame, then keep any rows in which ‘civil’ is
detected, then keep any rows in which ‘engineering’ is detected, then
drop any rows in which ‘technology’ is detected.”</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First search</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>first_pass <span class="ot">&lt;-</span> <span class="fu">filter_search</span>(cip, <span class="st">&quot;civil&quot;</span>)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Refine the search</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>second_pass <span class="ot">&lt;-</span> <span class="fu">filter_search</span>(first_pass, <span class="st">&quot;engineering&quot;</span>)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Refine further</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>third_pass <span class="ot">&lt;-</span> <span class="fu">filter_search</span>(second_pass, <span class="at">drop_text =</span> <span class="st">&quot;technology&quot;</span>)</span></code></pre></div>
<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip2
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip2name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip4
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip4name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip6
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip6name
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1408
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
140801
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering, General
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1408
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
140802
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Geotechnical Engineering
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1408
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
140803
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Structural Engineering
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1408
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
140804
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Transportation and Highway Engineering
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1408
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
140805
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Water Resources Engineering
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1408
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
140899
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Civil Engineering, Other
</td>
</tr>
</tbody>
</table>
<p>Seeing that all Civil Engineering programs have the same
<code>cip4name</code>, we could have used
<code>keep_text = c(&quot;civil engineering&quot;)</code> to narrow the search to
rows that match the full phrase. For example,</p>
<div class="sourceCode" id="cb15"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="st">&quot;civil engineering&quot;</span>, <span class="at">drop_text =</span> <span class="st">&quot;technology&quot;</span>)</span></code></pre></div>
<p>produces the same result reported in the table above.</p>
<div id="exercises" class="section level3">
<h3>Exercises</h3>
<ol style="list-style-type: decimal">
<li><p>Determine the set of 6-digit CIP codes you would expect to be
used by a College of Business.</p></li>
<li><p>The social sciences 2-digit CIP does not necessarily include all
possible social science programs. Let anthropology, economics,
geography, linguistics, political science, jurisprudence, psychology,
and sociology be defined a social sciences. Determine the set of 6-digit
codes we would collect to study these programs.</p></li>
</ol>
</div>
</div>
<div id="using-a-numerical-code-search" class="section level2">
<h2>Using a numerical code search</h2>
<p>Suppose we want to study programs relating to German culture,
language, and literature. Using “german” for the <code>keep_text</code>
value yields</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Search on text</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="st">&quot;german&quot;</span>)</span></code></pre></div>
<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip2
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip2name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip4
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip4name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip6
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip6name
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
05
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Area, Ethnic, Cultural and Gender and Group Studies
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
0501
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Area Studies
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
050125
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
German Studies
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
13
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Education
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1313
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Teacher Education and Professional Development, Specific Subject Areas
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
131326
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
German Language Teacher Education
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
16
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Foreign Languages, Literatures and Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1605
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Germanic Languages, Literatures Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
160500
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Germanic Languages, Literatures and Linguistics, General
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
16
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Foreign Languages, Literatures and Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1605
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Germanic Languages, Literatures Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
160501
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
German Language and Literature
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
16
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Foreign Languages, Literatures and Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1605
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Germanic Languages, Literatures Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
160502
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Scandinavian Languages, Literatures and Linguistics
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
16
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Foreign Languages, Literatures and Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1605
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Germanic Languages, Literatures Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
160503
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Danish Language and Literature
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
16
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Foreign Languages, Literatures and Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1605
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Germanic Languages, Literatures Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
160504
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Dutch, Flemish Language and Literature
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
16
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Foreign Languages, Literatures and Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1605
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Germanic Languages, Literatures Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
160505
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Norwegian Language and Literature
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
16
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Foreign Languages, Literatures and Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1605
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Germanic Languages, Literatures Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
160506
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Swedish Language and Literature
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
16
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Foreign Languages, Literatures and Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1605
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Germanic Languages, Literatures Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
160599
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Germanic Languages, Literatures and Linguistics, Other
</td>
</tr>
</tbody>
</table>
<p>From the 6-digit program names we find only two that are of interest,
German Studies (050125) and German Language and Literature (160501). We
use a character vector to assign these two codes to the
<code>keep_text</code> argument.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Search on codes</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="fu">c</span>(<span class="st">&quot;050125&quot;</span>, <span class="st">&quot;160501&quot;</span>))</span></code></pre></div>
<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip2
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip2name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip4
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip4name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip6
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip6name
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
05
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Area, Ethnic, Cultural and Gender and Group Studies
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
0501
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Area Studies
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
050125
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
German Studies
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
16
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Foreign Languages, Literatures and Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1605
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Germanic Languages, Literatures Linguistics
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
160501
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
German Language and Literature
</td>
</tr>
</tbody>
</table>
<p>If the 6-digit codes are entered as integers, they produce an
error.</p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Search that produces an error</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="fu">c</span>(<span class="dv">050125</span>, <span class="dv">160501</span>))</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Error in filter_search(cip, c(50125, 160501)): Assertion on &#39;keep_text&#39; failed. Must be of class &#39;string&#39;, not &#39;double&#39;.</span></span></code></pre></div>
<div id="exercise" class="section level3">
<h3>Exercise</h3>
<ol style="list-style-type: decimal">
<li><p>In the Social sciences exercise in the previous section,
searching for “jurisprudence” produced two codes: “220203” and “220204.”
Search <code>cip</code> for these two codes and determine the 2-digit
program to which they belong.</p></li>
<li><p>Do an initial search on the term, “history.” From the
results,</p>
<ul>
<li>Identify the 2-digit CIP for history.<br />
</li>
<li>Use a numerical search for programs that start with that 2-digit
CIP.</li>
<li>Subset for the 6-digit CIPs and 6-digit CIP names.<br />
</li>
<li>Assign the result to the object name <code>exercise_cip</code>.</li>
</ul></li>
</ol>
<p>Answer given below to check your work.</p>
<pre><code>#&gt;      cip6                                            cip6name
#&gt;    &lt;char&gt;                                              &lt;char&gt;
#&gt; 1: 540101                                    History, General
#&gt; 2: 540102                    American History (United States)
#&gt; 3: 540103                                    European History
#&gt; 4: 540104    History and Philosophy of Science and Technology
#&gt; 5: 540105 Public, Applied History and Archival Administration
#&gt; 6: 540106                                       Asian History
#&gt; 7: 540107                                    Canadian History
#&gt; 8: 540108                                    Military History
#&gt; 9: 540199                                      History, Other</code></pre>
</div>
</div>
<div id="using-a-regular-expression-search" class="section level2">
<h2>Using a regular expression search</h2>
<p>Specifying 4-digit codes yields a data frame all 6-digit programs
containing the 4-digit string. We use the regular expression notation
<code>^</code> to match the start of the strings.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># example 3 filter using regular expressions</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="fu">c</span>(<span class="st">&quot;^1410&quot;</span>, <span class="st">&quot;^1419&quot;</span>))</span></code></pre></div>
<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip2
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip2name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip4
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip4name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip6
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip6name
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1410
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Electrical, Electronics and Communications Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
141001
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Electrical, Electronics and Communications Engineering
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1410
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Electrical, Electronics and Communications Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
141003
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Laser and Optical Engineering
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1410
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Electrical, Electronics and Communications Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
141004
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Telecommunications Engineering
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1410
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Electrical, Electronics and Communications Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
141099
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Electrical, Electronics and Communications Engineering, Other
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
14
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
1419
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Mechanical Engineering
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
141901
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Mechanical Engineering
</td>
</tr>
</tbody>
</table>
<p>The 2-digit series represent the most general groupings of related
programs. Here, the result includes all History programs.</p>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Search on 2-digit code</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="st">&quot;^54&quot;</span>)</span></code></pre></div>
<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip2
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip2name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip4
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip4name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip6
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip6name
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
54
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
5401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
540101
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History, General
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
54
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
5401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
540102
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
American History (United States)
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
54
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
5401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
540103
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
European History
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
54
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
5401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
540104
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History and Philosophy of Science and Technology
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
54
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
5401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
540105
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Public, Applied History and Archival Administration
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
54
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
5401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
540106
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Asian History
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
54
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
5401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
540107
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Canadian History
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
54
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
5401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
540108
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Military History
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
54
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
5401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
540199
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
History, Other
</td>
</tr>
</tbody>
</table>
<p>The series argument can include any combination of 2, 4, and 6-digit
codes. It can also be passed to the function as a character vector.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Search on vector of codes</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>codes_we_want <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;^24&quot;</span>, <span class="st">&quot;^4102&quot;</span>, <span class="st">&quot;^450202&quot;</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, codes_we_want)</span></code></pre></div>
<table class=" lightable-paper" style="font-family: &quot;Arial Narrow&quot;, arial, helvetica, sans-serif; margin-left: auto; margin-right: auto;">
<thead>
<tr>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip2
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip2name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip4
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip4name
</th>
<th style="text-align:right;background-color: #c7eae5 !important;">
cip6
</th>
<th style="text-align:left;background-color: #c7eae5 !important;">
cip6name
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
24
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Liberal Arts and Sciences, General Studies and Humanities
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
2401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Liberal Arts and Sciences, General Studies Humanities
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
240101
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Liberal Arts and Sciences, Liberal Studies
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
24
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Liberal Arts and Sciences, General Studies and Humanities
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
2401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Liberal Arts and Sciences, General Studies Humanities
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
240102
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
General Studies
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
24
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Liberal Arts and Sciences, General Studies and Humanities
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
2401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Liberal Arts and Sciences, General Studies Humanities
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
240103
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Humanities, Humanistic Studies
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
24
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Liberal Arts and Sciences, General Studies and Humanities
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
2401
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Liberal Arts and Sciences, General Studies Humanities
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
240199
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Liberal Arts and Sciences, General Studies and Humanities, Other
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
41
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Science Technologies, Technicians
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4102
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Nuclear and Industrial Radiologic Technologies, Technicians
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
410204
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Industrial Radiologic Technology, Technician
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
41
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Science Technologies, Technicians
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4102
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Nuclear and Industrial Radiologic Technologies, Technicians
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
410205
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Nuclear, Nuclear Power Technology, Technician
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
41
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Science Technologies, Technicians
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4102
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Nuclear and Industrial Radiologic Technologies, Technicians
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
410299
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Nuclear and Industrial Radiologic Technologies, Technicians, Other
</td>
</tr>
<tr>
<td style="text-align:right;color: black !important;background-color: white !important;">
45
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Social Sciences
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
4502
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Anthropology
</td>
<td style="text-align:right;color: black !important;background-color: white !important;">
450202
</td>
<td style="text-align:left;color: black !important;background-color: white !important;">
Physical Anthropology
</td>
</tr>
</tbody>
</table>
</div>
<div id="when-search-terms-cannot-be-found" class="section level2">
<h2>When search terms cannot be found</h2>
<p>If the <code>keep_text</code> argument includes terms that cannot be
found in the CIP data frame, the unsuccessful terms are identified in a
message and the successful terms produce the usual output.</p>
<p>For example, the following <code>keep_text</code> argument includes
three search terms that are not present in the CIP data (“111111”,
“^55”, and “Bogus”) and two that are (“050125” and “160501”).</p>
<div class="sourceCode" id="cb23"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Unsuccessful terms produce a message</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>sub_cip <span class="ot">&lt;-</span> <span class="fu">filter_search</span>(cip, <span class="fu">c</span>(<span class="st">&quot;050125&quot;</span>, <span class="st">&quot;111111&quot;</span>, <span class="st">&quot;160501&quot;</span>, <span class="st">&quot;Bogus&quot;</span>, <span class="st">&quot;^55&quot;</span>))</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Can&#39;t find these terms: 111111, Bogus, ^55</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a><span class="co"># But the successful terms are returned</span></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>sub_cip</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;      cip2                                            cip2name   cip4</span></span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;    &lt;char&gt;                                              &lt;char&gt; &lt;char&gt;</span></span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1:     05 Area, Ethnic, Cultural and Gender and Group Studies   0501</span></span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2:     16      Foreign Languages, Literatures and Linguistics   1605</span></span>
<span id="cb23-11"><a href="#cb23-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                                       cip4name   cip6</span></span>
<span id="cb23-12"><a href="#cb23-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                                         &lt;char&gt; &lt;char&gt;</span></span>
<span id="cb23-13"><a href="#cb23-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1:                                Area Studies 050125</span></span>
<span id="cb23-14"><a href="#cb23-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2: Germanic Languages, Literatures Linguistics 160501</span></span>
<span id="cb23-15"><a href="#cb23-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                          cip6name</span></span>
<span id="cb23-16"><a href="#cb23-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;                            &lt;char&gt;</span></span>
<span id="cb23-17"><a href="#cb23-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 1:                 German Studies</span></span>
<span id="cb23-18"><a href="#cb23-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 2: German Language and Literature</span></span></code></pre></div>
<p>However, as seen earlier, if none of the search terms are found, an
error occurs.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="co"># When none of the search terms are found</span></span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="fu">c</span>(<span class="st">&quot;111111&quot;</span>, <span class="st">&quot;Bogus&quot;</span>, <span class="st">&quot;^55&quot;</span>))</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; Error: The search result is empty. Possible causes are:</span></span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  * &#39;dframe&#39; contained no matches to terms in &#39;keep_text&#39;.</span></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  * &#39;drop_text&#39; eliminated all remaining rows.</span></span></code></pre></div>
</div>
<div id="cip-data-from-another-source" class="section level2">
<h2>CIP data from another source</h2>
<p>If you use a CIP data set from another source, it must have the same
structure as <code>cip</code>: six character columns named as
follows,</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Name and class of variables (columns) in cip</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">unlist</span>(<span class="fu">lapply</span>(cip, <span class="at">FUN =</span> class))</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;        cip2    cip2name        cip4    cip4name        cip6    cip6name </span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; &quot;character&quot; &quot;character&quot; &quot;character&quot; &quot;character&quot; &quot;character&quot; &quot;character&quot;</span></span></code></pre></div>
</div>
<div id="assigning-program-names" class="section level2">
<h2>Assigning program names</h2>
<p>Programs in MIDFIELD data sets are encoded by 6-digit CIP codes. As
we’ve shown, multiple 6-digit codes can be considered specialties within
a larger program with a 4-digit code or even a set of distinct 4-digit
codes. It is nearly always necessary therefore to assign our own program
labels to groups of 6-digit codes to include all observations relevant
to meet the needs of a study.</p>
<blockquote>
<p>To emphasize the point: When grouping and summarizing MIDFIELD data,
it is usually necessary to group by one’s own set of program names
instead of the CIP codes and names directly.</p>
</blockquote>
<p>We use our case study group of four engineering programs to
illustrate several methods for adding a <code>program</code> column to
the CIP data frame.</p>
<p>By searching <code>cip</code>, we can find that the 4-digit codes for
the four engineering programs are: Civil (1408), Electrical (1410),
Mechanical (1419), and Industrial/Systems (1427, 1435, 1436, and
1437).</p>
<p>We obtain their 6-digit CIP codes. The 4-digit names are appropriate
here. Our task is to create a variable with custom program names.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Changing the number of rows to print</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">datatable.print.nrows =</span> <span class="dv">15</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Four engineering programs</span></span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a>study_program <span class="ot">&lt;-</span> <span class="fu">filter_search</span>(cip, <span class="fu">c</span>(<span class="st">&quot;^1408&quot;</span>, <span class="st">&quot;^1410&quot;</span>, <span class="st">&quot;^1419&quot;</span>, <span class="st">&quot;^1427&quot;</span>, <span class="st">&quot;^1435&quot;</span>, <span class="st">&quot;^1436&quot;</span>, <span class="st">&quot;^1437&quot;</span>))</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Retain the needed columns</span></span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a>study_program <span class="ot">&lt;-</span> study_program[, .(cip6, cip4name)]</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the result</span></span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a>study_program[]</span></code></pre></div>
<pre><code>#&gt;       cip6                                               cip4name
#&gt;     &lt;char&gt;                                                 &lt;char&gt;
#&gt;  1: 140801                                      Civil Engineering
#&gt;  2: 140802                                      Civil Engineering
#&gt;  3: 140803                                      Civil Engineering
#&gt;  4: 140804                                      Civil Engineering
#&gt;  5: 140805                                      Civil Engineering
#&gt;  6: 140899                                      Civil Engineering
#&gt;  7: 141001 Electrical, Electronics and Communications Engineering
#&gt;  8: 141003 Electrical, Electronics and Communications Engineering
#&gt;  9: 141004 Electrical, Electronics and Communications Engineering
#&gt; 10: 141099 Electrical, Electronics and Communications Engineering
#&gt; 11: 141901                                 Mechanical Engineering
#&gt; 12: 142701                                    Systems Engineering
#&gt; 13: 143501                                 Industrial Engineering
#&gt; 14: 143601                              Manufacturing Engineering
#&gt; 15: 143701                                    Operations Research</code></pre>
<p>To make the assignments clear, our approach here will be to assign a
new <code>program</code> column with NA values, then edit the new column
values.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Assign a new column</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>study_program[, program <span class="sc">:</span><span class="er">=</span> <span class="cn">NA_character_</span>]</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-4"><a href="#cb28-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the result</span></span>
<span id="cb28-5"><a href="#cb28-5" aria-hidden="true" tabindex="-1"></a>study_program[]</span></code></pre></div>
<pre><code>#&gt;       cip6                                               cip4name program
#&gt;     &lt;char&gt;                                                 &lt;char&gt;  &lt;char&gt;
#&gt;  1: 140801                                      Civil Engineering    &lt;NA&gt;
#&gt;  2: 140802                                      Civil Engineering    &lt;NA&gt;
#&gt;  3: 140803                                      Civil Engineering    &lt;NA&gt;
#&gt;  4: 140804                                      Civil Engineering    &lt;NA&gt;
#&gt;  5: 140805                                      Civil Engineering    &lt;NA&gt;
#&gt;  6: 140899                                      Civil Engineering    &lt;NA&gt;
#&gt;  7: 141001 Electrical, Electronics and Communications Engineering    &lt;NA&gt;
#&gt;  8: 141003 Electrical, Electronics and Communications Engineering    &lt;NA&gt;
#&gt;  9: 141004 Electrical, Electronics and Communications Engineering    &lt;NA&gt;
#&gt; 10: 141099 Electrical, Electronics and Communications Engineering    &lt;NA&gt;
#&gt; 11: 141901                                 Mechanical Engineering    &lt;NA&gt;
#&gt; 12: 142701                                    Systems Engineering    &lt;NA&gt;
#&gt; 13: 143501                                 Industrial Engineering    &lt;NA&gt;
#&gt; 14: 143601                              Manufacturing Engineering    &lt;NA&gt;
#&gt; 15: 143701                                    Operations Research    &lt;NA&gt;</code></pre>
<div id="use-cip4name-ilike-to-recode-one-value" class="section level3">
<h3>1. Use <code>cip4name %ilike%</code> to recode one value</h3>
<p>The <code>%like%</code> function is essentially a wrapper function
around the base R <code>grepl()</code> function. The
<code>%ilike%</code> version is case-insensitive. See its help page by
running (the back-ticks facilitate a help search for terms starting with
a symbol):</p>
<div class="sourceCode" id="cb30"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>? <span class="st">`</span><span class="at">%like%</span><span class="st">`</span></span></code></pre></div>
<p>In this approach, we search for one distinctive term only. We’re
using abbreviations for compact output.</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode program using the 4-digit name</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>study_program[cip4name <span class="sc">%ilike%</span> <span class="st">&quot;electrical&quot;</span>,  program <span class="sc">:</span><span class="er">=</span> <span class="st">&quot;EE&quot;</span>]</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the result</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>study_program[]</span></code></pre></div>
<pre><code>#&gt;       cip6                                               cip4name program
#&gt;     &lt;char&gt;                                                 &lt;char&gt;  &lt;char&gt;
#&gt;  1: 140801                                      Civil Engineering    &lt;NA&gt;
#&gt;  2: 140802                                      Civil Engineering    &lt;NA&gt;
#&gt;  3: 140803                                      Civil Engineering    &lt;NA&gt;
#&gt;  4: 140804                                      Civil Engineering    &lt;NA&gt;
#&gt;  5: 140805                                      Civil Engineering    &lt;NA&gt;
#&gt;  6: 140899                                      Civil Engineering    &lt;NA&gt;
#&gt;  7: 141001 Electrical, Electronics and Communications Engineering      EE
#&gt;  8: 141003 Electrical, Electronics and Communications Engineering      EE
#&gt;  9: 141004 Electrical, Electronics and Communications Engineering      EE
#&gt; 10: 141099 Electrical, Electronics and Communications Engineering      EE
#&gt; 11: 141901                                 Mechanical Engineering    &lt;NA&gt;
#&gt; 12: 142701                                    Systems Engineering    &lt;NA&gt;
#&gt; 13: 143501                                 Industrial Engineering    &lt;NA&gt;
#&gt; 14: 143601                              Manufacturing Engineering    &lt;NA&gt;
#&gt; 15: 143701                                    Operations Research    &lt;NA&gt;</code></pre>
</div>
<div id="use-cip6-like-to-recode-one-value" class="section level3">
<h3>2. Use <code>cip6 %like%</code> to recode one value</h3>
<p>In our second approach, we use the <code>%like%</code> function
again, but apply it to a CIP code. Here we use the regular expression
<code>^1408</code> meaning “starts with 1408.”</p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode program using the 4-digit code</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>study_program[cip6 <span class="sc">%like%</span> <span class="st">&quot;^1408&quot;</span>,  program <span class="sc">:</span><span class="er">=</span> <span class="st">&quot;CE&quot;</span>]</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the result</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>study_program[]</span></code></pre></div>
<pre><code>#&gt;       cip6                                               cip4name program
#&gt;     &lt;char&gt;                                                 &lt;char&gt;  &lt;char&gt;
#&gt;  1: 140801                                      Civil Engineering      CE
#&gt;  2: 140802                                      Civil Engineering      CE
#&gt;  3: 140803                                      Civil Engineering      CE
#&gt;  4: 140804                                      Civil Engineering      CE
#&gt;  5: 140805                                      Civil Engineering      CE
#&gt;  6: 140899                                      Civil Engineering      CE
#&gt;  7: 141001 Electrical, Electronics and Communications Engineering      EE
#&gt;  8: 141003 Electrical, Electronics and Communications Engineering      EE
#&gt;  9: 141004 Electrical, Electronics and Communications Engineering      EE
#&gt; 10: 141099 Electrical, Electronics and Communications Engineering      EE
#&gt; 11: 141901                                 Mechanical Engineering    &lt;NA&gt;
#&gt; 12: 142701                                    Systems Engineering    &lt;NA&gt;
#&gt; 13: 143501                                 Industrial Engineering    &lt;NA&gt;
#&gt; 14: 143601                              Manufacturing Engineering    &lt;NA&gt;
#&gt; 15: 143701                                    Operations Research    &lt;NA&gt;</code></pre>
</div>
<div id="use-program-fcase-to-edit-all-values" class="section level3">
<h3>3. Use <code>program := fcase()</code> to edit all values</h3>
<p>In this approach, we use the data.table function
<code>fcase()</code>, an implementation of the SQL CASE WHEN statement.
The data.table function <code>%chin%</code> is like <code>%in%</code>,
but for character vectors.</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Recode all program values</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>study_program[, program <span class="sc">:</span><span class="er">=</span> <span class="fu">fcase</span>(</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%like%</span> <span class="st">&quot;^1408&quot;</span>, <span class="st">&quot;CE&quot;</span>, </span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%like%</span> <span class="st">&quot;^1410&quot;</span>, <span class="st">&quot;EE&quot;</span>, </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%like%</span> <span class="st">&quot;^1419&quot;</span>, <span class="st">&quot;ME&quot;</span>, </span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%chin%</span> <span class="fu">c</span>(<span class="st">&quot;142701&quot;</span>, <span class="st">&quot;143501&quot;</span>, <span class="st">&quot;143601&quot;</span>, <span class="st">&quot;143701&quot;</span>), <span class="st">&quot;ISE&quot;</span></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>)]</span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the result</span></span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>study_program[]</span></code></pre></div>
<pre><code>#&gt;       cip6                                               cip4name program
#&gt;     &lt;char&gt;                                                 &lt;char&gt;  &lt;char&gt;
#&gt;  1: 140801                                      Civil Engineering      CE
#&gt;  2: 140802                                      Civil Engineering      CE
#&gt;  3: 140803                                      Civil Engineering      CE
#&gt;  4: 140804                                      Civil Engineering      CE
#&gt;  5: 140805                                      Civil Engineering      CE
#&gt;  6: 140899                                      Civil Engineering      CE
#&gt;  7: 141001 Electrical, Electronics and Communications Engineering      EE
#&gt;  8: 141003 Electrical, Electronics and Communications Engineering      EE
#&gt;  9: 141004 Electrical, Electronics and Communications Engineering      EE
#&gt; 10: 141099 Electrical, Electronics and Communications Engineering      EE
#&gt; 11: 141901                                 Mechanical Engineering      ME
#&gt; 12: 142701                                    Systems Engineering     ISE
#&gt; 13: 143501                                 Industrial Engineering     ISE
#&gt; 14: 143601                              Manufacturing Engineering     ISE
#&gt; 15: 143701                                    Operations Research     ISE</code></pre>
<p>Having completed labeling the programs, we can remove the original
verbose <code>cip4nme</code> column.</p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Delete a column</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>study_program[, cip4name <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Examine the result</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>study_program[]</span></code></pre></div>
<pre><code>#&gt;       cip6 program
#&gt;     &lt;char&gt;  &lt;char&gt;
#&gt;  1: 140801      CE
#&gt;  2: 140802      CE
#&gt;  3: 140803      CE
#&gt;  4: 140804      CE
#&gt;  5: 140805      CE
#&gt;  6: 140899      CE
#&gt;  7: 141001      EE
#&gt;  8: 141003      EE
#&gt;  9: 141004      EE
#&gt; 10: 141099      EE
#&gt; 11: 141901      ME
#&gt; 12: 142701     ISE
#&gt; 13: 143501     ISE
#&gt; 14: 143601     ISE
#&gt; 15: 143701     ISE</code></pre>
</div>
<div id="exercises-1" class="section level3">
<h3>Exercises</h3>
<ol style="list-style-type: decimal">
<li>Obtain the 9 programs in the 2-digit program 54 History.</li>
<li>Add a <code>program</code> column with NA values.</li>
<li>Edit some of the values in the <code>program</code> column as
follows:
<ul>
<li>Rename both “General” and “Other” to “General History”</li>
<li>Shorten “History and Philosophy…” to “Sci/Tech History”</li>
<li>Shorten “American History …” to “US History”</li>
<li>Shorten “Public Applied …” to “Public/Applied History”</li>
<li>Others retain their 6-digit name</li>
</ul></li>
<li>Delete the <code>cip6name</code> column.</li>
</ol>
<p>Answer given below to check your work.</p>
<pre><code>#&gt;      cip6                program
#&gt;    &lt;char&gt;                 &lt;char&gt;
#&gt; 1: 540101        General History
#&gt; 2: 540102             US History
#&gt; 3: 540103       European History
#&gt; 4: 540104       Sci/Tech History
#&gt; 5: 540105 Public/Applied History
#&gt; 6: 540106          Asian History
#&gt; 7: 540107       Canadian History
#&gt; 8: 540108       Military History
#&gt; 9: 540199        General History</code></pre>
</div>
</div>
<div id="closing" class="section level2">
<h2>Closing</h2>
<p>We introduced the taxonomy of academic programs established by the US
Department of Education and its implementation in the midfieldr data set
<code>cip</code>.</p>
<p>We outlined several search strategies for identifying programs of
interest and methods for assigning custom program labels typically used
for grouping and summarizing SUR observations.</p>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<div id="refs" class="references csl-bib-body hanging-indent" line-spacing="2">
<div id="ref-NCES:2010" class="csl-entry">
NCES. (2010). <em><span class="nocase">IPEDS Classification of
Instructional Programs (CIP)</span></em>. <span>National Center for
Education Statistics</span>. <a href="https://nces.ed.gov/ipeds/cipcode/">https://nces.ed.gov/ipeds/cipcode/</a>
</div>
<div id="ref-NCES:2020" class="csl-entry">
NCES. (2020). <em><span class="nocase">Introduction to the
classification of instructional programs (CIP-2020)</span></em>.
<span>National Center for Education Statistics</span>; [Online; accessed
2021-06-04]. <a href="https://nces.ed.gov/ipeds/cipcode/Files/2020_CIP_Introduction.pdf">https://nces.ed.gov/ipeds/cipcode/Files/2020_CIP_Introduction.pdf</a>
</div>
</div>
</div>
<div id="appendix" class="section level2">
<h2>Appendix</h2>
<p>We conclude each vignette by collecting its code chunks in a single,
condensed script for the convenience of those who wish to copy it into
their own R file.</p>
<div class="sourceCode" id="cb40"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Packages</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfieldr&quot;</span>)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(<span class="st">&quot;data.table&quot;</span>))</span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing options for data.table</span></span>
<span id="cb40-6"><a href="#cb40-6" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(</span>
<span id="cb40-7"><a href="#cb40-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.nrows =</span> <span class="dv">55</span>,</span>
<span id="cb40-8"><a href="#cb40-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.topn =</span> <span class="dv">3</span>,</span>
<span id="cb40-9"><a href="#cb40-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.class =</span> <span class="cn">TRUE</span></span>
<span id="cb40-10"><a href="#cb40-10" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb40-11"><a href="#cb40-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-12"><a href="#cb40-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Introduction to cip</span></span>
<span id="cb40-13"><a href="#cb40-13" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(cip)</span>
<span id="cb40-14"><a href="#cb40-14" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">unique</span>(cip<span class="sc">$</span>cip2))</span>
<span id="cb40-15"><a href="#cb40-15" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(cip<span class="sc">$</span>cip4))</span>
<span id="cb40-16"><a href="#cb40-16" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(<span class="fu">unique</span>(cip<span class="sc">$</span>cip6))</span>
<span id="cb40-17"><a href="#cb40-17" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(cip[, cip2name], <span class="dv">10</span>)</span>
<span id="cb40-18"><a href="#cb40-18" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(cip[, cip4name], <span class="dv">10</span>)</span>
<span id="cb40-19"><a href="#cb40-19" aria-hidden="true" tabindex="-1"></a><span class="fu">sample</span>(cip[, cip6name], <span class="dv">10</span>)</span>
<span id="cb40-20"><a href="#cb40-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-21"><a href="#cb40-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Using a keyword search</span></span>
<span id="cb40-22"><a href="#cb40-22" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(<span class="at">dframe =</span> cip, <span class="at">keep_text =</span> <span class="st">&quot;engineering&quot;</span>)</span>
<span id="cb40-23"><a href="#cb40-23" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, </span>
<span id="cb40-24"><a href="#cb40-24" aria-hidden="true" tabindex="-1"></a>              <span class="st">&quot;engineering&quot;</span>, </span>
<span id="cb40-25"><a href="#cb40-25" aria-hidden="true" tabindex="-1"></a>              <span class="at">drop_text =</span> <span class="fu">c</span>(<span class="st">&quot;related&quot;</span>, <span class="st">&quot;technology&quot;</span>, <span class="st">&quot;technologies&quot;</span>), </span>
<span id="cb40-26"><a href="#cb40-26" aria-hidden="true" tabindex="-1"></a>              <span class="at">select =</span> <span class="fu">c</span>(<span class="st">&quot;cip6&quot;</span>, <span class="st">&quot;cip6name&quot;</span>))</span>
<span id="cb40-27"><a href="#cb40-27" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="st">&quot;civil&quot;</span>)</span>
<span id="cb40-28"><a href="#cb40-28" aria-hidden="true" tabindex="-1"></a>first_pass <span class="ot">&lt;-</span> <span class="fu">filter_search</span>(cip, <span class="st">&quot;civil&quot;</span>)</span>
<span id="cb40-29"><a href="#cb40-29" aria-hidden="true" tabindex="-1"></a>second_pass <span class="ot">&lt;-</span> <span class="fu">filter_search</span>(first_pass, <span class="st">&quot;engineering&quot;</span>)</span>
<span id="cb40-30"><a href="#cb40-30" aria-hidden="true" tabindex="-1"></a>third_pass <span class="ot">&lt;-</span> <span class="fu">filter_search</span>(second_pass, <span class="at">drop_text =</span> <span class="st">&quot;technology&quot;</span>)</span>
<span id="cb40-31"><a href="#cb40-31" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="st">&quot;civil engineering&quot;</span>, <span class="at">drop_text =</span> <span class="st">&quot;technology&quot;</span>)</span>
<span id="cb40-32"><a href="#cb40-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-33"><a href="#cb40-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Using a numerical code search</span></span>
<span id="cb40-34"><a href="#cb40-34" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="st">&quot;german&quot;</span>)</span>
<span id="cb40-35"><a href="#cb40-35" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="fu">c</span>(<span class="st">&quot;050125&quot;</span>, <span class="st">&quot;160501&quot;</span>))</span>
<span id="cb40-36"><a href="#cb40-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-37"><a href="#cb40-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Using a regular expression search</span></span>
<span id="cb40-38"><a href="#cb40-38" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="fu">c</span>(<span class="st">&quot;^1410&quot;</span>, <span class="st">&quot;^1419&quot;</span>))</span>
<span id="cb40-39"><a href="#cb40-39" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, <span class="st">&quot;^54&quot;</span>)</span>
<span id="cb40-40"><a href="#cb40-40" aria-hidden="true" tabindex="-1"></a>codes_we_want <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;^24&quot;</span>, <span class="st">&quot;^4102&quot;</span>, <span class="st">&quot;^450202&quot;</span>)</span>
<span id="cb40-41"><a href="#cb40-41" aria-hidden="true" tabindex="-1"></a><span class="fu">filter_search</span>(cip, codes_we_want)</span>
<span id="cb40-42"><a href="#cb40-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-43"><a href="#cb40-43" aria-hidden="true" tabindex="-1"></a><span class="co"># When search terms cannot be found</span></span>
<span id="cb40-44"><a href="#cb40-44" aria-hidden="true" tabindex="-1"></a><span class="co"># filter_search(cip, c(&quot;050125&quot;, &quot;111111&quot;, &quot;160501&quot;, &quot;Bogus&quot;, &quot;^55&quot;))</span></span>
<span id="cb40-45"><a href="#cb40-45" aria-hidden="true" tabindex="-1"></a><span class="co"># filter_search(cip, c(&quot;111111&quot;, &quot;Bogus&quot;, &quot;^55&quot;))</span></span>
<span id="cb40-46"><a href="#cb40-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-47"><a href="#cb40-47" aria-hidden="true" tabindex="-1"></a><span class="co"># CIP data from another source</span></span>
<span id="cb40-48"><a href="#cb40-48" aria-hidden="true" tabindex="-1"></a><span class="fu">unlist</span>(<span class="fu">lapply</span>(cip, <span class="at">FUN =</span> class))</span>
<span id="cb40-49"><a href="#cb40-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-50"><a href="#cb40-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Assigning program names</span></span>
<span id="cb40-51"><a href="#cb40-51" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">datatable.print.nrows =</span> <span class="dv">15</span>)</span>
<span id="cb40-52"><a href="#cb40-52" aria-hidden="true" tabindex="-1"></a>study_program <span class="ot">&lt;-</span> <span class="fu">filter_search</span>(cip, <span class="fu">c</span>(<span class="st">&quot;^1408&quot;</span>, <span class="st">&quot;^1410&quot;</span>, <span class="st">&quot;^1419&quot;</span>, <span class="st">&quot;^1427&quot;</span>, <span class="st">&quot;^1435&quot;</span>, <span class="st">&quot;^1436&quot;</span>, <span class="st">&quot;^1437&quot;</span>))</span>
<span id="cb40-53"><a href="#cb40-53" aria-hidden="true" tabindex="-1"></a>study_program <span class="ot">&lt;-</span> study_program[, .(cip6, cip4name)]</span>
<span id="cb40-54"><a href="#cb40-54" aria-hidden="true" tabindex="-1"></a>study_program[, program <span class="sc">:</span><span class="er">=</span> <span class="cn">NA_character_</span>]</span>
<span id="cb40-55"><a href="#cb40-55" aria-hidden="true" tabindex="-1"></a>study_program[cip4name <span class="sc">%ilike%</span> <span class="st">&quot;electrical&quot;</span>,  program <span class="sc">:</span><span class="er">=</span> <span class="st">&quot;EE&quot;</span>]</span>
<span id="cb40-56"><a href="#cb40-56" aria-hidden="true" tabindex="-1"></a>study_program[cip6 <span class="sc">%like%</span> <span class="st">&quot;^1408&quot;</span>,  program <span class="sc">:</span><span class="er">=</span> <span class="st">&quot;CE&quot;</span>]</span>
<span id="cb40-57"><a href="#cb40-57" aria-hidden="true" tabindex="-1"></a>study_program[, program <span class="sc">:</span><span class="er">=</span> <span class="fu">fcase</span>(</span>
<span id="cb40-58"><a href="#cb40-58" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%like%</span> <span class="st">&quot;^1408&quot;</span>, <span class="st">&quot;CE&quot;</span>, </span>
<span id="cb40-59"><a href="#cb40-59" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%like%</span> <span class="st">&quot;^1410&quot;</span>, <span class="st">&quot;EE&quot;</span>, </span>
<span id="cb40-60"><a href="#cb40-60" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%like%</span> <span class="st">&quot;^1419&quot;</span>, <span class="st">&quot;ME&quot;</span>, </span>
<span id="cb40-61"><a href="#cb40-61" aria-hidden="true" tabindex="-1"></a>    cip6 <span class="sc">%chin%</span> <span class="fu">c</span>(<span class="st">&quot;142701&quot;</span>, <span class="st">&quot;143501&quot;</span>, <span class="st">&quot;143601&quot;</span>, <span class="st">&quot;143701&quot;</span>), <span class="st">&quot;ISE&quot;</span></span>
<span id="cb40-62"><a href="#cb40-62" aria-hidden="true" tabindex="-1"></a>)]</span>
<span id="cb40-63"><a href="#cb40-63" aria-hidden="true" tabindex="-1"></a>study_program[, cip4name <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span></code></pre></div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
