<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />


<meta name="date" content="2022-06-29" />

<title>Completion status</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>



<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>



<style type="text/css">
/* for pandoc --citeproc since 2.11 */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>

<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">Completion status</h1>
<h4 class="date">2022-06-29</h4>



<p>After subsetting longitudinal Student Unit Records (SURs) for data
sufficiency, degree seeking, and programs, a typical next step is to
label the records with completion status—required for most metrics
because graduation is the most significant measure of both program
success and student success.</p>
<p>To be counted as a timely graduate, a student must satisfy the timely
completion criterion. Depending on the purpose of the study, completion
status can be used to filter observations or to group and summarize
observations.</p>
<div id="definitions" class="section level2">
<h2>Definitions</h2>
<dl>
<dt>program completion</dt>
<dd>
<p>Graduating from a baccalaureate program</p>
</dd>
<dt>timely completion criterion</dt>
<dd>
<p>Completing a program in no more than a specified span of years, in
many cases, within 6 years after admission, or possibly less for some
transfer students.</p>
</dd>
</dl>
</div>
<div id="method" class="section level2">
<h2>Method</h2>
<p>The method for labeling completion status is:</p>
<ul>
<li>Completion is TRUE if a degree is recorded in the
<code>degree</code> data table and FALSE otherwise.<br />
</li>
<li>Completion status is “timely” if the degree term is no later than
the timely term; “untimely” if later; and “NA” for non-completion.</li>
</ul>
</div>
<div id="population" class="section level2">
<h2>Population</h2>
<p>If you are writing your own script to follow along, we start with
these packages:</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfieldr&quot;</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfielddata&quot;</span>)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(<span class="st">&quot;data.table&quot;</span>))</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing options for data.table</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.nrows =</span> <span class="dv">55</span>,</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.topn =</span> <span class="dv">5</span>,</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.class =</span> <span class="cn">TRUE</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div>
<p><strong>Importing.</strong> Load the midfielddata data tables.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data sets from midfielddata</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(student, term, degree)</span></code></pre></div>
<p><strong>Filtering.</strong> The steps from previous vignettes (<a href="art-010-data-sufficiency.html">Data sufficiency</a> and <a href="art-020-degree-seeking.html">Degree seeking</a> are reproduced
here in condensed form to yield the IDs of all students in the practice
data satisfying data sufficiency and degree seeking.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for data sufficiency</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">copy</span>(term)</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_timely_term</span>(DT, term)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_data_sufficiency</span>(DT, term)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[data_sufficiency <span class="sc">==</span> <span class="st">&quot;include&quot;</span>]</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for degree seeking</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid)]</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">unique</span>(DT)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[student, .(mcid), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;               mcid
#&gt;             &lt;char&gt;
#&gt;     1: MID25783135
#&gt;     2: MID25783162
#&gt;     3: MID25783178
#&gt;     4: MID25783195
#&gt;     5: MID25783220
#&gt;    ---            
#&gt; 63948: MID26697574
#&gt; 63949: MID26697576
#&gt; 63950: MID26697599
#&gt; 63951: MID26697615
#&gt; 63952: MID26697623</code></pre>
<p>This data frame is adequate for demonstration purposes.</p>
</div>
<div id="add_completion_status" class="section level2">
<h2><code>add_completion_status()</code></h2>
<p>You can view the function help page by running,</p>
<pre><code>? add_completion_status()</code></pre>
<p>Its arguments are:</p>
<dl>
<dt><code>dframe</code></dt>
<dd>
<p>Data frame of student unit record (SUR) observations keyed by student
ID. Required variables are <code>mcid</code> and
<code>timely_term</code>.</p>
</dd>
<dt><code>midfield_degree</code></dt>
<dd>
<p>Data frame of SUR degree observations keyed by student ID. Default is
<code>degree</code>. Required variables are <code>mcid</code> and
<code>term_degree</code>.</p>
</dd>
</dl>
<p>The function adds three columns to the SUR data frame: the
<code>completion_status</code> result plus two supporting variables:</p>
<dl>
<dt><code>term_degree</code></dt>
<dd>
<p>Character. Term in which a program is completed. Encoded YYYYT.</p>
</dd>
<dt><code>completion</code></dt>
<dd>
<p>Logical. TRUE denotes program completion; FALSE denotes
non-completion.</p>
</dd>
</dl>
<p>The possible values for completion status are:</p>
<ul>
<li>“timely”, program completion no later than
<code>timely_term</code></li>
<li>“untimely”, program completion after <code>timely_term</code></li>
<li>NA, non-completion.</li>
</ul>
<p><strong>Add variables.</strong> For demonstrating
<code>add_completion_status()</code>, our working data frame must have
columns for ID and the timely completion term. We use
<code>add_timely_term()</code> again, though alternatively we could have
retained the <code>timely_term</code> variable in earlier code
chunks.</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Add completion status</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_timely_term</span>(DT, term)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(DT, degree)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop unnecessary columns</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>DT[, <span class="fu">c</span>(<span class="st">&quot;term_i&quot;</span>, <span class="st">&quot;level_i&quot;</span>, <span class="st">&quot;adj_span&quot;</span>) <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;               mcid timely_term term_degree completion completion_status
#&gt;             &lt;char&gt;      &lt;char&gt;      &lt;char&gt;     &lt;lgcl&gt;            &lt;char&gt;
#&gt;     1: MID25783135       19963        &lt;NA&gt;      FALSE              &lt;NA&gt;
#&gt;     2: MID25783162       19973       19963       TRUE            timely
#&gt;     3: MID25783178       20003       20001       TRUE            timely
#&gt;     4: MID25783195       19983       19966       TRUE            timely
#&gt;     5: MID25783220       20023        &lt;NA&gt;      FALSE              &lt;NA&gt;
#&gt;    ---                                                                 
#&gt; 63948: MID26697574       20113       20113       TRUE            timely
#&gt; 63949: MID26697576       20153       20134       TRUE            timely
#&gt; 63950: MID26697599       20153       20143       TRUE            timely
#&gt; 63951: MID26697615       20153        &lt;NA&gt;      FALSE              &lt;NA&gt;
#&gt; 63952: MID26697623       20153       20153       TRUE            timely</code></pre>
<p><strong>Closer look.</strong> Let’s examine three specific
observations to illustrate the sense of the results.</p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Student F</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>DT[mcid <span class="sc">==</span> <span class="st">&quot;MID25783162&quot;</span>]</span></code></pre></div>
<pre><code>#&gt;           mcid timely_term term_degree completion completion_status
#&gt;         &lt;char&gt;      &lt;char&gt;      &lt;char&gt;     &lt;lgcl&gt;            &lt;char&gt;
#&gt; 1: MID25783162       19973       19963       TRUE            timely</code></pre>
<p>The student has a degree term, Spring 1997 (encoded
<code>19963</code>), so completion is TRUE. Their degree term does not
exceed their timely completion term, Spring 1998 (encoded
<code>19973</code>), so their completion status is “timely”.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Student G</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>DT[mcid <span class="sc">==</span> <span class="st">&quot;MID26696871&quot;</span>]</span></code></pre></div>
<pre><code>#&gt;           mcid timely_term term_degree completion completion_status
#&gt;         &lt;char&gt;      &lt;char&gt;      &lt;char&gt;     &lt;lgcl&gt;            &lt;char&gt;
#&gt; 1: MID26696871       20153       20163       TRUE          untimely</code></pre>
<p>This student too has a degree term, Spring 2017 (encoded
<code>20163</code>), so completion is TRUE. Their degree term exceeds
their timely completion term, Spring 2016 (encoded <code>20153</code>),
so their completion status is “untimely”.</p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Student H</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>DT[mcid <span class="sc">==</span> <span class="st">&quot;MID26697615&quot;</span>]</span></code></pre></div>
<pre><code>#&gt;           mcid timely_term term_degree completion completion_status
#&gt;         &lt;char&gt;      &lt;char&gt;      &lt;char&gt;     &lt;lgcl&gt;            &lt;char&gt;
#&gt; 1: MID26697615       20153        &lt;NA&gt;      FALSE              &lt;NA&gt;</code></pre>
<p>The student’s degree term is NA indicating they did not graduate.
Completion is therefore FALSE and completion status is also NA.</p>
<p><strong>Usage.</strong> The following implementations yield identical
results,</p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Required arguments in order and explicitly named</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(<span class="at">dframe =</span> DT, <span class="at">midfield_degree =</span> degree)</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Required arguments in order, but not named</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(DT, degree)</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Using the implicit default for the midfield_term argument</span></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(DT)</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Equality test between the data tables</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(x, y)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(x, z)</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; [1] TRUE</span></span></code></pre></div>
<p>In the vignettes, I will typically write required arguments without
names to remind us which midfielddata table is being used, e.g.,</p>
<pre><code>add_timely_term(DT, term)</code></pre>
<p>Your degree data set can be named something other than
<code>degree</code>. For example, if we were working with the “toy”
(exercise) data sets bundled with midfieldr, we would write something
like this,</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Using degree data named something else</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>toy_DT <span class="ot">&lt;-</span> toy_student[, .(mcid)]</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>toy_DT <span class="ot">&lt;-</span> <span class="fu">add_timely_term</span>(toy_DT, toy_term)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>toy_DT <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(toy_DT, toy_degree)</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>toy_DT[, <span class="fu">c</span>(<span class="st">&quot;term_i&quot;</span>, <span class="st">&quot;level_i&quot;</span>, <span class="st">&quot;adj_span&quot;</span>) <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>toy_DT[]</span></code></pre></div>
<pre><code>#&gt;            mcid timely_term term_degree completion completion_status
#&gt;          &lt;char&gt;      &lt;char&gt;      &lt;char&gt;     &lt;lgcl&gt;            &lt;char&gt;
#&gt;  1: MID25784187       19943       19946       TRUE          untimely
#&gt;  2: MID25784974       19931        &lt;NA&gt;      FALSE              &lt;NA&gt;
#&gt;  3: MID25816209       19923        &lt;NA&gt;      FALSE              &lt;NA&gt;
#&gt;  4: MID25819358       19993       19963       TRUE            timely
#&gt;  5: MID25828870       19933       19923       TRUE            timely
#&gt; ---                                                                 
#&gt; 95: MID26622664       20113       20093       TRUE            timely
#&gt; 96: MID26624815       20113       20073       TRUE            timely
#&gt; 97: MID26691066       20161       20141       TRUE            timely
#&gt; 98: MID26692025       20153       20141       TRUE            timely
#&gt; 99: MID26692254       20191       20143       TRUE            timely</code></pre>
<p><strong>Caution! Silent overwriting!</strong> In this case, existing
columns with the same name as one of the added columns are deleted and
replaced except.</p>
<p>Using the toy data to illustrate, I’ll drop the columns added by
timely term except <code>completion</code></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Drop two columns</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>toy_DT <span class="ot">&lt;-</span> toy_DT[, <span class="fu">c</span>(<span class="st">&quot;term_degree&quot;</span>, <span class="st">&quot;completion_status&quot;</span>) <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>toy_DT[]</span></code></pre></div>
<pre><code>#&gt;            mcid timely_term completion
#&gt;          &lt;char&gt;      &lt;char&gt;     &lt;lgcl&gt;
#&gt;  1: MID25784187       19943       TRUE
#&gt;  2: MID25784974       19931      FALSE
#&gt;  3: MID25816209       19923      FALSE
#&gt;  4: MID25819358       19993       TRUE
#&gt;  5: MID25828870       19933       TRUE
#&gt; ---                                   
#&gt; 95: MID26622664       20113       TRUE
#&gt; 96: MID26624815       20113       TRUE
#&gt; 97: MID26691066       20161       TRUE
#&gt; 98: MID26692025       20153       TRUE
#&gt; 99: MID26692254       20191       TRUE</code></pre>
<p>Reapplying the function, the <code>completion</code> column is
silently deleted and replaced.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Reapply the function</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>toy_DT <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(toy_DT, toy_degree)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>toy_DT[]</span></code></pre></div>
<pre><code>#&gt;            mcid timely_term term_degree completion completion_status
#&gt;          &lt;char&gt;      &lt;char&gt;      &lt;char&gt;     &lt;lgcl&gt;            &lt;char&gt;
#&gt;  1: MID25784187       19943       19946       TRUE          untimely
#&gt;  2: MID25784974       19931        &lt;NA&gt;      FALSE              &lt;NA&gt;
#&gt;  3: MID25816209       19923        &lt;NA&gt;      FALSE              &lt;NA&gt;
#&gt;  4: MID25819358       19993       19963       TRUE            timely
#&gt;  5: MID25828870       19933       19923       TRUE            timely
#&gt; ---                                                                 
#&gt; 95: MID26622664       20113       20093       TRUE            timely
#&gt; 96: MID26624815       20113       20073       TRUE            timely
#&gt; 97: MID26691066       20161       20141       TRUE            timely
#&gt; 98: MID26692025       20153       20141       TRUE            timely
#&gt; 99: MID26692254       20191       20143       TRUE            timely</code></pre>
</div>
<div id="completion-summaries" class="section level2">
<h2>Completion summaries</h2>
<p>If our research question requires us to count the frequency of
observations by completion status, we can retain all observations and
group and summarize.</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>DT[, .N, by <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;completion_status&quot;</span>)]</span></code></pre></div>
<pre><code>#&gt;    completion_status     N
#&gt;               &lt;char&gt; &lt;int&gt;
#&gt; 1:              &lt;NA&gt; 23173
#&gt; 2:            timely 37047
#&gt; 3:          untimely  3732</code></pre>
<p>Or we might add a second grouping variable.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> DT[student, .(mcid, sex, completion_status), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> x[, .N, by <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;sex&quot;</span>, <span class="st">&quot;completion_status&quot;</span>)]</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setkeyv</span>(x, <span class="fu">c</span>(<span class="st">&quot;completion_status&quot;</span>, <span class="st">&quot;sex&quot;</span>))</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a>x[]</span></code></pre></div>
<pre><code>#&gt;       sex completion_status     N
#&gt;    &lt;char&gt;            &lt;char&gt; &lt;int&gt;
#&gt; 1: Female              &lt;NA&gt; 10566
#&gt; 2:   Male              &lt;NA&gt; 12607
#&gt; 3: Female            timely 18842
#&gt; 4:   Male            timely 18205
#&gt; 5: Female          untimely  1437
#&gt; 6:   Male          untimely  2295</code></pre>
</div>
<div id="completion-filter" class="section level2">
<h2>Completion filter</h2>
<p>If our research question requires us to extract timely graduates
only, we can use completion status as a filter.</p>
<div class="sourceCode" id="cb26"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> DT[completion_status <span class="sc">==</span> <span class="st">&quot;timely&quot;</span>]</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a>x[]</span></code></pre></div>
<pre><code>#&gt;               mcid timely_term term_degree completion completion_status
#&gt;             &lt;char&gt;      &lt;char&gt;      &lt;char&gt;     &lt;lgcl&gt;            &lt;char&gt;
#&gt;     1: MID25783162       19973       19963       TRUE            timely
#&gt;     2: MID25783178       20003       20001       TRUE            timely
#&gt;     3: MID25783195       19983       19966       TRUE            timely
#&gt;     4: MID25783259       19941       19933       TRUE            timely
#&gt;     5: MID25783324       19973       19963       TRUE            timely
#&gt;    ---                                                                 
#&gt; 37043: MID26697553       20153       20133       TRUE            timely
#&gt; 37044: MID26697574       20113       20113       TRUE            timely
#&gt; 37045: MID26697576       20153       20134       TRUE            timely
#&gt; 37046: MID26697599       20153       20143       TRUE            timely
#&gt; 37047: MID26697623       20153       20153       TRUE            timely</code></pre>
</div>
<div id="completion-programs" class="section level2">
<h2>Completion programs</h2>
<p>If our research question require the programs that graduates
completed, we can use an inner join with <code>degree</code> and retain
selected columns.</p>
<div class="sourceCode" id="cb28"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[completion_status <span class="sc">==</span> <span class="st">&quot;timely&quot;</span>]</span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[degree, .(mcid, cip6), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;               mcid   cip6
#&gt;             &lt;char&gt; &lt;char&gt;
#&gt;     1: MID25783162 521401
#&gt;     2: MID25783178 143501
#&gt;     3: MID25783195 521401
#&gt;     4: MID25783259 011103
#&gt;     5: MID25783324 260202
#&gt;    ---                   
#&gt; 37043: MID26697553 451001
#&gt; 37044: MID26697574 300000
#&gt; 37045: MID26697576 521401
#&gt; 37046: MID26697599 110401
#&gt; 37047: MID26697623 520301</code></pre>
<p>If we have a particular set of programs such as those developed in
the case study vignettes, we can join our program names with another
inner join. First, the case study program names and codes are loaded
with midfieldr. View the data help page by running</p>
<pre><code>? study_program_cips</code></pre>
<p>The case study program CIP codes and names are:</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>study_program_cips[]</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;       cip6 program</span></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;     &lt;char&gt;  &lt;char&gt;</span></span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  1: 140801      CE</span></span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  2: 140802      CE</span></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  3: 140803      CE</span></span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  4: 140804      CE</span></span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  5: 140805      CE</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  6: 140899      CE</span></span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  7: 141001      EE</span></span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  8: 141003      EE</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;  9: 141004      EE</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 10: 141099      EE</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 11: 141901      ME</span></span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 12: 142701     ISE</span></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 13: 143501     ISE</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 14: 143601     ISE</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; 15: 143701     ISE</span></span></code></pre></div>
<p>Inner-join the program names and retain only those graduating in the
selected programs.</p>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[study_program_cips, .(mcid, program), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;cip6&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>DT[]</span></code></pre></div>
<pre><code>#&gt;              mcid program
#&gt;            &lt;char&gt;  &lt;char&gt;
#&gt;    1: MID25783441      CE
#&gt;    2: MID25784334      CE
#&gt;    3: MID25784418      CE
#&gt;    4: MID25784489      CE
#&gt;    5: MID25784709      CE
#&gt;   ---                    
#&gt; 3618: MID26689274     ISE
#&gt; 3619: MID26692926     ISE
#&gt; 3620: MID26695626     ISE
#&gt; 3621: MID26696116     ISE
#&gt; 3622: MID26696429     ISE</code></pre>
<p>Again, a quick summary of program timely graduates.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>DT[, .N, by <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;program&quot;</span>)]</span></code></pre></div>
<pre><code>#&gt;    program     N
#&gt;     &lt;char&gt; &lt;int&gt;
#&gt; 1:      CE   836
#&gt; 2:      EE   914
#&gt; 3:      ME  1289
#&gt; 4:     ISE   583</code></pre>
</div>
<div id="closing" class="section level2">
<h2>Closing</h2>
<p>Starting with the student, term, and degree data tables, we filtered
the data for data sufficiency and degree seeking. We explored the
features of the <code>add_completion_status()</code> function and
examined how the result might be used.</p>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<div id="refs">

</div>
</div>
<div id="appendix" class="section level2">
<h2>Appendix</h2>
<p>We conclude each vignette by collecting its code chunks in a single,
condensed script for the convenience of those who wish to copy it into
their own R file.</p>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Packages</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfieldr&quot;</span>)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">&quot;midfielddata&quot;</span>)</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a><span class="fu">suppressPackageStartupMessages</span>(<span class="fu">library</span>(<span class="st">&quot;data.table&quot;</span>))</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Printing options for data.table</span></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(</span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.nrows =</span> <span class="dv">55</span>,</span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.topn =</span> <span class="dv">5</span>,</span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">datatable.print.class =</span> <span class="cn">TRUE</span></span>
<span id="cb36-11"><a href="#cb36-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb36-12"><a href="#cb36-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-13"><a href="#cb36-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Load data sets from midfielddata</span></span>
<span id="cb36-14"><a href="#cb36-14" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(student, term, degree)</span>
<span id="cb36-15"><a href="#cb36-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-16"><a href="#cb36-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for data sufficiency</span></span>
<span id="cb36-17"><a href="#cb36-17" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">copy</span>(term)</span>
<span id="cb36-18"><a href="#cb36-18" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_timely_term</span>(DT, term)</span>
<span id="cb36-19"><a href="#cb36-19" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_data_sufficiency</span>(DT, term)</span>
<span id="cb36-20"><a href="#cb36-20" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[data_sufficiency <span class="sc">==</span> <span class="st">&quot;include&quot;</span>]</span>
<span id="cb36-21"><a href="#cb36-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-22"><a href="#cb36-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Filter for degree seeking</span></span>
<span id="cb36-23"><a href="#cb36-23" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[, .(mcid)]</span>
<span id="cb36-24"><a href="#cb36-24" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">unique</span>(DT)</span>
<span id="cb36-25"><a href="#cb36-25" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[student, .(mcid), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb36-26"><a href="#cb36-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-27"><a href="#cb36-27" aria-hidden="true" tabindex="-1"></a><span class="co"># Add completion status</span></span>
<span id="cb36-28"><a href="#cb36-28" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_timely_term</span>(DT, term)</span>
<span id="cb36-29"><a href="#cb36-29" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(DT, degree)</span>
<span id="cb36-30"><a href="#cb36-30" aria-hidden="true" tabindex="-1"></a>DT[, <span class="fu">c</span>(<span class="st">&quot;term_i&quot;</span>, <span class="st">&quot;level_i&quot;</span>, <span class="st">&quot;adj_span&quot;</span>) <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb36-31"><a href="#cb36-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-32"><a href="#cb36-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Closer look</span></span>
<span id="cb36-33"><a href="#cb36-33" aria-hidden="true" tabindex="-1"></a>DT[mcid <span class="sc">==</span> <span class="st">&quot;MID25783162&quot;</span>]</span>
<span id="cb36-34"><a href="#cb36-34" aria-hidden="true" tabindex="-1"></a>DT[mcid <span class="sc">==</span> <span class="st">&quot;MID26696871&quot;</span>]</span>
<span id="cb36-35"><a href="#cb36-35" aria-hidden="true" tabindex="-1"></a>DT[mcid <span class="sc">==</span> <span class="st">&quot;MID26697615&quot;</span>]</span>
<span id="cb36-36"><a href="#cb36-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-37"><a href="#cb36-37" aria-hidden="true" tabindex="-1"></a><span class="co"># Equivalent statements</span></span>
<span id="cb36-38"><a href="#cb36-38" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(<span class="at">dframe =</span> DT, <span class="at">midfield_degree =</span> degree)</span>
<span id="cb36-39"><a href="#cb36-39" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(DT, degree)</span>
<span id="cb36-40"><a href="#cb36-40" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(DT)</span>
<span id="cb36-41"><a href="#cb36-41" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(x, y)</span>
<span id="cb36-42"><a href="#cb36-42" aria-hidden="true" tabindex="-1"></a><span class="fu">all.equal</span>(x, z)</span>
<span id="cb36-43"><a href="#cb36-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-44"><a href="#cb36-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Using degree data named something else</span></span>
<span id="cb36-45"><a href="#cb36-45" aria-hidden="true" tabindex="-1"></a>toy_DT <span class="ot">&lt;-</span> toy_student[, .(mcid)]</span>
<span id="cb36-46"><a href="#cb36-46" aria-hidden="true" tabindex="-1"></a>toy_DT <span class="ot">&lt;-</span> <span class="fu">add_timely_term</span>(toy_DT, toy_term)</span>
<span id="cb36-47"><a href="#cb36-47" aria-hidden="true" tabindex="-1"></a>toy_DT <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(toy_DT, toy_degree)</span>
<span id="cb36-48"><a href="#cb36-48" aria-hidden="true" tabindex="-1"></a>toy_DT[, <span class="fu">c</span>(<span class="st">&quot;term_i&quot;</span>, <span class="st">&quot;level_i&quot;</span>, <span class="st">&quot;adj_span&quot;</span>) <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb36-49"><a href="#cb36-49" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-50"><a href="#cb36-50" aria-hidden="true" tabindex="-1"></a><span class="co"># Caution. Overwriting.</span></span>
<span id="cb36-51"><a href="#cb36-51" aria-hidden="true" tabindex="-1"></a>toy_DT <span class="ot">&lt;-</span> toy_DT[, <span class="fu">c</span>(<span class="st">&quot;term_degree&quot;</span>, <span class="st">&quot;completion_status&quot;</span>) <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]</span>
<span id="cb36-52"><a href="#cb36-52" aria-hidden="true" tabindex="-1"></a>toy_DT <span class="ot">&lt;-</span> <span class="fu">add_completion_status</span>(toy_DT, toy_degree)</span>
<span id="cb36-53"><a href="#cb36-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-54"><a href="#cb36-54" aria-hidden="true" tabindex="-1"></a><span class="co"># Completion summaries</span></span>
<span id="cb36-55"><a href="#cb36-55" aria-hidden="true" tabindex="-1"></a>DT[, .N, by <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;completion_status&quot;</span>)]</span>
<span id="cb36-56"><a href="#cb36-56" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> DT[student, .(mcid, sex, completion_status), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb36-57"><a href="#cb36-57" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> x[, .N, by <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;sex&quot;</span>, <span class="st">&quot;completion_status&quot;</span>)]</span>
<span id="cb36-58"><a href="#cb36-58" aria-hidden="true" tabindex="-1"></a><span class="fu">setkeyv</span>(x, <span class="fu">c</span>(<span class="st">&quot;completion_status&quot;</span>, <span class="st">&quot;sex&quot;</span>))</span>
<span id="cb36-59"><a href="#cb36-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-60"><a href="#cb36-60" aria-hidden="true" tabindex="-1"></a><span class="co"># Completion filter</span></span>
<span id="cb36-61"><a href="#cb36-61" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> DT[completion_status <span class="sc">==</span> <span class="st">&quot;timely&quot;</span>]</span>
<span id="cb36-62"><a href="#cb36-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-63"><a href="#cb36-63" aria-hidden="true" tabindex="-1"></a><span class="co"># Completion programs</span></span>
<span id="cb36-64"><a href="#cb36-64" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[completion_status <span class="sc">==</span> <span class="st">&quot;timely&quot;</span>]</span>
<span id="cb36-65"><a href="#cb36-65" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[degree, .(mcid, cip6), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;mcid&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb36-66"><a href="#cb36-66" aria-hidden="true" tabindex="-1"></a>DT <span class="ot">&lt;-</span> DT[study_program_cips, .(mcid, program), on <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;cip6&quot;</span>), nomatch <span class="ot">=</span> <span class="cn">NULL</span>]</span>
<span id="cb36-67"><a href="#cb36-67" aria-hidden="true" tabindex="-1"></a>DT[, .N, by <span class="ot">=</span> <span class="fu">c</span>(<span class="st">&quot;program&quot;</span>)]</span></code></pre></div>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
