---
title: "Audience"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Audience}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
bibliography: ../inst/REFERENCES.bib
---

```{r setup, echo = FALSE, message = FALSE, purl = FALSE}
knitr::opts_knit$set(root.dir = "../")
knitr::opts_chunk$set(
  echo = FALSE, # varies from one Rmd to another
  message = TRUE,
  warning = TRUE,
  collapse = TRUE,
  comment = "#>",
  error = TRUE,
  purl = FALSE,
  fig.width = 6,
  fig.asp = 1 / 1.6,
  out.width = "70%",
  fig.align = "center",
  fig.path = "../man/figures/about-"
)
```


## Research in student persistence

Analytical tools for research in student pathways are generally scarce. midfieldr provides an entry to this type of intersectional research for anyone with basic proficiency in R and familiarity with packages from the tidyverse. 

The goal of the package is to share our data, methods, and metrics for intersectional research in student persistence. We have two audiences in mind. 

1. Anyone interested in exploring new data. The packages provide registrar's data for approximately 98,000 students over 25 years with 729,000 observations of academic term variables and 3.5 M observations of academic course variables.

2. Anyone interested in longitudinal, intersectional research of undergraduate student pathways including data scientists responsible for measuring and reporting metrics in student persistence for academic institutions. 

## Novice R users 

We have tried to develop the vignettes with enough detail for an R novice to follow, noting the packages and functions we are using.  

For users just starting with R, we suggest the following links for getting started with R and RStudio. 

- [Installing R and RStudio](https://github.com/DSR-RHIT/install-R-and-RStudio), Richard Layton, Rose-Hulman Institute of Technology  
- [All the R things](http://stat545.com/topics.html), Jenny Bryan, University of British Columbia   
- [R tutorials](http://kbroman.org/pages/tutorials.html), Karl Broman, University of Wisconsin Madison 



