---
title: "Data"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
bibliography: ../inst/REFERENCES.bib
---

```{r setup, echo = FALSE, message = FALSE}
knitr::opts_knit$set(root.dir = "../")
knitr::opts_chunk$set(
  echo = TRUE, # varies from one Rmd to another
  message = FALSE,
  warning = FALSE,
  collapse = TRUE,
  comment = "#>",
  error = TRUE,
  purl = FALSE,
  fig.width = 6,
  fig.asp = 1 / 1.6,
  out.width = "70%",
  fig.align = "center",
  fig.path = "../man/figures/data-"
)
knitr::knit_hooks$set(inline = function(x) {
  if (!is.numeric(x)) {
    x
  } else if (x >= 10000) {
    prettyNum(round(x, 2), big.mark = ",")
  } else {
    prettyNum(round(x, 2))
  }
})
options(tibble.print_min = 8L, tibble.print_max = 8L)
```

The midfieldr package includes Classification of Instructional Programs (CIP) data from the US Department of Education [@cip2010].

- `cip` data frame
- `cip_series` 

The midfielddata package provides the stratified sample of student record data from the MIDFIELD database. 

- `midfieldstudents` A data frame with 97,640 observations and 15 demographic variables, occupying 19 Mb of memory. Each observation is a unique student.  
- `midfieldcourses` A data frame with 3.5 M observations and 12 academic course variables, occupying 348 Mb of memory (the largest of the midfielddata datasets). Each observation is one course in one term for one student. 
- `midfieldterms` A data frame with 729,014 observations and 13 academic term variables, occupying 82 Mb of memory. Each observation is one term for one student.  
- `midfielddegrees` A data frame with 97,640 observations and 5 graduation variables, occupying 10 Mb of memory. Each observation is a unique student.

The process of designing, compiling, maintaining, protecting, and sharing the MIDFIELD data is described in [@aee2016].

## Installing the packages

midfieldr is not currently available from CRAN. The development version can be installed from GitHub with:

```r
# midfieldr package
devtools::install_github("MIDFIELDR/midfieldr")

# help pages for data 
library(midfieldr)
?cip
?cip_series
```

midfielddata is not currently available from CRAN. The development version can be installed from GitHub with:

```r
# midfielddata package
devtools::install_github("MIDFIELDR/midfielddata")

# help pages for data
library(midfielddata)
?midfieldstudents
?midfieldcourses
?midfieldterms
?midfielddegrees
```


## References
