---
title: "Case study part 1: Goals"
format:
  gfm:
    html-table-processing: none
bibliography: ../../inst/REFERENCES.bib
link-citations: true
---

```{r setup}
#| include: false

# for any figures generated in the article
knitr::opts_chunk$set(fig.path = "figures/art-001-")

# for any "child" arguments in r-code-chunks
library("rprojroot")
path_to_rmd <- find_root_file("man", "rmd", criterion = has_file("DESCRIPTION"))
```

```{r child = paste0(path_to_rmd, "/common-setup.Rmd")}
```

Part 1 of a case study in three parts, illustrating how we work with longitudinal student-level records.  

1. *Goals.* &nbsp; Introducing the study.   

2. *Data.* &nbsp; Transforming the data to yield the observations of interest.

3. *Results.* &nbsp; Summary statistics, metric, chart, and table.  






## Definitions

```{r child = paste0(path_to_rmd, "/define-student-level-data.Rmd")}
```

```{r child = paste0(path_to_rmd, "/define-stickiness.Rmd")}
```




: $$
  \small S = \frac{N_g}{N_e} = \frac{\mathrm{number\ of\ graduates\ of\ a\ program}}{\mathrm{number\ ever\ enrolled\ in\ the\ program}}
  $$

: Stickiness is a more-inclusive alternative to graduation rate as a measure of a program's success in attracting, keeping, and graduating their undergraduates. Stickiness includes many students excluded by graduation rate such as part-time students, transfers, students admitted in any term, and migrators [@Ohland+Orr+others:2012]. 

 




## Goals

Task

: Compute and compare the stickiness of Civil, Electrical, Industrial, and Mechanical Engineering programs with students grouped by race/ethnicity and sex. 

Purpose

: The case study illustrates how we work with student-level data. Starting with the curated data and concluding with a chart of the metric, we focus throughout on our process and the underlying rationale. 

Constraint

: While we provide all the necessary code, we limit our discussion of the code (functions, arguments, syntax, etc.) to meet the constraint of providing a brief, yet complete, case study. Such discussions are left to later articles. One can always use the R help system to read more about a data set or function.








***

[&#9665; Introduction to midfieldr](art-000-getting-started.html) &nbsp; <a href="#top">&#9650; top of page</a> &nbsp;[Case study data &#9655;](art-002-case-data.html) 

***



```{r child = paste0(path_to_rmd, "/common-closing.Rmd")}
```
