---
title: "Notes on syntax"
format:
  gfm:
    html-table-processing: none
bibliography: ../../inst/REFERENCES.bib
link-citations: true
---
  
```{r setup}
#| include: false

# for any figures generated in the article
knitr::opts_chunk$set(fig.path = "figures/art-001-")

# for any "child" arguments in r-code-chunks
library("rprojroot")
path_to_rmd <- find_root_file("man", "rmd", criterion = has_file("DESCRIPTION"))
```
  
```{r child = paste0(path_to_rmd, "/common-setup.Rmd")}
```



```{r}
library("midfieldr")
library("data.table")
library("tibble")
```
 
*On printing a data frame:* &nbsp; Set the following data frame printing options to print *all columns* with the total number of rows displayed set by `max_n_rows`.

```{r}
# set max number of rows to display
max_n_rows <- 6

# data.table options
half_max <- round(max_n_rows / 2, 0)
options(
  datatable.print.nrows = max_n_rows,
  datatable.print.topn = half_max
)

# dplyr/tibble options
options(
  pillar.width = Inf,
  pillar.print_max = max_n_rows,
  pillar.print_min = max_n_rows
)
```

For example

```{r}
# example data frame
x <- copy(toy_student)

# data.table syntax
x

# tibble syntax
library(tibble)
as_tibble(x)

# base R syntax
x <- as.data.frame(x)
head(x, n = max_n_rows)

# alternative base R syntax
head(x, n = half_max)

tail(x, n = half_max)
```

