<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Feasible completion • midfieldr</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/spacelab/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Feasible completion">
<meta property="og:description" content="midfieldr">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">midfieldr</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.0.0.9008</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/get_started.html">Get started</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Vignettes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/data_basics.html">Data basics</a>
    </li>
    <li>
      <a href="../articles/multiway_graphs.html">Multiway graphs and tables</a>
    </li>
    <li>
      <a href="../articles/identify_programs.html">Identify programs</a>
    </li>
    <li>
      <a href="../articles/handle_fye.html">Handle FYE programs</a>
    </li>
    <li>
      <a href="../articles/feasible_completion.html">Feasible completion</a>
    </li>
    <li>
      <a href="../articles/timely-completion.html">Timely completion</a>
    </li>
    <li>
      <a href="../articles/graduation_rate.html">Graduation rate</a>
    </li>
    <li>
      <a href="../articles/stickiness_metric.html">Stickiness metric</a>
    </li>
  </ul>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="../articles/pages/get_session.html">Session info</a>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
<li>
  <a href="../articles/pages/about_midfield.html">About</a>
</li>
<li>
  <a href="https://github.com/MIDFIELDR/midfieldr">
    <span class="fas fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="feasible_completion_files/header-attrs-2.7/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Feasible completion</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/MIDFIELDR/midfieldr/blob/master/vignettes/feasible_completion.Rmd"><code>vignettes/feasible_completion.Rmd</code></a></small>
      <div class="hidden name"><code>feasible_completion.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>Persistence metrics often include a criterion that students complete their programs within <span class="math inline">\(x\)</span> years (typically 6 years, based on 150% of the “normal” time to completion). See, for example, <span class="citation">(<a href="#ref-IPEDS:2020" role="doc-biblioref">NCES, 2020</a>)</span>.</p>
<p>In longitudinal research, this completion criterion requires special care. For student records near the upper limit of an institution’s data range, a student’s completion status can be ambiguous. Consider a case in which:</p>
<ul>
<li>a student matriculates in 2012 and graduates in 2017</li>
<li>their institution’s data range ends in 2016</li>
</ul>
<p>The student satisfies the completion criterion, but their recorded degree status is NA because their degree term exceeds the data range.</p>
<p>Without special care, such students would add to the count of non-graduates, adversely and unfairly affecting the value of a persistence metric. Therefore, students with a degree status of NA are excluded from the analysis if completing their program is not feasible given the range of data available.</p>
<p>Feasible completion terminology is illustrated in the figure. Definitions are given below.</p>
<p><br><img src="../man/figures/vignette-feasible-completion-fig1-1.png" width="70%" style="display: block; margin: auto;"><br></p>
<dl>
<dt>data range</dt>
<dd>The range of terms for which student-record data are available, from the “first record” term to the “data limit” term. Varies by institution.
</dd>
<dt>completion feasibility</dt>
<dd>A student may complete their program within the data limit.
</dd>
<dt>matriculation limit</dt>
<dd>The last term a student can matriculate and feasibly complete their program. Defined as <span class="math inline">\(x\)</span> years (typically 6 years) before the data limit. Can be advanced by transfer credit hours.
</dd>
</dl>
<div id="this-vignette-uses" class="section level3">
<h3 class="hasAnchor">
<a href="#this-vignette-uses" class="anchor"></a>This vignette uses</h3>
<p>midfieldr functions</p>
<ul>
<li><code><a href="../reference/subset_feasible.html">subset_feasible()</a></code></li>
</ul>
<p>packages</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># packages used</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/MIDFIELDR/midfieldr">midfieldr</a></span><span class="op">)</span>

<span class="co"># print max 20 rows, otherwise 10 rows each head/tail</span>
<span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span>datatable.print.nrows <span class="op">=</span> <span class="fl">20</span>, datatable.print.topn <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></code></pre></div>
</div>
</div>
<div id="how-to-use-subset_feasible" class="section level2">
<h2 class="hasAnchor">
<a href="#how-to-use-subset_feasible" class="anchor"></a>How to use <code>subset_feasible()</code>
</h2>
<p>The first argument, <code>id</code>, is required. The remaining arguments all have default settings. The last three arguments accommodate using data sets other than those from midfielddata. Arguments after the ellipsis (…) must be named if used.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="../reference/subset_feasible.html">subset_feasible</a></span><span class="op">(</span><span class="va">id</span>,
                <span class="va">...</span>,
                <span class="va">span</span>,
                <span class="va">term_advance_max</span>,
                <span class="va">data_students</span>,
                <span class="va">data_terms</span>,
                <span class="va">data_degrees</span><span class="op">)</span></code></pre></div>
<ul>
<li>
<code>id</code> character vector of student IDs</li>
<li>
<code>span</code> number of years to define feasibility, default is 6 years</li>
<li>
<code>term_advance_max</code> maximum terms of transfer credit for advancing the matriculation limit, default is 4 terms (2 years)</li>
<li>
<code>data_students</code> student attributes data set, <code>midfieldstudents</code> or equivalent</li>
<li>
<code>data_terms</code> term attributes data set, <code>midfieldterms</code> or equivalent</li>
<li>
<code>data_degrees</code> degree attributes data set, <code>midfielddegrees</code> or equivalent</li>
</ul>
<p>The primary input to <code><a href="../reference/subset_feasible.html">subset_feasible()</a></code> is a character vector of student IDs. To illustrate its use, we use the built-in data set <code>rep_ever</code> from the engineering case study as developed in the <em>Stickiness metric</em> vignette <a href="stickiness_metric.html">(link)</a>.</p>
<p>View its help page by running</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="op">?</span> <span class="va">rep_ever</span></code></pre></div>
<p>The data are loaded with midfieldr.</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># view the example IDs</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">rep_ever</span><span class="op">)</span>
<span class="co">#&gt;  chr [1:11862] "MID25783166" "MID25783178" "MID25783197" "MID25783227" ...</span></code></pre></div>
<p>This vector of IDs is the input to <code><a href="../reference/subset_feasible.html">subset_feasible()</a></code>, which performs the subsetting for completion feasibility.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># filter IDs for feasible program completion within data limit</span>
<span class="va">feasible_id</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/subset_feasible.html">subset_feasible</a></span><span class="op">(</span><span class="va">rep_ever</span><span class="op">)</span>

<span class="co"># examine the result</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">feasible_id</span><span class="op">)</span>
<span class="co">#&gt;  chr [1:9281] "MID25783178" "MID25783197" "MID25783441" "MID25783491" ...</span></code></pre></div>
<p>In this instance, we started with 11,862 enrollees. After applying the criteria for feasible completion, we retain 9281 students. These students either graduated (demonstrating the feasibility of completing their programs before the data limit) or they matriculated no later than their matriculation limits.</p>
</div>
<div id="how-subset_feasible-works" class="section level2">
<h2 class="hasAnchor">
<a href="#how-subset_feasible-works" class="anchor"></a>How <code>subset_feasible()</code> works</h2>
<p>The remainder of the vignette describes the inner workings of <code><a href="../reference/subset_feasible.html">subset_feasible()</a></code>, showing intermediate results at key stages. Its operation can be divided into 5 basic steps:</p>
<ol style="list-style-type: decimal">
<li>Identify graduates and non-graduates by ID</li>
<li>Obtain entering terms and transfer credit hours by ID</li>
<li>Derive matriculation limit and median hours per term by institution</li>
<li>Advance the matriculation limit by transfer credit hours</li>
<li>Filter IDs for feasible completion</li>
</ol>
<p>The default data sets queried are from midfielddata, but if desired the arguments of <code><a href="../reference/subset_feasible.html">subset_feasible()</a></code> accommodate data sets other than those from midfielddata.</p>
<div id="identify-graduates-and-non-graduates-by-id" class="section level3">
<h3 class="hasAnchor">
<a href="#identify-graduates-and-non-graduates-by-id" class="anchor"></a>1. Identify graduates and non-graduates by ID</h3>
<p>The first data accessed by <code><a href="../reference/subset_feasible.html">subset_feasible()</a></code> is <code>midfielddegrees</code>. The head and tail of that data are show here.</p>
<pre><code>#&gt;                 id   institution   cip6 term_degree              degree
#&gt;     1: MID26131491 Institution A   &lt;NA&gt;          NA                &lt;NA&gt;
#&gt;     2: MID26131493 Institution A   &lt;NA&gt;          NA                &lt;NA&gt;
#&gt;     3: MID26131501 Institution A   &lt;NA&gt;          NA                &lt;NA&gt;
#&gt;     4: MID26131502 Institution A   &lt;NA&gt;          NA                &lt;NA&gt;
#&gt;     5: MID26131511 Institution A   &lt;NA&gt;          NA                &lt;NA&gt;
#&gt;     6: MID26131523 Institution A   &lt;NA&gt;          NA                &lt;NA&gt;
#&gt;     7: MID26131528 Institution A   &lt;NA&gt;          NA                &lt;NA&gt;
#&gt;     8: MID26131534 Institution A 110101       20034   Bachelor's Degree
#&gt;     9: MID26131544 Institution A   &lt;NA&gt;          NA                &lt;NA&gt;
#&gt;    10: MID26131549 Institution A   &lt;NA&gt;          NA                &lt;NA&gt;
#&gt;    ---                                                                 
#&gt; 97631: MID25852711 Institution M 521401       19923 Bachelor of Science
#&gt; 97632: MID25852714 Institution M 520801       20013 Bachelor of Science
#&gt; 97633: MID25852723 Institution M   &lt;NA&gt;          NA                &lt;NA&gt;
#&gt; 97634: MID25852736 Institution M 521401       19996 Bachelor of Science
#&gt; 97635: MID25852745 Institution M   &lt;NA&gt;          NA                &lt;NA&gt;
#&gt; 97636: MID25852756 Institution M 520801       20006 Bachelor of Science
#&gt; 97637: MID25852761 Institution M 131202       20021    Bachelor of Arts
#&gt; 97638: MID25852767 Institution M 260502       19946 Bachelor of Science
#&gt; 97639: MID25852770 Institution M   &lt;NA&gt;          NA                &lt;NA&gt;
#&gt; 97640: MID25852801 Institution M 451001       20031    Bachelor of Arts</code></pre>
<p>The <code>degree</code> column is re-coded so that the values are either <code>grad</code> or <code>nongrad</code>.</p>
<pre><code>#&gt;                 id   institution   cip6 term_degree  degree
#&gt;     1: MID26131491 Institution A   &lt;NA&gt;          NA nongrad
#&gt;     2: MID26131493 Institution A   &lt;NA&gt;          NA nongrad
#&gt;     3: MID26131501 Institution A   &lt;NA&gt;          NA nongrad
#&gt;     4: MID26131502 Institution A   &lt;NA&gt;          NA nongrad
#&gt;     5: MID26131511 Institution A   &lt;NA&gt;          NA nongrad
#&gt;     6: MID26131523 Institution A   &lt;NA&gt;          NA nongrad
#&gt;     7: MID26131528 Institution A   &lt;NA&gt;          NA nongrad
#&gt;     8: MID26131534 Institution A 110101       20034    grad
#&gt;     9: MID26131544 Institution A   &lt;NA&gt;          NA nongrad
#&gt;    10: MID26131549 Institution A   &lt;NA&gt;          NA nongrad
#&gt;    ---                                                     
#&gt; 97631: MID25852711 Institution M 521401       19923    grad
#&gt; 97632: MID25852714 Institution M 520801       20013    grad
#&gt; 97633: MID25852723 Institution M   &lt;NA&gt;          NA nongrad
#&gt; 97634: MID25852736 Institution M 521401       19996    grad
#&gt; 97635: MID25852745 Institution M   &lt;NA&gt;          NA nongrad
#&gt; 97636: MID25852756 Institution M 520801       20006    grad
#&gt; 97637: MID25852761 Institution M 131202       20021    grad
#&gt; 97638: MID25852767 Institution M 260502       19946    grad
#&gt; 97639: MID25852770 Institution M   &lt;NA&gt;          NA nongrad
#&gt; 97640: MID25852801 Institution M 451001       20031    grad</code></pre>
<p>In this step, we use all students in the data set so that later we can use all graduates (not just those in the study) for determining median credit hours per term by institution.</p>
</div>
<div id="obtain-entering-terms-and-transfer-credit-hours-by-id" class="section level3">
<h3 class="hasAnchor">
<a href="#obtain-entering-terms-and-transfer-credit-hours-by-id" class="anchor"></a>2. Obtain entering terms and transfer credit hours by ID</h3>
<p>The <code>midfieldstudents</code> data are accessed next to obtain the entering term and transfer credit hours by student ID for the students in the study only.</p>
<pre><code>#&gt;                 id term_enter hours_transfer
#&gt;     1: MID25934494      19921            170
#&gt;     2: MID25868987      19901            169
#&gt;     3: MID25974420      19911            169
#&gt;     4: MID25861759      20051            166
#&gt;     5: MID25873033      19961            163
#&gt;     6: MID25923220      19943            154
#&gt;     7: MID25973641      19911            143
#&gt;     8: MID25905410      19931            136
#&gt;     9: MID26688433      20083            135
#&gt;    10: MID26362384      20041            128
#&gt;    ---                                      
#&gt; 10126: MID26696429      20101             NA
#&gt; 10127: MID26696439      20101             NA
#&gt; 10128: MID26696484      20101             NA
#&gt; 10129: MID26696642      20121             NA
#&gt; 10130: MID26696771      20101             NA
#&gt; 10131: MID26696958      20111             NA
#&gt; 10132: MID26696967      20101             NA
#&gt; 10133: MID26697163      20101             NA
#&gt; 10134: MID26697444      20101             NA
#&gt; 10135: MID26697447      20111             NA</code></pre>
</div>
<div id="derive-matriculation-limit-and-median-hours-per-term-by-institution" class="section level3">
<h3 class="hasAnchor">
<a href="#derive-matriculation-limit-and-median-hours-per-term-by-institution" class="anchor"></a>3. Derive matriculation limit and median hours per term by institution</h3>
<p>The <code>midfieldterms</code> data are accessed to obtain the data limits by institution. The <code>max_term</code> column is the result of a group and summarize operation.</p>
<pre><code>#&gt;       institution max_term
#&gt;  1: Institution A    20034
#&gt;  2: Institution B    20104
#&gt;  3: Institution C    20154
#&gt;  4: Institution D    20154
#&gt;  5: Institution E    20034
#&gt;  6: Institution F    20044
#&gt;  7: Institution G    20051
#&gt;  8: Institution H    20036
#&gt;  9: Institution J    20096
#&gt; 10: Institution K    20034
#&gt; 11: Institution L    20164
#&gt; 12: Institution M    20096</code></pre>
<p>The <code>span</code> number of years is subtracted from the maximum term to create the initial matriculation limit.</p>
<pre><code>#&gt;       institution max_term span_terms matric_limit
#&gt;  1: Institution A    20034        -12        19981
#&gt;  2: Institution B    20104        -12        20051
#&gt;  3: Institution C    20154        -12        20101
#&gt;  4: Institution D    20154        -12        20101
#&gt;  5: Institution E    20034        -12        19981
#&gt;  6: Institution F    20044        -12        19991
#&gt;  7: Institution G    20051        -12        19993
#&gt;  8: Institution H    20036        -12        19981
#&gt;  9: Institution J    20096        -12        20041
#&gt; 10: Institution K    20034        -12        19981
#&gt; 11: Institution L    20164        -12        20111
#&gt; 12: Institution M    20096        -12        20041</code></pre>
<p>To check the term addition represented here, consider Institution M. The span is 6 years (12 terms) and the last term in the data set is <code>20096</code> or summer of 2009-10 academic year. The algorithm rounds down to the spring term <code>20093</code> and subtracts the span. The six academic years ending in the Spring 2009-10 are: 2004-05, 2005-06, 2006-07, 2007-08, 2008-09, and 2009-10. Thus the matriculation limit is Fall of 2004, encoded <code>20041</code>.</p>
<p>In the final data query, the function filters <code>midfieldterms</code> by the IDs of all graduates in the data set, an ID vector we obtained in the first step. The function then determines the median number of credit hours per term by institution for successful (i.e., graduating) students.</p>
<p>Joining these results with the previous findings yields the data frame needed to subset for feasible completion.</p>
<pre><code>#&gt;                 id   institution term_enter hours_transfer med_hr_per_term
#&gt;     1: MID26131502 Institution A      20011             NA              13
#&gt;     2: MID26131523 Institution A      20011             NA              13
#&gt;     3: MID26131544 Institution A      19981             NA              13
#&gt;     4: MID26133649 Institution A      19901             NA              13
#&gt;     5: MID26135340 Institution A      20024             NA              13
#&gt;     6: MID26137725 Institution A      19901             NA              13
#&gt;     7: MID26138315 Institution A      20021             NA              13
#&gt;     8: MID26140157 Institution A      19941             NA              13
#&gt;     9: MID26140925 Institution A      19913             NA              13
#&gt;    10: MID26141076 Institution A      20001             NA              13
#&gt;    ---                                                                    
#&gt; 10126: MID25852065 Institution M      19981             NA              14
#&gt; 10127: MID25852214 Institution M      20081             NA              14
#&gt; 10128: MID25852453 Institution M      19891             NA              14
#&gt; 10129: MID25852465 Institution M      19891             NA              14
#&gt; 10130: MID25852497 Institution M      19981             NA              14
#&gt; 10131: MID25852503 Institution M      19981             NA              14
#&gt; 10132: MID25852510 Institution M      19941             NA              14
#&gt; 10133: MID25852624 Institution M      19921             NA              14
#&gt; 10134: MID25852630 Institution M      20061             NA              14
#&gt; 10135: MID25852745 Institution M      20011             NA              14
#&gt;        matric_limit  degree
#&gt;     1:        19981 nongrad
#&gt;     2:        19981 nongrad
#&gt;     3:        19981 nongrad
#&gt;     4:        19981 nongrad
#&gt;     5:        19981 nongrad
#&gt;     6:        19981 nongrad
#&gt;     7:        19981 nongrad
#&gt;     8:        19981 nongrad
#&gt;     9:        19981    grad
#&gt;    10:        19981 nongrad
#&gt;    ---                     
#&gt; 10126:        20041    grad
#&gt; 10127:        20041 nongrad
#&gt; 10128:        20041    grad
#&gt; 10129:        20041    grad
#&gt; 10130:        20041 nongrad
#&gt; 10131:        20041    grad
#&gt; 10132:        20041 nongrad
#&gt; 10133:        20041    grad
#&gt; 10134:        20041 nongrad
#&gt; 10135:        20041 nongrad</code></pre>
</div>
<div id="advance-the-matriculation-limit-by-transfer-credit-hours" class="section level3">
<h3 class="hasAnchor">
<a href="#advance-the-matriculation-limit-by-transfer-credit-hours" class="anchor"></a>4. Advance the matriculation limit by transfer credit hours</h3>
<p>Transfer credit hours are converted to an equivalent number of “transfer terms” by dividing by the median hours per term. The result is capped (default is 4 terms or 2 years) to account for the common institutional policy that the final two years of an undergraduate degree be earned at the degree-granting institution.</p>
<p>Transfer students’ matriculation limits are advanced by the number of transfer terms. The printout shows two students (lines 8 and 10,132) whose matriculation term exceeds the matriculation limit, exemplifying students who are removed from the analysis in the next step.</p>
<pre><code>#&gt;                 id term_enter matric_limit  degree
#&gt;     1: MID25783178      19946        20041    grad
#&gt;     2: MID25783197      19871        20041    grad
#&gt;     3: MID25783388      19871        20041 nongrad
#&gt;     4: MID25783441      19921        20041    grad
#&gt;     5: MID25783491      19961        20041    grad
#&gt;     6: MID25783553      20021        20041 nongrad
#&gt;     7: MID25783606      20011        20041 nongrad
#&gt;     8: MID25783648      20071        20041 nongrad
#&gt;     9: MID25783912      19971        20041    grad
#&gt;    10: MID25784022      20011        20041 nongrad
#&gt;    ---                                            
#&gt; 10126: MID26696484      20101        20111    grad
#&gt; 10127: MID26696642      20121        20111    grad
#&gt; 10128: MID26696738      20114        20131    grad
#&gt; 10129: MID26696771      20101        20111    grad
#&gt; 10130: MID26696958      20111        20111 nongrad
#&gt; 10131: MID26696967      20101        20111    grad
#&gt; 10132: MID26696979      20154        20131 nongrad
#&gt; 10133: MID26697163      20101        20111    grad
#&gt; 10134: MID26697444      20101        20111    grad
#&gt; 10135: MID26697447      20111        20111    grad</code></pre>
</div>
<div id="filter-ids-for-feasible-completion" class="section level3">
<h3 class="hasAnchor">
<a href="#filter-ids-for-feasible-completion" class="anchor"></a>5. Filter IDs for feasible completion</h3>
<p>This final data frame is ready for subsetting for feasible completion. All graduates are retained. Non-graduates are retained if their term of entry is no later than their matriculation limit.</p>
<pre><code>#&gt;                id term_enter matric_limit  degree
#&gt;    1: MID25783178      19946        20041    grad
#&gt;    2: MID25783197      19871        20041    grad
#&gt;    3: MID25783388      19871        20041 nongrad
#&gt;    4: MID25783441      19921        20041    grad
#&gt;    5: MID25783491      19961        20041    grad
#&gt;    6: MID25783553      20021        20041 nongrad
#&gt;    7: MID25783606      20011        20041 nongrad
#&gt;    8: MID25783912      19971        20041    grad
#&gt;    9: MID25784022      20011        20041 nongrad
#&gt;   10: MID25784025      19891        20041 nongrad
#&gt;   ---                                            
#&gt; 8034: MID26696439      20101        20111 nongrad
#&gt; 8035: MID26696484      20101        20111    grad
#&gt; 8036: MID26696642      20121        20111    grad
#&gt; 8037: MID26696738      20114        20131    grad
#&gt; 8038: MID26696771      20101        20111    grad
#&gt; 8039: MID26696958      20111        20111 nongrad
#&gt; 8040: MID26696967      20101        20111    grad
#&gt; 8041: MID26697163      20101        20111    grad
#&gt; 8042: MID26697444      20101        20111    grad
#&gt; 8043: MID26697447      20111        20111    grad</code></pre>
<p>The final output of the function is the ID column from this data frame.</p>
<pre><code>#&gt;  chr [1:8043] "MID25783178" "MID25783197" "MID25783388" "MID25783441" ...</code></pre>
<p>This vector is identical to <code>feasible_id</code> described in the first part of the vignette.</p>
</div>
</div>
<div id="references" class="section level2">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs" class="references csl-bib-body hanging-indent">
<div id="ref-IPEDS:2020" class="csl-entry">
NCES (2020) <em><span>IPEDS Survey Methodology</span></em>. <span>National Center for Education Statistics</span>; [Online; accessed 2020-07-29]. Available at: <a href="https://nces.ed.gov/ipeds/ReportYourData/IpedsSurveyMethodology">https://nces.ed.gov/ipeds/ReportYourData/IpedsSurveyMethodology</a>.
</div>
</div>
</div>
<div id="appendix" class="section level2">
<h2 class="hasAnchor">
<a href="#appendix" class="anchor"></a>Appendix</h2>
<div id="complete-script" class="section level3">
<h3 class="hasAnchor">
<a href="#complete-script" class="anchor"></a>Complete script</h3>
<p>The vignette code chunks are collected below in a single, condensed script.</p>
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># packages used</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/MIDFIELDR/midfieldr">midfieldr</a></span><span class="op">)</span>

<span class="co"># part 1:  How to use subset_feasible()</span>
<span class="va">feasible_id</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/subset_feasible.html">subset_feasible</a></span><span class="op">(</span><span class="va">rep_ever</span><span class="op">)</span>

<span class="co"># part 2:  How subset_feasible() works</span>
<span class="co"># no reproducible code</span></code></pre></div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Richard Layton, Russell Long, Matthew Ohland, US National Science Foundation.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
