<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Graduation rate • midfieldr</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/spacelab/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Graduation rate">
<meta property="og:description" content="midfieldr">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">midfieldr</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.0.0.9005</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/get_started.html">Get started</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Vignettes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/data_basics.html">Data basics</a>
    </li>
    <li>
      <a href="../articles/multiway_graphs.html">Multiway graphs and tables</a>
    </li>
    <li>
      <a href="../articles/identify_programs.html">Identify programs</a>
    </li>
    <li>
      <a href="../articles/handle_fye.html">Handle FYE programs</a>
    </li>
    <li>
      <a href="../articles/feasible_completion.html">Feasible completion</a>
    </li>
    <li>
      <a href="../articles/graduation_rate.html">Graduation rate</a>
    </li>
    <li>
      <a href="../articles/stickiness_metric.html">Stickiness metric</a>
    </li>
  </ul>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="../articles/pages/get_session.html">Session info</a>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
<li>
  <a href="../articles/pages/about_midfield.html">About</a>
</li>
<li>
  <a href="https://github.com/MIDFIELDR/midfieldr">
    <span class="fa fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="graduation_rate_files/accessible-code-block-0.0.1/empty-anchor.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Graduation rate</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/MIDFIELDR/midfieldr/blob/master/vignettes/graduation_rate.Rmd"><code>vignettes/graduation_rate.Rmd</code></a></small>
      <div class="hidden name"><code>graduation_rate.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>Despite its flaws, graduation rate is commonly used persistence metric.</p>
<p>In the US, the Integrated Postsecondary Education Data System (IPEDS) defines “graduation rate” as the fraction of <em>full-time, first-time,</em> degree/certificate-seeking undergraduate students in a particular year who <em>complete the program in which they matriculate</em> within 150 percent of normal time, i.e., <em>within 6 years</em> for a 4-year program <span class="citation">(NCES, <a href="#ref-IPEDS:2020" role="doc-biblioref">2020</a>)</span>.</p>
<p>The IPEDS definition excludes students who attend college part-time, who transfer from one institution to another, and who change majors. The American Council on Education (ACE) estimates that this definition of graduation rate may exclude up to 60% of students at 4-year institutions <span class="citation">(Cook and Hartle, <a href="#ref-Cook+Hartle:2011" role="doc-biblioref">2011</a>)</span>.</p>
<p>So why use the metric? Do graduation rates really matter? Cook and Hartle say, yes they do …</p>
<blockquote>
<p>… because in the eyes of the public, policy makers, and the media, they provide a clear, simple, and logical—if often misleading—number.</p>
</blockquote>
<p>So with these caveats in mind, we provide the tools for determining program graduation rates per the IPEDS definition.</p>
<div id="this-vignette-uses" class="section level3">
<h3 class="hasAnchor">
<a href="#this-vignette-uses" class="anchor"></a>This vignette uses</h3>
<p>midfieldr functions</p>
<ul>
<li><code><a href="../reference/subset_feasible.html">subset_feasible()</a></code></li>
<li><code><a href="../reference/subset_ipeds.html">subset_ipeds()</a></code></li>
<li><code><a href="../reference/prepare_multiway.html">prepare_multiway()</a></code></li>
</ul>
<p>data.table syntax</p>
<ul>
<li>
<code><a href="https://Rdatatable.gitlab.io/data.table/reference/copy.html">copy()</a></code> prevent changing a source by reference</li>
<li>
<code><a href="https://Rdatatable.gitlab.io/data.table/reference/setattr.html">setnames()</a></code> rename columns</li>
<li>
<code>DT[]</code> print a data frame</li>
<li>
<code>DT[rows_we_want]</code> subset rows</li>
<li>
<code>DT[, col := NULL]</code> remove a column</li>
<li>
<code>DT[, col := FUN]</code> assign values in a column</li>
<li>
<code>DT[, .(new_col = .N), by = grouping_variables]</code> count N by group</li>
</ul>
<p>packages</p>
<div class="sourceCode" id="cb1"><html><body><pre class="r"><span class="co"># packages used</span>
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">midfieldr</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">midfielddata</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">data.table</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">ggplot2</span>)

<span class="co"># print max 20 rows, otherwise 10 rows each head/tail</span>
<span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span>(<span class="kw">datatable.print.nrows</span> <span class="kw">=</span> <span class="fl">20</span>, <span class="kw">datatable.print.topn</span> <span class="kw">=</span> <span class="fl">10</span>)</pre></body></html></div>
</div>
</div>
<div id="choose-the-programs-to-study" class="section level2">
<h2 class="hasAnchor">
<a href="#choose-the-programs-to-study" class="anchor"></a>Choose the programs to study</h2>
<p>The program group for the engineering case study is included with midfieldr as the built-in data set <code>rep_group</code>. View its help page by running</p>
<div class="sourceCode" id="cb2"><html><body><pre class="r">? <span class="no">rep_group</span></pre></body></html></div>
<p>The data are loaded with midfieldr.</p>
<div class="sourceCode" id="cb3"><html><body><pre class="r"><span class="co"># obtain programs (built-in data set)</span>
<span class="no">program_group</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/copy.html">copy</a></span>(<span class="no">rep_group</span>)

<span class="co"># examine the result</span>
<span class="no">program_group</span>
<span class="co">#&gt;       cip6                program</span>
<span class="co">#&gt;  1: 140801      Civil Engineering</span>
<span class="co">#&gt;  2: 140802      Civil Engineering</span>
<span class="co">#&gt;  3: 140803      Civil Engineering</span>
<span class="co">#&gt;  4: 140804      Civil Engineering</span>
<span class="co">#&gt;  5: 140805      Civil Engineering</span>
<span class="co">#&gt;  6: 140899      Civil Engineering</span>
<span class="co">#&gt;  7: 141001 Electrical Engineering</span>
<span class="co">#&gt;  8: 141003 Electrical Engineering</span>
<span class="co">#&gt;  9: 141004 Electrical Engineering</span>
<span class="co">#&gt; 10: 141099 Electrical Engineering</span>
<span class="co">#&gt; 11: 141901 Mechanical Engineering</span>
<span class="co">#&gt; 12: 143501 Industrial Engineering</span></pre></body></html></div>
<p>We extract the <code>cip6</code> column as a character vector to gather student data.</p>
<div class="sourceCode" id="cb4"><html><body><pre class="r"><span class="co"># extract a vector of 6-digit CIP codes</span>
<span class="no">group_cip</span> <span class="kw">&lt;-</span> <span class="no">program_group</span>$<span class="no">cip6</span>

<span class="co"># examine the result</span>
<span class="no">group_cip</span>
<span class="co">#&gt;  [1] "140801" "140802" "140803" "140804" "140805" "140899" "141001" "141003"</span>
<span class="co">#&gt;  [9] "141004" "141099" "141901" "143501"</span></pre></body></html></div>
<p>Related vignettes</p>
<ul>
<li>
<em>Identify programs</em> <a href="identify_programs.html">(link)</a> illustrates program labeling options</li>
</ul>
</div>
<div id="gather-the-starters" class="section level2">
<h2 class="hasAnchor">
<a href="#gather-the-starters" class="anchor"></a>Gather the starters</h2>
<p>By “starters” we mean students matriculating in a case study program and FYE students whose starting programs are in the case study.</p>
<ul>
<li>matriculants from <code>midfieldstudents</code> by CIP</li>
<li>FYE starters from <code>fye_start</code>
</li>
</ul>
<p>From <code>midfieldstudents</code>, we extract the IDs of students matriculating in these programs.</p>
<div class="sourceCode" id="cb5"><html><body><pre class="r"><span class="co"># gather students matriculating in programs</span>
<span class="no">cols_we_want</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"id"</span>, <span class="st">"cip6"</span>)
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">midfieldstudents</span>$<span class="no">cip6</span> <span class="kw">%in%</span> <span class="no">group_cip</span>
<span class="no">matriculants</span> <span class="kw">&lt;-</span> <span class="no">midfieldstudents</span>[<span class="no">rows_we_want</span>, <span class="no">..cols_we_want</span>]
<span class="no">matriculants</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/duplicated.html">unique</a></span>(<span class="no">matriculants</span>)

<span class="co"># examine the result</span>
<span class="no">matriculants</span>
<span class="co">#&gt;                id   cip6</span>
<span class="co">#&gt;    1: MID25792087 141901</span>
<span class="co">#&gt;    2: MID25796088 140801</span>
<span class="co">#&gt;    3: MID25799551 141001</span>
<span class="co">#&gt;    4: MID25799578 141001</span>
<span class="co">#&gt;    5: MID25808049 140801</span>
<span class="co">#&gt;    6: MID25814680 141901</span>
<span class="co">#&gt;    7: MID25816716 141901</span>
<span class="co">#&gt;    8: MID25818239 141001</span>
<span class="co">#&gt;    9: MID25825948 140801</span>
<span class="co">#&gt;   10: MID25836704 141901</span>
<span class="co">#&gt;   ---                   </span>
<span class="co">#&gt; 5017: MID26696337 140801</span>
<span class="co">#&gt; 5018: MID26696429 143501</span>
<span class="co">#&gt; 5019: MID26696439 141901</span>
<span class="co">#&gt; 5020: MID26696484 141901</span>
<span class="co">#&gt; 5021: MID26696642 141001</span>
<span class="co">#&gt; 5022: MID26696738 141901</span>
<span class="co">#&gt; 5023: MID26696958 141901</span>
<span class="co">#&gt; 5024: MID26696967 141901</span>
<span class="co">#&gt; 5025: MID26696979 141901</span>
<span class="co">#&gt; 5026: MID26697444 141901</span></pre></body></html></div>
<p>In the <em>Handle FYE programs</em> vignette <a href="handle_fye.html">(link)</a>, we derive the starting programs for all FYE students in midfielddata. Again, we filter by the program group CIP codes.</p>
<div class="sourceCode" id="cb6"><html><body><pre class="r"><span class="co"># gather FYE students predicted to start in these programs</span>
<span class="no">cols_we_want</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"id"</span>, <span class="st">"start"</span>)
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">fye_start</span>$<span class="no">start</span> <span class="kw">%in%</span> <span class="no">group_cip</span>
<span class="no">fye_starters</span> <span class="kw">&lt;-</span> <span class="no">fye_start</span>[<span class="no">rows_we_want</span>, <span class="no">..cols_we_want</span>]
<span class="no">fye_starters</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/duplicated.html">unique</a></span>(<span class="no">fye_starters</span>)
<span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/setattr.html">setnames</a></span>(<span class="no">fye_starters</span>, <span class="kw">old</span> <span class="kw">=</span> <span class="st">"start"</span>, <span class="kw">new</span> <span class="kw">=</span> <span class="st">"cip6"</span>)

<span class="co"># examine the result</span>
<span class="no">fye_starters</span>
<span class="co">#&gt;                id   cip6</span>
<span class="co">#&gt;    1: MID25783166 141901</span>
<span class="co">#&gt;    2: MID25783227 141001</span>
<span class="co">#&gt;    3: MID25783388 141901</span>
<span class="co">#&gt;    4: MID25783428 140801</span>
<span class="co">#&gt;    5: MID25783441 140801</span>
<span class="co">#&gt;    6: MID25783491 141001</span>
<span class="co">#&gt;    7: MID25783553 140801</span>
<span class="co">#&gt;    8: MID25783606 141001</span>
<span class="co">#&gt;    9: MID25783648 140801</span>
<span class="co">#&gt;   10: MID25783753 141901</span>
<span class="co">#&gt;   ---                   </span>
<span class="co">#&gt; 3819: MID26648222 141901</span>
<span class="co">#&gt; 3820: MID26648282 143501</span>
<span class="co">#&gt; 3821: MID26648283 141001</span>
<span class="co">#&gt; 3822: MID26648334 140801</span>
<span class="co">#&gt; 3823: MID26648392 141901</span>
<span class="co">#&gt; 3824: MID26648422 141901</span>
<span class="co">#&gt; 3825: MID26648435 141901</span>
<span class="co">#&gt; 3826: MID26648484 140801</span>
<span class="co">#&gt; 3827: MID26648517 140801</span>
<span class="co">#&gt; 3828: MID26648544 141901</span></pre></body></html></div>
<p>Bind the two data frames</p>
<div class="sourceCode" id="cb7"><html><body><pre class="r"><span class="no">starters</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/rbindlist.html">rbind</a></span>(<span class="no">matriculants</span>, <span class="no">fye_starters</span>)

<span class="co"># examine the result</span>
<span class="no">starters</span>
<span class="co">#&gt;                id   cip6</span>
<span class="co">#&gt;    1: MID25792087 141901</span>
<span class="co">#&gt;    2: MID25796088 140801</span>
<span class="co">#&gt;    3: MID25799551 141001</span>
<span class="co">#&gt;    4: MID25799578 141001</span>
<span class="co">#&gt;    5: MID25808049 140801</span>
<span class="co">#&gt;    6: MID25814680 141901</span>
<span class="co">#&gt;    7: MID25816716 141901</span>
<span class="co">#&gt;    8: MID25818239 141001</span>
<span class="co">#&gt;    9: MID25825948 140801</span>
<span class="co">#&gt;   10: MID25836704 141901</span>
<span class="co">#&gt;   ---                   </span>
<span class="co">#&gt; 8845: MID26648222 141901</span>
<span class="co">#&gt; 8846: MID26648282 143501</span>
<span class="co">#&gt; 8847: MID26648283 141001</span>
<span class="co">#&gt; 8848: MID26648334 140801</span>
<span class="co">#&gt; 8849: MID26648392 141901</span>
<span class="co">#&gt; 8850: MID26648422 141901</span>
<span class="co">#&gt; 8851: MID26648435 141901</span>
<span class="co">#&gt; 8852: MID26648484 140801</span>
<span class="co">#&gt; 8853: MID26648517 140801</span>
<span class="co">#&gt; 8854: MID26648544 141901</span></pre></body></html></div>
<p>For some of these students, completing their program may not be feasible given the range of data available. <code><a href="../reference/subset_feasible.html">subset_feasible()</a></code> subsets the student IDs, retaining those who matriculate at least six years before the last term in the data.</p>
<div class="sourceCode" id="cb8"><html><body><pre class="r"><span class="co"># apply the feasible completion filter</span>
<span class="no">feasible_ids</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/subset_feasible.html">subset_feasible</a></span>(<span class="kw">id</span> <span class="kw">=</span> <span class="no">starters</span>$<span class="no">id</span>)

<span class="co"># examine the result</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span>(<span class="no">feasible_ids</span>)
<span class="co">#&gt;  chr [1:6947] "MID25783441" "MID25783491" "MID25783912" "MID25784047" ...</span></pre></body></html></div>
<p>See the <em>Feasible completion</em> vignette <a href="feasible_completion.html">(link)</a> for a detailed explanation of how completion feasibility is determined.</p>
<div class="sourceCode" id="cb9"><html><body><pre class="r"><span class="co"># subset the starters</span>
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">starters</span>$<span class="no">id</span> <span class="kw">%in%</span> <span class="no">feasible_ids</span>
<span class="no">starters</span> <span class="kw">&lt;-</span> <span class="no">starters</span>[<span class="no">rows_we_want</span>]

<span class="co"># examine the result</span>
<span class="no">starters</span>
<span class="co">#&gt;                id   cip6</span>
<span class="co">#&gt;    1: MID25792087 141901</span>
<span class="co">#&gt;    2: MID25796088 140801</span>
<span class="co">#&gt;    3: MID25799551 141001</span>
<span class="co">#&gt;    4: MID25799578 141001</span>
<span class="co">#&gt;    5: MID25808049 140801</span>
<span class="co">#&gt;    6: MID25814680 141901</span>
<span class="co">#&gt;    7: MID25816716 141901</span>
<span class="co">#&gt;    8: MID25818239 141001</span>
<span class="co">#&gt;    9: MID25825948 140801</span>
<span class="co">#&gt;   10: MID25836704 141901</span>
<span class="co">#&gt;   ---                   </span>
<span class="co">#&gt; 6938: MID26624428 143501</span>
<span class="co">#&gt; 6939: MID26624493 141901</span>
<span class="co">#&gt; 6940: MID26624564 143501</span>
<span class="co">#&gt; 6941: MID26624723 141001</span>
<span class="co">#&gt; 6942: MID26624792 141901</span>
<span class="co">#&gt; 6943: MID26625136 143501</span>
<span class="co">#&gt; 6944: MID26628494 141901</span>
<span class="co">#&gt; 6945: MID26629213 140801</span>
<span class="co">#&gt; 6946: MID26630725 141901</span>
<span class="co">#&gt; 6947: MID26636885 140801</span></pre></body></html></div>
<p>These are the students eligible to be considered starters in our case study programs before we apply the IPEDS constraints.</p>
<p>The <code>starters</code> data frame is the input to <code><a href="../reference/subset_ipeds.html">subset_ipeds()</a></code>.</p>
</div>
<div id="apply-ipeds-criteria" class="section level2">
<h2 class="hasAnchor">
<a href="#apply-ipeds-criteria" class="anchor"></a>Apply IPEDS criteria</h2>
<p>In the next step, we subset the starters, retaining those who satisfy the IPEDS criteria:</p>
<ul>
<li>first time in college (thus removing transfers)</li>
<li>matriculate and graduate in the same program (thus removing migrators)</li>
<li>graduate no later than 6 years after matriculation (effectively removing part-time students)</li>
</ul>
<p>The IPEDS definition excludes part-time students. We do not test for part-time status specifically. We assume that students attending for no more than 6 years are effectively full-time.</p>
<p>The input to <code><a href="../reference/subset_ipeds.html">subset_ipeds()</a></code> is the <code>starters</code> data frame with columns <code>id</code> and <code>start</code>. The function subsets the rows of the data frame per the IPEDS constraints and adds a new yes/no column <code>ipeds_grad</code>, where “Y” indicates that the student’s graduation accords with the IPEDS definition of graduation rate.</p>
<div class="sourceCode" id="cb10"><html><body><pre class="r"><span class="co"># subset_ipeds() requires a CIP `start` column</span>
<span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/setattr.html">setnames</a></span>(<span class="no">starters</span>, <span class="kw">old</span> <span class="kw">=</span> <span class="st">"cip6"</span>, <span class="kw">new</span> <span class="kw">=</span> <span class="st">"start"</span>)
<span class="no">ipeds_students</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/subset_ipeds.html">subset_ipeds</a></span>(<span class="no">starters</span>)
<span class="no">ipeds_students</span>[]
<span class="co">#&gt;                id  start ipeds_grad</span>
<span class="co">#&gt;    1: MID25783227 141001          N</span>
<span class="co">#&gt;    2: MID25783388 141901          N</span>
<span class="co">#&gt;    3: MID25783441 140801          Y</span>
<span class="co">#&gt;    4: MID25783491 141001          Y</span>
<span class="co">#&gt;    5: MID25783553 140801          N</span>
<span class="co">#&gt;    6: MID25783606 141001          N</span>
<span class="co">#&gt;    7: MID25783753 141901          N</span>
<span class="co">#&gt;    8: MID25783830 141901          N</span>
<span class="co">#&gt;    9: MID25783912 143501          Y</span>
<span class="co">#&gt;   10: MID25784022 141901          N</span>
<span class="co">#&gt;   ---                              </span>
<span class="co">#&gt; 5828: MID26696050 141901          Y</span>
<span class="co">#&gt; 5829: MID26696234 141901          Y</span>
<span class="co">#&gt; 5830: MID26696337 140801          Y</span>
<span class="co">#&gt; 5831: MID26696429 143501          Y</span>
<span class="co">#&gt; 5832: MID26696439 141901          N</span>
<span class="co">#&gt; 5833: MID26696484 141901          Y</span>
<span class="co">#&gt; 5834: MID26696642 141001          Y</span>
<span class="co">#&gt; 5835: MID26696958 141901          N</span>
<span class="co">#&gt; 5836: MID26696967 141901          Y</span>
<span class="co">#&gt; 5837: MID26697444 141901          N</span></pre></body></html></div>
<p>By applying the IPEDS restrictions, we’ve dropped from 6947 to 5837 students in this example, a 16% reduction in the number of students being considered.</p>
</div>
<div id="group-summarize-and-join" class="section level2">
<h2 class="hasAnchor">
<a href="#group-summarize-and-join" class="anchor"></a>Group, summarize, and join</h2>
<p>Join program labels, race/ethnicity and sex.</p>
<div class="sourceCode" id="cb11"><html><body><pre class="r"><span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/setattr.html">setnames</a></span>(<span class="no">ipeds_students</span>, <span class="kw">old</span> <span class="kw">=</span> <span class="st">"start"</span>, <span class="kw">new</span> <span class="kw">=</span> <span class="st">"cip6"</span>)

<span class="co"># join race sex</span>
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">midfieldstudents</span>$<span class="no">id</span> <span class="kw">%in%</span> <span class="no">ipeds_students</span>$<span class="no">id</span>
<span class="no">cols_we_want</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"id"</span>, <span class="st">"race"</span>, <span class="st">"sex"</span>)
<span class="no">race_sex</span> <span class="kw">&lt;-</span> <span class="no">midfieldstudents</span>[<span class="no">rows_we_want</span>, <span class="no">..cols_we_want</span>]
<span class="no">race_sex</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/duplicated.html">unique</a></span>(<span class="no">race_sex</span>)
<span class="no">ipeds_students</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/merge.html">merge</a></span>(<span class="no">ipeds_students</span>, <span class="no">race_sex</span>, <span class="kw">by</span> <span class="kw">=</span> <span class="st">"id"</span>, <span class="kw">all.x</span> <span class="kw">=</span> <span class="fl">TRUE</span>)

<span class="co"># join programs</span>
<span class="no">ipeds_students</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/merge.html">merge</a></span>(<span class="no">ipeds_students</span>,
  <span class="no">program_group</span>,
  <span class="kw">by</span> <span class="kw">=</span> <span class="st">"cip6"</span>,
  <span class="kw">all.x</span> <span class="kw">=</span> <span class="fl">TRUE</span>
)

<span class="co"># done with ID and CIP</span>
<span class="no">ipeds_students</span>[, <span class="no">id</span> <span class="kw">:=</span> <span class="kw">NULL</span>]
<span class="no">ipeds_students</span>[, <span class="no">cip6</span> <span class="kw">:=</span> <span class="kw">NULL</span>]

<span class="no">ipeds_students</span>
<span class="co">#&gt;       ipeds_grad    race    sex                program</span>
<span class="co">#&gt;    1:          Y   White   Male      Civil Engineering</span>
<span class="co">#&gt;    2:          N   White   Male      Civil Engineering</span>
<span class="co">#&gt;    3:          Y   White   Male      Civil Engineering</span>
<span class="co">#&gt;    4:          N   White   Male      Civil Engineering</span>
<span class="co">#&gt;    5:          Y   White   Male      Civil Engineering</span>
<span class="co">#&gt;    6:          Y   White   Male      Civil Engineering</span>
<span class="co">#&gt;    7:          N   White   Male      Civil Engineering</span>
<span class="co">#&gt;    8:          N   White Female      Civil Engineering</span>
<span class="co">#&gt;    9:          N   White Female      Civil Engineering</span>
<span class="co">#&gt;   10:          N   White   Male      Civil Engineering</span>
<span class="co">#&gt;   ---                                                 </span>
<span class="co">#&gt; 5828:          Y   White Female Industrial Engineering</span>
<span class="co">#&gt; 5829:          Y   White Female Industrial Engineering</span>
<span class="co">#&gt; 5830:          Y   Black   Male Industrial Engineering</span>
<span class="co">#&gt; 5831:          Y   White   Male Industrial Engineering</span>
<span class="co">#&gt; 5832:          N Unknown Female Industrial Engineering</span>
<span class="co">#&gt; 5833:          N Unknown   Male Industrial Engineering</span>
<span class="co">#&gt; 5834:          Y   White   Male Industrial Engineering</span>
<span class="co">#&gt; 5835:          Y   White   Male Industrial Engineering</span>
<span class="co">#&gt; 5836:          Y   White   Male Industrial Engineering</span>
<span class="co">#&gt; 5837:          Y   White Female Industrial Engineering</span></pre></body></html></div>
<p>Aggregate number of starters by program, race, and sex</p>
<div class="sourceCode" id="cb12"><html><body><pre class="r"><span class="co"># assign variables to aggregate by</span>
<span class="no">grouping_variables</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"program"</span>, <span class="st">"race"</span>, <span class="st">"sex"</span>)

<span class="co"># group and summarize</span>
<span class="no">grouped_starters</span> <span class="kw">&lt;-</span> <span class="no">ipeds_students</span>[, <span class="fu">.</span>(<span class="kw">start</span> <span class="kw">=</span> <span class="no">.N</span>), <span class="kw">by</span> <span class="kw">=</span> <span class="no">grouping_variables</span>]

<span class="co"># examine the result</span>
<span class="no">grouped_starters</span>
<span class="co">#&gt;                    program            race    sex start</span>
<span class="co">#&gt;  1:      Civil Engineering           White   Male   815</span>
<span class="co">#&gt;  2:      Civil Engineering           White Female   242</span>
<span class="co">#&gt;  3:      Civil Engineering           Black   Male    60</span>
<span class="co">#&gt;  4:      Civil Engineering           Black Female    28</span>
<span class="co">#&gt;  5:      Civil Engineering           Other   Male    10</span>
<span class="co">#&gt;  6:      Civil Engineering           Asian   Male    31</span>
<span class="co">#&gt;  7:      Civil Engineering        Hispanic   Male    33</span>
<span class="co">#&gt;  8:      Civil Engineering           Other Female     3</span>
<span class="co">#&gt;  9:      Civil Engineering           Asian Female    14</span>
<span class="co">#&gt; 10:      Civil Engineering   International   Male     6</span>
<span class="co">#&gt; ---                                                    </span>
<span class="co">#&gt; 52: Industrial Engineering   International   Male    19</span>
<span class="co">#&gt; 53: Industrial Engineering        Hispanic   Male    13</span>
<span class="co">#&gt; 54: Industrial Engineering        Hispanic Female     2</span>
<span class="co">#&gt; 55: Industrial Engineering           Asian Female    16</span>
<span class="co">#&gt; 56: Industrial Engineering   International Female     3</span>
<span class="co">#&gt; 57: Industrial Engineering Native American   Male     1</span>
<span class="co">#&gt; 58: Industrial Engineering           Other Female     3</span>
<span class="co">#&gt; 59: Industrial Engineering           Other   Male     6</span>
<span class="co">#&gt; 60: Industrial Engineering         Unknown Female     1</span>
<span class="co">#&gt; 61: Industrial Engineering         Unknown   Male     1</span></pre></body></html></div>
<p>Aggregate number of graduates by program, race, and sex</p>
<div class="sourceCode" id="cb13"><html><body><pre class="r"><span class="co"># group and summarize</span>
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">ipeds_students</span>$<span class="no">ipeds_grad</span> <span class="kw">==</span> <span class="st">"Y"</span>
<span class="no">grouped_graduates</span> <span class="kw">&lt;-</span> <span class="no">ipeds_students</span>[<span class="no">rows_we_want</span>,
  <span class="fu">.</span>(<span class="kw">grad</span> <span class="kw">=</span> <span class="no">.N</span>),
  <span class="kw">by</span> <span class="kw">=</span> <span class="no">grouping_variables</span>
]

<span class="co"># examine the result</span>
<span class="no">grouped_graduates</span>
<span class="co">#&gt;                    program            race    sex grad</span>
<span class="co">#&gt;  1:      Civil Engineering           White   Male  335</span>
<span class="co">#&gt;  2:      Civil Engineering           White Female   95</span>
<span class="co">#&gt;  3:      Civil Engineering           Black   Male   19</span>
<span class="co">#&gt;  4:      Civil Engineering           Asian   Male   12</span>
<span class="co">#&gt;  5:      Civil Engineering           Black Female   11</span>
<span class="co">#&gt;  6:      Civil Engineering   International   Male    2</span>
<span class="co">#&gt;  7:      Civil Engineering        Hispanic   Male   12</span>
<span class="co">#&gt;  8:      Civil Engineering           Asian Female    6</span>
<span class="co">#&gt;  9:      Civil Engineering Native American   Male    2</span>
<span class="co">#&gt; 10:      Civil Engineering        Hispanic Female    1</span>
<span class="co">#&gt; ---                                                   </span>
<span class="co">#&gt; 44: Industrial Engineering           Black Female   24</span>
<span class="co">#&gt; 45: Industrial Engineering           White Female   80</span>
<span class="co">#&gt; 46: Industrial Engineering           Black   Male   25</span>
<span class="co">#&gt; 47: Industrial Engineering        Hispanic   Male    7</span>
<span class="co">#&gt; 48: Industrial Engineering        Hispanic Female    1</span>
<span class="co">#&gt; 49: Industrial Engineering   International   Male   12</span>
<span class="co">#&gt; 50: Industrial Engineering           Asian Female    7</span>
<span class="co">#&gt; 51: Industrial Engineering   International Female    2</span>
<span class="co">#&gt; 52: Industrial Engineering           Other Female    3</span>
<span class="co">#&gt; 53: Industrial Engineering           Other   Male    3</span></pre></body></html></div>
<p>Join. The number of grouped-graduate rows can never be greater than the number of grouped-starters rows, so we left-join graduates to starters.</p>
<div class="sourceCode" id="cb14"><html><body><pre class="r"><span class="no">grouped_data</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/merge.html">merge</a></span>(<span class="no">grouped_starters</span>,
  <span class="no">grouped_graduates</span>,
  <span class="kw">by</span> <span class="kw">=</span> <span class="no">grouping_variables</span>,
  <span class="kw">all.x</span> <span class="kw">=</span> <span class="fl">TRUE</span>
)

<span class="no">grouped_data</span>
<span class="co">#&gt;                    program            race    sex start grad</span>
<span class="co">#&gt;  1:      Civil Engineering           Asian Female    14    6</span>
<span class="co">#&gt;  2:      Civil Engineering           Asian   Male    31   12</span>
<span class="co">#&gt;  3:      Civil Engineering           Black Female    28   11</span>
<span class="co">#&gt;  4:      Civil Engineering           Black   Male    60   19</span>
<span class="co">#&gt;  5:      Civil Engineering        Hispanic Female     6    1</span>
<span class="co">#&gt;  6:      Civil Engineering        Hispanic   Male    33   12</span>
<span class="co">#&gt;  7:      Civil Engineering   International Female     1   NA</span>
<span class="co">#&gt;  8:      Civil Engineering   International   Male     6    2</span>
<span class="co">#&gt;  9:      Civil Engineering Native American   Male     5    2</span>
<span class="co">#&gt; 10:      Civil Engineering           Other Female     3   NA</span>
<span class="co">#&gt; ---                                                         </span>
<span class="co">#&gt; 52: Mechanical Engineering   International Female     1   NA</span>
<span class="co">#&gt; 53: Mechanical Engineering   International   Male    22   10</span>
<span class="co">#&gt; 54: Mechanical Engineering Native American Female     2    2</span>
<span class="co">#&gt; 55: Mechanical Engineering Native American   Male     7    3</span>
<span class="co">#&gt; 56: Mechanical Engineering           Other Female     3    2</span>
<span class="co">#&gt; 57: Mechanical Engineering           Other   Male    30   17</span>
<span class="co">#&gt; 58: Mechanical Engineering         Unknown Female     2    1</span>
<span class="co">#&gt; 59: Mechanical Engineering         Unknown   Male     9    3</span>
<span class="co">#&gt; 60: Mechanical Engineering           White Female   185   72</span>
<span class="co">#&gt; 61: Mechanical Engineering           White   Male  1598  630</span></pre></body></html></div>
</div>
<div id="compute-graduation-rate" class="section level2">
<h2 class="hasAnchor">
<a href="#compute-graduation-rate" class="anchor"></a>Compute graduation rate</h2>
<p>Convert the NA values in the <code>grad</code> column to zero.</p>
<div class="sourceCode" id="cb15"><html><body><pre class="r"><span class="no">grad_rate</span> <span class="kw">&lt;-</span> <span class="no">grouped_data</span>
<span class="no">rows_with_grad_NA</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span>(<span class="no">grad_rate</span>$<span class="no">grad</span>)
<span class="no">grad_rate</span>[<span class="no">rows_with_grad_NA</span>, <span class="no">grad</span> <span class="kw">:=</span> <span class="fl">0</span>]

<span class="no">grad_rate</span>
<span class="co">#&gt;                    program            race    sex start grad</span>
<span class="co">#&gt;  1:      Civil Engineering           Asian Female    14    6</span>
<span class="co">#&gt;  2:      Civil Engineering           Asian   Male    31   12</span>
<span class="co">#&gt;  3:      Civil Engineering           Black Female    28   11</span>
<span class="co">#&gt;  4:      Civil Engineering           Black   Male    60   19</span>
<span class="co">#&gt;  5:      Civil Engineering        Hispanic Female     6    1</span>
<span class="co">#&gt;  6:      Civil Engineering        Hispanic   Male    33   12</span>
<span class="co">#&gt;  7:      Civil Engineering   International Female     1    0</span>
<span class="co">#&gt;  8:      Civil Engineering   International   Male     6    2</span>
<span class="co">#&gt;  9:      Civil Engineering Native American   Male     5    2</span>
<span class="co">#&gt; 10:      Civil Engineering           Other Female     3    0</span>
<span class="co">#&gt; ---                                                         </span>
<span class="co">#&gt; 52: Mechanical Engineering   International Female     1    0</span>
<span class="co">#&gt; 53: Mechanical Engineering   International   Male    22   10</span>
<span class="co">#&gt; 54: Mechanical Engineering Native American Female     2    2</span>
<span class="co">#&gt; 55: Mechanical Engineering Native American   Male     7    3</span>
<span class="co">#&gt; 56: Mechanical Engineering           Other Female     3    2</span>
<span class="co">#&gt; 57: Mechanical Engineering           Other   Male    30   17</span>
<span class="co">#&gt; 58: Mechanical Engineering         Unknown Female     2    1</span>
<span class="co">#&gt; 59: Mechanical Engineering         Unknown   Male     9    3</span>
<span class="co">#&gt; 60: Mechanical Engineering           White Female   185   72</span>
<span class="co">#&gt; 61: Mechanical Engineering           White   Male  1598  630</span></pre></body></html></div>
<p>We omit rows with zero starters, if any, to avoid dividing by zero.</p>
<div class="sourceCode" id="cb16"><html><body><pre class="r"><span class="co"># prevent division by zero</span>
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">grad_rate</span>$<span class="no">start</span> <span class="kw">&gt;</span> <span class="fl">0</span>
<span class="no">grad_rate</span> <span class="kw">&lt;-</span> <span class="no">grad_rate</span>[<span class="no">rows_we_want</span>]</pre></body></html></div>
<p>Graduation rate is the ratio of <code>grad</code> to <code>start</code>.</p>
<div class="sourceCode" id="cb17"><html><body><pre class="r"><span class="no">grad_rate</span>[, <span class="no">rate</span> <span class="kw">:=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span>(<span class="no">grad</span> / <span class="no">start</span>, <span class="fl">2</span>)]

<span class="no">grad_rate</span>
<span class="co">#&gt;                    program            race    sex start grad rate</span>
<span class="co">#&gt;  1:      Civil Engineering           Asian Female    14    6 0.43</span>
<span class="co">#&gt;  2:      Civil Engineering           Asian   Male    31   12 0.39</span>
<span class="co">#&gt;  3:      Civil Engineering           Black Female    28   11 0.39</span>
<span class="co">#&gt;  4:      Civil Engineering           Black   Male    60   19 0.32</span>
<span class="co">#&gt;  5:      Civil Engineering        Hispanic Female     6    1 0.17</span>
<span class="co">#&gt;  6:      Civil Engineering        Hispanic   Male    33   12 0.36</span>
<span class="co">#&gt;  7:      Civil Engineering   International Female     1    0 0.00</span>
<span class="co">#&gt;  8:      Civil Engineering   International   Male     6    2 0.33</span>
<span class="co">#&gt;  9:      Civil Engineering Native American   Male     5    2 0.40</span>
<span class="co">#&gt; 10:      Civil Engineering           Other Female     3    0 0.00</span>
<span class="co">#&gt; ---                                                              </span>
<span class="co">#&gt; 52: Mechanical Engineering   International Female     1    0 0.00</span>
<span class="co">#&gt; 53: Mechanical Engineering   International   Male    22   10 0.45</span>
<span class="co">#&gt; 54: Mechanical Engineering Native American Female     2    2 1.00</span>
<span class="co">#&gt; 55: Mechanical Engineering Native American   Male     7    3 0.43</span>
<span class="co">#&gt; 56: Mechanical Engineering           Other Female     3    2 0.67</span>
<span class="co">#&gt; 57: Mechanical Engineering           Other   Male    30   17 0.57</span>
<span class="co">#&gt; 58: Mechanical Engineering         Unknown Female     2    1 0.50</span>
<span class="co">#&gt; 59: Mechanical Engineering         Unknown   Male     9    3 0.33</span>
<span class="co">#&gt; 60: Mechanical Engineering           White Female   185   72 0.39</span>
<span class="co">#&gt; 61: Mechanical Engineering           White   Male  1598  630 0.39</span></pre></body></html></div>
<p>To see the class of each column:</p>
<div class="sourceCode" id="cb18"><html><body><pre class="r"><span class="co"># name and class of variables (columns)</span>
<span class="fu"><a href="https://rdrr.io/r/base/unlist.html">unlist</a></span>(<span class="fu"><a href="https://rdrr.io/r/base/lapply.html">lapply</a></span>(<span class="no">grad_rate</span>, <span class="kw">FUN</span> <span class="kw">=</span> <span class="no">class</span>))
<span class="co">#&gt;     program        race         sex       start        grad        rate </span>
<span class="co">#&gt; "character" "character" "character"   "integer"   "integer"   "numeric"</span></pre></body></html></div>
</div>
<div id="condition-the-data-for-display" class="section level2">
<h2 class="hasAnchor">
<a href="#condition-the-data-for-display" class="anchor"></a>Condition the data for display</h2>
<p>Before graphing, we isolate the three multiway variables (program, combined race and sex, and rate) and transform the categorical variables into factors with levels that are ordered by median graduation rate.</p>
<div class="sourceCode" id="cb19"><html><body><pre class="r"><span class="co"># pre-multiway data frame</span>
<span class="no">pre_mw</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/copy.html">copy</a></span>(<span class="no">grad_rate</span>)

<span class="co"># prepare rows</span>
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">pre_mw</span>$<span class="no">start</span> <span class="kw">&gt;=</span> <span class="fl">5</span>
<span class="no">pre_mw</span> <span class="kw">&lt;-</span> <span class="no">pre_mw</span>[<span class="no">rows_we_want</span>]

<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> !<span class="no">pre_mw</span>$<span class="no">race</span> <span class="kw">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(
  <span class="st">"Unknown"</span>,
  <span class="st">"International"</span>,
  <span class="st">"Other"</span>,
  <span class="st">"Native American"</span>
)
<span class="no">pre_mw</span> <span class="kw">&lt;-</span> <span class="no">pre_mw</span>[<span class="no">rows_we_want</span>]

<span class="co"># complete the transformation to multiway form</span>
<span class="no">data_mw</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/copy.html">copy</a></span>(<span class="no">pre_mw</span>)
<span class="no">data_mw</span>[, <span class="no">race_sex</span> <span class="kw">:=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span>(<span class="no">race</span>, <span class="no">sex</span>, <span class="kw">sep</span> <span class="kw">=</span> <span class="st">" "</span>)]
<span class="no">cols_we_want</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"program"</span>, <span class="st">"race_sex"</span>, <span class="st">"rate"</span>)
<span class="no">data_mw</span> <span class="kw">&lt;-</span> <span class="no">data_mw</span>[, <span class="no">..cols_we_want</span>]

<span class="co"># transform characters to factors ordered by median rate</span>
<span class="no">data_mw</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/prepare_multiway.html">prepare_multiway</a></span>(<span class="no">data_mw</span>)</pre></body></html></div>
</div>
<div id="graph-the-metric" class="section level2">
<h2 class="hasAnchor">
<a href="#graph-the-metric" class="anchor"></a>Graph the metric</h2>
<p>We use conventional ggplot2 functions to graph the <code>data_mw</code> data set in a multiway graph.</p>
<div class="sourceCode" id="cb20"><html><body><pre class="r"><span class="co"># graph results</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(<span class="kw">data</span> <span class="kw">=</span> <span class="no">data_mw</span>, <span class="kw">mapping</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">rate</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">race_sex</span>)) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span>(<span class="kw">facets</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/vars.html">vars</a></span>(<span class="no">program</span>), <span class="kw">ncol</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="kw">as.table</span> <span class="kw">=</span> <span class="fl">FALSE</span>) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span>(<span class="kw">na.rm</span> <span class="kw">=</span> <span class="fl">TRUE</span>) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="st">"Graduation rate"</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="st">""</span>)</pre></body></html></div>
<p><img src="../man/figures/vignette-graduation-rate-fig1-1.png" width="70%" style="display: block; margin: auto;"></p>
</div>
<div id="references" class="section level2">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs">
<div id="ref-Cook+Hartle:2011">
<p>Cook, Bryan and Hartle, Terry W. (2011) Why graduation rates matter—and why they don’t. <em>The Presidency magazine</em> (Spring/Summer 2011). American Council on Education.</p>
</div>
<div id="ref-IPEDS:2020">
<p>NCES (2020) <em>IPEDS Survey Methodology</em>. National Center for Education Statistics; [Online; accessed 2020-07-29]. Available at: <a href="https://nces.ed.gov/ipeds/ReportYourData/IpedsSurveyMethodology">https://nces.ed.gov/ipeds/ReportYourData/IpedsSurveyMethodology</a>.</p>
</div>
</div>
</div>
<div id="appendix" class="section level2">
<h2 class="hasAnchor">
<a href="#appendix" class="anchor"></a>Appendix</h2>
<div id="a--how-subset_ipeds-works" class="section level3">
<h3 class="hasAnchor">
<a href="#a--how-subset_ipeds-works" class="anchor"></a>A. How <code>subset_ipeds()</code> works</h3>
<p>The first operation in <code><a href="../reference/subset_ipeds.html">subset_ipeds()</a></code> is accessing <code>midfieldstudents</code> for entering term and transfer information for the students is <code>starters</code>. Then transfer students are removed, yielding:</p>
<pre><code>#&gt;                id  start term_enter transfer
#&gt;    1: MID25783227 141001      20031        N
#&gt;    2: MID25783388 141901      19871        N
#&gt;    3: MID25783441 140801      19921        N
#&gt;    4: MID25783491 141001      19961        N
#&gt;    5: MID25783553 140801      20021        N
#&gt;    6: MID25783606 141001      20011        N
#&gt;    7: MID25783753 141901      20001        N
#&gt;    8: MID25783830 141901      19951        N
#&gt;    9: MID25783912 143501      19971        N
#&gt;   10: MID25784022 141901      20011        N
#&gt;   ---                                       
#&gt; 5862: MID26696050 141901      20111        N
#&gt; 5863: MID26696234 141901      20111        N
#&gt; 5864: MID26696337 140801      20101        N
#&gt; 5865: MID26696429 143501      20101        N
#&gt; 5866: MID26696439 141901      20101        N
#&gt; 5867: MID26696484 141901      20101        N
#&gt; 5868: MID26696642 141001      20121        N
#&gt; 5869: MID26696958 141901      20111        N
#&gt; 5870: MID26696967 141901      20101        N
#&gt; 5871: MID26697444 141901      20101        N</code></pre>
<p>By removing transfer students, we’ve reduced the population in this example from 6947 to 5871.</p>
<p>The next operation accesses <code>midfielddegrees</code> for the degree term and CIP code. An NA indicates no degree.</p>
<pre><code>#&gt;                id  start term_enter term_degree cip_degree
#&gt;    1: MID25783227 141001      20031          NA       &lt;NA&gt;
#&gt;    2: MID25783388 141901      19871          NA       &lt;NA&gt;
#&gt;    3: MID25783441 140801      19921       19963     140801
#&gt;    4: MID25783491 141001      19961       20001     141001
#&gt;    5: MID25783553 140801      20021          NA       &lt;NA&gt;
#&gt;    6: MID25783606 141001      20011          NA       &lt;NA&gt;
#&gt;    7: MID25783753 141901      20001          NA       &lt;NA&gt;
#&gt;    8: MID25783830 141901      19951          NA       &lt;NA&gt;
#&gt;    9: MID25783912 143501      19971       20001     143501
#&gt;   10: MID25784022 141901      20011          NA       &lt;NA&gt;
#&gt;   ---                                                     
#&gt; 5862: MID26696050 141901      20111       20163     141901
#&gt; 5863: MID26696234 141901      20111       20143     141901
#&gt; 5864: MID26696337 140801      20101       20133     140801
#&gt; 5865: MID26696429 143501      20101       20133     143501
#&gt; 5866: MID26696439 141901      20101          NA       &lt;NA&gt;
#&gt; 5867: MID26696484 141901      20101       20154     141901
#&gt; 5868: MID26696642 141001      20121       20153     141001
#&gt; 5869: MID26696958 141901      20111          NA       &lt;NA&gt;
#&gt; 5870: MID26696967 141901      20101       20141     141901
#&gt; 5871: MID26697444 141901      20101       20151     240199</code></pre>
<p>In the degree data, the term recorded is NA for students with no degree. Therefore, the next operation accesses <code>midfieldterms</code> for the term and CIP code for every term for these students, retaining the last term only, yielding:</p>
<pre><code>#&gt;                id  start term_enter  term term_degree cip_term cip_degree
#&gt;    1: MID25783227 141001      20031 20033          NA   230101       &lt;NA&gt;
#&gt;    2: MID25783388 141901      19871 19905          NA   141901       &lt;NA&gt;
#&gt;    3: MID25783441 140801      19921 19963       19963   140801     140801
#&gt;    4: MID25783491 141001      19961 20001       20001   141001     141001
#&gt;    5: MID25783553 140801      20021 20071          NA   140801       &lt;NA&gt;
#&gt;    6: MID25783606 141001      20011 20043          NA   141001       &lt;NA&gt;
#&gt;    7: MID25783753 141901      20001 20043          NA   310301       &lt;NA&gt;
#&gt;    8: MID25783830 141901      19951 19963          NA   419999       &lt;NA&gt;
#&gt;    9: MID25783912 143501      19971 20001       20001   143501     143501
#&gt;   10: MID25784022 141901      20011 20053          NA   141901       &lt;NA&gt;
#&gt;   ---                                                                    
#&gt; 5828: MID26696050 141901      20111 20163       20163   141901     141901
#&gt; 5829: MID26696234 141901      20111 20143       20143   141901     141901
#&gt; 5830: MID26696337 140801      20101 20131       20133   140801     140801
#&gt; 5831: MID26696429 143501      20101 20131       20133   143501     143501
#&gt; 5832: MID26696439 141901      20101 20131          NA   141901       &lt;NA&gt;
#&gt; 5833: MID26696484 141901      20101 20154       20154   141901     141901
#&gt; 5834: MID26696642 141001      20121 20153       20153   141001     141001
#&gt; 5835: MID26696958 141901      20111 20111          NA   141901       &lt;NA&gt;
#&gt; 5836: MID26696967 141901      20101 20141       20141   141901     141901
#&gt; 5837: MID26697444 141901      20101 20151       20151   240199     240199</code></pre>
<p>There is a small reduction in the number of students, from 5871 to 5837, because of incomplete data in <code>midfieldterms</code>. (Some students have an NA in both their degree term and in their <code>term</code> data in <code>midfieldterms</code>. Essentially, we have matriculation information for these students but no term information.)</p>
<p>Selecting the columns that are needed to apply the IPEDS constraints, we have,</p>
<pre><code>#&gt;                id  start term_enter term_degree cip_degree
#&gt;    1: MID25783227 141001      20031          NA       &lt;NA&gt;
#&gt;    2: MID25783388 141901      19871          NA       &lt;NA&gt;
#&gt;    3: MID25783441 140801      19921       19963     140801
#&gt;    4: MID25783491 141001      19961       20001     141001
#&gt;    5: MID25783553 140801      20021          NA       &lt;NA&gt;
#&gt;    6: MID25783606 141001      20011          NA       &lt;NA&gt;
#&gt;    7: MID25783753 141901      20001          NA       &lt;NA&gt;
#&gt;    8: MID25783830 141901      19951          NA       &lt;NA&gt;
#&gt;    9: MID25783912 143501      19971       20001     143501
#&gt;   10: MID25784022 141901      20011          NA       &lt;NA&gt;
#&gt;   ---                                                     
#&gt; 5828: MID26696050 141901      20111       20163     141901
#&gt; 5829: MID26696234 141901      20111       20143     141901
#&gt; 5830: MID26696337 140801      20101       20133     140801
#&gt; 5831: MID26696429 143501      20101       20133     143501
#&gt; 5832: MID26696439 141901      20101          NA       &lt;NA&gt;
#&gt; 5833: MID26696484 141901      20101       20154     141901
#&gt; 5834: MID26696642 141001      20121       20153     141001
#&gt; 5835: MID26696958 141901      20111          NA       &lt;NA&gt;
#&gt; 5836: MID26696967 141901      20101       20141     141901
#&gt; 5837: MID26697444 141901      20101       20151     240199</code></pre>
<p>The next step is to recode degree CIP under either condition:</p>
<ul>
<li>recode a degree to NA if more than 6 years from entering term to degree term</li>
<li>recode a degree to NA if degree CIP different from matriculation CIP</li>
</ul>
<p>Finally, the degree CIP is used to create a yes/no column <code>ipeds_grad</code> to be returned with the original ID and <code>start</code> columns. For graduates in this result, the degree CIP and starting CIP are identical.</p>
<pre><code>#&gt;                id  start ipeds_grad
#&gt;    1: MID25783227 141001          N
#&gt;    2: MID25783388 141901          N
#&gt;    3: MID25783441 140801          Y
#&gt;    4: MID25783491 141001          Y
#&gt;    5: MID25783553 140801          N
#&gt;    6: MID25783606 141001          N
#&gt;    7: MID25783753 141901          N
#&gt;    8: MID25783830 141901          N
#&gt;    9: MID25783912 143501          Y
#&gt;   10: MID25784022 141901          N
#&gt;   ---                              
#&gt; 5828: MID26696050 141901          Y
#&gt; 5829: MID26696234 141901          Y
#&gt; 5830: MID26696337 140801          Y
#&gt; 5831: MID26696429 143501          Y
#&gt; 5832: MID26696439 141901          N
#&gt; 5833: MID26696484 141901          Y
#&gt; 5834: MID26696642 141001          Y
#&gt; 5835: MID26696958 141901          N
#&gt; 5836: MID26696967 141901          Y
#&gt; 5837: MID26697444 141901          N</code></pre>
</div>
<div id="b--complete-script" class="section level3">
<h3 class="hasAnchor">
<a href="#b--complete-script" class="anchor"></a>B. Complete script</h3>
<p>The vignette code chunks are collected below in a single, condensed script.</p>
<div class="sourceCode" id="cb26"><html><body><pre class="r"><span class="co"># packages used</span>
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">midfieldr</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">midfielddata</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">data.table</span>)
<span class="fu"><a href="https://rdrr.io/r/base/library.html">library</a></span>(<span class="no">ggplot2</span>)

<span class="co"># select programs (built-in data set)</span>
<span class="no">program_group</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/copy.html">copy</a></span>(<span class="no">rep_group</span>)
<span class="no">group_cip</span> <span class="kw">&lt;-</span> <span class="no">program_group</span>$<span class="no">cip6</span>

<span class="co"># gather students matriculating in programs</span>
<span class="no">cols_we_want</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"id"</span>, <span class="st">"cip6"</span>)
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">midfieldstudents</span>$<span class="no">cip6</span> <span class="kw">%in%</span> <span class="no">group_cip</span>
<span class="no">matriculants</span> <span class="kw">&lt;-</span> <span class="no">midfieldstudents</span>[<span class="no">rows_we_want</span>, <span class="no">..cols_we_want</span>]
<span class="no">matriculants</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/duplicated.html">unique</a></span>(<span class="no">matriculants</span>)

<span class="co"># gather FYE students predicted to start in these programs</span>
<span class="no">cols_we_want</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"id"</span>, <span class="st">"start"</span>)
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">fye_start</span>$<span class="no">start</span> <span class="kw">%in%</span> <span class="no">group_cip</span>
<span class="no">fye_starters</span> <span class="kw">&lt;-</span> <span class="no">fye_start</span>[<span class="no">rows_we_want</span>, <span class="no">..cols_we_want</span>]
<span class="no">fye_starters</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/duplicated.html">unique</a></span>(<span class="no">fye_starters</span>)
<span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/setattr.html">setnames</a></span>(<span class="no">fye_starters</span>, <span class="kw">old</span> <span class="kw">=</span> <span class="st">"start"</span>, <span class="kw">new</span> <span class="kw">=</span> <span class="st">"cip6"</span>)
<span class="no">starters</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/rbindlist.html">rbind</a></span>(<span class="no">matriculants</span>, <span class="no">fye_starters</span>)

<span class="co"># apply the feasible completion filter</span>
<span class="no">feasible_ids</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/subset_feasible.html">subset_feasible</a></span>(<span class="no">starters</span>$<span class="no">id</span>)
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">starters</span>$<span class="no">id</span> <span class="kw">%in%</span> <span class="no">feasible_ids</span>
<span class="no">starters</span> <span class="kw">&lt;-</span> <span class="no">starters</span>[<span class="no">rows_we_want</span>]

<span class="co"># apply IPEDS constraints</span>
<span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/setattr.html">setnames</a></span>(<span class="no">starters</span>, <span class="kw">old</span> <span class="kw">=</span> <span class="st">"cip6"</span>, <span class="kw">new</span> <span class="kw">=</span> <span class="st">"start"</span>)
<span class="no">ipeds_students</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/subset_ipeds.html">subset_ipeds</a></span>(<span class="no">starters</span>)
<span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/setattr.html">setnames</a></span>(<span class="no">ipeds_students</span>, <span class="kw">old</span> <span class="kw">=</span> <span class="st">"start"</span>, <span class="kw">new</span> <span class="kw">=</span> <span class="st">"cip6"</span>)

<span class="co"># join race sex</span>
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">midfieldstudents</span>$<span class="no">id</span> <span class="kw">%in%</span> <span class="no">ipeds_students</span>$<span class="no">id</span>
<span class="no">cols_we_want</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"id"</span>, <span class="st">"race"</span>, <span class="st">"sex"</span>)
<span class="no">race_sex</span> <span class="kw">&lt;-</span> <span class="no">midfieldstudents</span>[<span class="no">rows_we_want</span>, <span class="no">..cols_we_want</span>]
<span class="no">race_sex</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/duplicated.html">unique</a></span>(<span class="no">race_sex</span>)
<span class="no">ipeds_students</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/merge.html">merge</a></span>(<span class="no">ipeds_students</span>, <span class="no">race_sex</span>, <span class="kw">by</span> <span class="kw">=</span> <span class="st">"id"</span>, <span class="kw">all.x</span> <span class="kw">=</span> <span class="fl">TRUE</span>)

<span class="co"># join programs</span>
<span class="no">ipeds_students</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/merge.html">merge</a></span>(<span class="no">ipeds_students</span>,
  <span class="no">program_group</span>,
  <span class="kw">by</span> <span class="kw">=</span> <span class="st">"cip6"</span>,
  <span class="kw">all.x</span> <span class="kw">=</span> <span class="fl">TRUE</span>
)

<span class="co"># group, summarize, join</span>
<span class="no">grouping_variables</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"program"</span>, <span class="st">"race"</span>, <span class="st">"sex"</span>)
<span class="no">grouped_starters</span> <span class="kw">&lt;-</span> <span class="no">ipeds_students</span>[, <span class="fu">.</span>(<span class="kw">start</span> <span class="kw">=</span> <span class="no">.N</span>), <span class="kw">by</span> <span class="kw">=</span> <span class="no">grouping_variables</span>]
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">ipeds_students</span>$<span class="no">ipeds_grad</span> <span class="kw">==</span> <span class="st">"Y"</span>
<span class="no">grouped_graduates</span> <span class="kw">&lt;-</span> <span class="no">ipeds_students</span>[<span class="no">rows_we_want</span>,
  <span class="fu">.</span>(<span class="kw">grad</span> <span class="kw">=</span> <span class="no">.N</span>),
  <span class="kw">by</span> <span class="kw">=</span> <span class="no">grouping_variables</span>
]
<span class="no">grouped_data</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://Rdatatable.gitlab.io/data.table/reference/merge.html">merge</a></span>(<span class="no">grouped_starters</span>,
  <span class="no">grouped_graduates</span>,
  <span class="kw">by</span> <span class="kw">=</span> <span class="no">grouping_variables</span>,
  <span class="kw">all.x</span> <span class="kw">=</span> <span class="fl">TRUE</span>
)

<span class="co"># compute graduation rate</span>
<span class="no">grad_rate</span> <span class="kw">&lt;-</span> <span class="no">grouped_data</span>
<span class="no">rows_with_grad_NA</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span>(<span class="no">grad_rate</span>$<span class="no">grad</span>)
<span class="no">grad_rate</span>[<span class="no">rows_with_grad_NA</span>, <span class="no">grad</span> <span class="kw">:=</span> <span class="fl">0</span>]
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">grad_rate</span>$<span class="no">start</span> <span class="kw">&gt;</span> <span class="fl">0</span>
<span class="no">grad_rate</span> <span class="kw">&lt;-</span> <span class="no">grad_rate</span>[<span class="no">rows_we_want</span>]
<span class="no">grad_rate</span>[, <span class="no">rate</span> <span class="kw">:=</span> <span class="fu"><a href="https://rdrr.io/r/base/Round.html">round</a></span>(<span class="no">grad</span> / <span class="no">start</span>, <span class="fl">2</span>)]

<span class="co"># condition data for display</span>
<span class="no">pre_mw</span> <span class="kw">&lt;-</span> <span class="no">grad_rate</span>
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> <span class="no">pre_mw</span>$<span class="no">start</span> <span class="kw">&gt;=</span> <span class="fl">5</span>
<span class="no">pre_mw</span> <span class="kw">&lt;-</span> <span class="no">pre_mw</span>[<span class="no">rows_we_want</span>]
<span class="no">rows_we_want</span> <span class="kw">&lt;-</span> !<span class="no">pre_mw</span>$<span class="no">race</span> <span class="kw">%in%</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(
  <span class="st">"Unknown"</span>,
  <span class="st">"International"</span>,
  <span class="st">"Other"</span>,
  <span class="st">"Native American"</span>
)
<span class="no">pre_mw</span> <span class="kw">&lt;-</span> <span class="no">pre_mw</span>[<span class="no">rows_we_want</span>]
<span class="no">data_mw</span> <span class="kw">&lt;-</span> <span class="no">pre_mw</span>
<span class="no">data_mw</span>[, <span class="no">race_sex</span> <span class="kw">:=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste</a></span>(<span class="no">race</span>, <span class="no">sex</span>, <span class="kw">sep</span> <span class="kw">=</span> <span class="st">" "</span>)]
<span class="no">cols_we_want</span> <span class="kw">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"program"</span>, <span class="st">"race_sex"</span>, <span class="st">"rate"</span>)
<span class="no">data_mw</span> <span class="kw">&lt;-</span> <span class="no">data_mw</span>[, <span class="no">..cols_we_want</span>]
<span class="no">data_mw</span> <span class="kw">&lt;-</span> <span class="fu"><a href="../reference/prepare_multiway.html">prepare_multiway</a></span>(<span class="no">data_mw</span>)

<span class="co"># graph</span>
<span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span>(<span class="kw">data</span> <span class="kw">=</span> <span class="no">data_mw</span>, <span class="kw">mapping</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="no">rate</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="no">race_sex</span>)) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/facet_wrap.html">facet_wrap</a></span>(<span class="kw">facets</span> <span class="kw">=</span> <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/vars.html">vars</a></span>(<span class="no">program</span>), <span class="kw">ncol</span> <span class="kw">=</span> <span class="fl">1</span>, <span class="kw">as.table</span> <span class="kw">=</span> <span class="fl">FALSE</span>) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span>(<span class="kw">na.rm</span> <span class="kw">=</span> <span class="fl">TRUE</span>) +
  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/labs.html">labs</a></span>(<span class="kw">x</span> <span class="kw">=</span> <span class="st">"Graduation rate"</span>, <span class="kw">y</span> <span class="kw">=</span> <span class="st">""</span>)</pre></body></html></div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Richard Layton, Russell Long, Matthew Ohland, US National Science Foundation.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.5.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
