<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Timely completion • midfieldr</title>
<!-- favicons --><link rel="icon" type="image/png" sizes="16x16" href="../favicon-16x16.png">
<link rel="icon" type="image/png" sizes="32x32" href="../favicon-32x32.png">
<link rel="apple-touch-icon" type="image/png" sizes="180x180" href="../apple-touch-icon.png">
<link rel="apple-touch-icon" type="image/png" sizes="120x120" href="../apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" type="image/png" sizes="76x76" href="../apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" type="image/png" sizes="60x60" href="../apple-touch-icon-60x60.png">
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/spacelab/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../bootstrap-toc.css">
<script src="../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Timely completion">
<meta property="og:description" content="midfieldr">
<meta property="og:image" content="/logo.png">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">midfieldr</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.0.0.9010</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../articles/get_started.html">Get started</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Vignettes
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/data_basics.html">Data basics</a>
    </li>
    <li>
      <a href="../articles/multiway_graphs.html">Multiway graphs and tables</a>
    </li>
    <li>
      <a href="../articles/identify_programs.html">Identify programs</a>
    </li>
    <li>
      <a href="../articles/handle_fye.html">Handle FYE programs</a>
    </li>
    <li>
      <a href="../articles/feasible_completion.html">Feasible completion</a>
    </li>
    <li>
      <a href="../articles/timely-completion.html">Timely completion</a>
    </li>
    <li>
      <a href="../articles/graduation_rate.html">Graduation rate</a>
    </li>
    <li>
      <a href="../articles/stickiness_metric.html">Stickiness metric</a>
    </li>
  </ul>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="../articles/pages/get_session.html">Session info</a>
</li>
<li>
  <a href="../news/index.html">News</a>
</li>
<li>
  <a href="../articles/pages/about_midfield.html">About</a>
</li>
<li>
  <a href="https://github.com/MIDFIELDR/midfieldr">
    <span class="fas fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="timely-completion_files/header-attrs-2.7/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Timely completion</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/MIDFIELDR/midfieldr/blob/master/vignettes/timely-completion.Rmd"><code>vignettes/timely-completion.Rmd</code></a></small>
      <div class="hidden name"><code>timely-completion.Rmd</code></div>

    </div>

    
    
<div id="introduction" class="section level2">
<h2 class="hasAnchor">
<a href="#introduction" class="anchor"></a>Introduction</h2>
<p>Some persistence metrics, e.g. graduation rate, require that students earn their degrees in a timely fashion, typically in no more than 6 years. When counting the number of graduates, only degrees earned within the timely completion span are included. All other degrees are re-coded for aggregation with the non-graduates.</p>
<p>Timely completion terminology is illustrated in the figure. Definitions are given below.</p>
<p><br><img src="../man/figures/vignette-timely-completion-fig1-1.png" width="70%" style="display: block; margin: auto;"><br></p>
<dl>
<dt>matriculation term</dt>
<dd>The term a student enters the institution from which they graduate. Applies to transfer students as well as first-time-in-college (FTIC) students.
</dd>
<dt>offset start term</dt>
<dd>For transfer students, the effective start term as if their transfer credit hours been earned at the institution from which they graduate. Typically, no more than 2 years of transfer credits are counted. For FTIC students, the offset is zero.
</dd>
<dt>degree term</dt>
<dd>The term in which a student earns their first degree.
</dd>
<dt>time to graduation</dt>
<dd>The number of terms (or equivalent years) between the offset start term and the end of the degree term.
</dd>
<dt>timely completion span</dt>
<dd>The maximum time to graduation (typically 6 years) for a degree to be included in the count of program graduates.
</dd>
</dl>
<p>When applying the timely completion constraint, students are counted as program graduates only if their time to graduation is no greater than the timely completion span; otherwise their they are aggregated with the program non-graduates.</p>
<div id="this-vignette-uses" class="section level3">
<h3 class="hasAnchor">
<a href="#this-vignette-uses" class="anchor"></a>This vignette uses</h3>
<p>midfieldr functions</p>
<ul>
<li><code><a href="../reference/subset_feasible.html">subset_feasible()</a></code></li>
<li><code>timely_completion()</code></li>
</ul>
<p>packages</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># packages used</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/MIDFIELDR/midfieldr">midfieldr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/MIDFIELDR/midfielddata">midfielddata</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-datatable.com">data.table</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://ggplot2.tidyverse.org">ggplot2</a></span><span class="op">)</span>

<span class="co"># print max 20 rows, otherwise 10 rows each head/tail</span>
<span class="fu"><a href="https://rdrr.io/r/base/options.html">options</a></span><span class="op">(</span>datatable.print.nrows <span class="op">=</span> <span class="fl">20</span>, datatable.print.topn <span class="op">=</span> <span class="fl">10</span><span class="op">)</span></code></pre></div>
<!-- ################################################ -->
</div>
</div>
<div id="how-to-use-timely_completion" class="section level2">
<h2 class="hasAnchor">
<a href="#how-to-use-timely_completion" class="anchor"></a>How to use <code>timely_completion()</code>
</h2>
<p>The first argument, <code>id</code>, is required. The remaining arguments all have default settings. The last three arguments accommodate using data sets other than those from midfielddata. Arguments after the ellipsis (…) must be named if used.</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R">    <span class="fu">timely_completion</span><span class="op">(</span>
      <span class="va">id</span>,                    
      <span class="va">...</span>,
      span <span class="op">=</span> <span class="cn">NULL</span>,
      term_transfer_max <span class="op">=</span> <span class="cn">NULL</span>,
      data_students <span class="op">=</span> <span class="cn">NULL</span>,
      data_terms <span class="op">=</span> <span class="cn">NULL</span>,
      data_degrees <span class="op">=</span> <span class="cn">NULL</span>
    <span class="op">)</span></code></pre></div>
<ul>
<li>
<code>id</code> character vector of student IDs</li>
<li>
<code>span</code> number of years to define timely completion, default is 6 years</li>
<li>
<code>term_transfer_max</code> maximum terms of transfer credit for determining years to graduation, default is 4 terms (2 years)</li>
<li>
<code>data_students</code> student attributes data set, <code>midfieldstudents</code> or equivalent</li>
<li>
<code>data_terms</code> term attributes data set, <code>midfieldterms</code> or equivalent</li>
<li>
<code>data_degrees</code> degree attributes data set, <code>midfielddegrees</code> or equivalent</li>
</ul>
<p>The primary input to <code><a href="../reference/subset_feasible.html">subset_feasible()</a></code> is a character vector of student IDs. To illustrate its use, we use the built-in data set <code>rep_ever</code> from the engineering case study as developed in the <em>Stickiness metric</em> vignette <a href="stickiness_metric.html">(link)</a>.</p>
<p>View its help page by running</p>
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="op">?</span> <span class="va">rep_ever</span></code></pre></div>
<p>The data are loaded with midfieldr.</p>
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># view the example IDs</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">rep_ever</span><span class="op">)</span>
<span class="co">#&gt;  chr [1:11862] "MID25783166" "MID25783178" "MID25783197" "MID25783227" ...</span></code></pre></div>
<p>This vector of IDs is the input to <code><a href="../reference/subset_feasible.html">subset_feasible()</a></code>, which performs the subsetting for completion feasibility.</p>
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># filter IDs for feasible program completion within data limit</span>
<span class="va">feasible_id</span> <span class="op">&lt;-</span> <span class="fu"><a href="../reference/subset_feasible.html">subset_feasible</a></span><span class="op">(</span><span class="va">rep_ever</span><span class="op">)</span>

<span class="co"># examine the result</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">feasible_id</span><span class="op">)</span>
<span class="co">#&gt;  chr [1:9281] "MID25783178" "MID25783197" "MID25783441" "MID25783491" ...</span></code></pre></div>
<p>In this instance, we started with 11,862 enrollees. After applying the criteria for feasible completion, we retain 9281 students. These students either graduated (demonstrating the feasibility of completing their programs before the data limit) or they matriculated no later than their matriculation limits.</p>
<p>Related vignettes</p>
<ul>
<li>
<em>Graduation rate</em> vignette <a href="graduation_rate_metric.html">(link)</a> in which the representative group of case study starters is developed.</li>
</ul>
<!-- ################################################ -->
</div>
<div id="how-to-use-timely_completion-1" class="section level2">
<h2 class="hasAnchor">
<a href="#how-to-use-timely_completion-1" class="anchor"></a>How to use <code>timely_completion()</code>
</h2>
<p>change: use the <code>rep_ever</code> IDs to illustrate using the function</p>
<p>The program group for the engineering case study is included with midfieldr as the built-in data set <code>rep_group</code>. View its help page by running</p>
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="op">?</span> <span class="va">rep_ever</span> </code></pre></div>
<p>The data are loaded with midfieldr.</p>
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="co"># examine the result</span>
<span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">rep_ever</span><span class="op">)</span>
<span class="co">#&gt;  chr [1:11862] "MID25783166" "MID25783178" "MID25783197" "MID25783227" ...</span></code></pre></div>
<p>The argument of <code>timely_completion()</code> is a vector of student IDs. The function returns a data frame with two columns keyed by ID: a numerical variable <code>years_to_grad</code>, giving the time to graduation; and a logical variable <code>is_timely</code>, stating if the graduate satisfies the timely completion criterion.</p>
<p>Example output of <code>timely_completion(id)</code></p>
<pre><code>#&gt;      id   years_to_grad   is_timely 
#&gt;  MID001               5        TRUE
#&gt;  MID002               7       FALSE        
#&gt;  MID003            &lt;NA&gt;       FALSE  
#&gt;  MID004               5        TRUE
#&gt;  MID005             6.5       FALSE
#&gt;   ---   </code></pre>
<p>Related vignettes</p>
<ul>
<li>obtaining <code>rep_ever</code> IDs</li>
</ul>
</div>
<div id="how-timely_completion-works" class="section level2">
<h2 class="hasAnchor">
<a href="#how-timely_completion-works" class="anchor"></a>How <code>timely_completion()</code> works</h2>
<p>function arguments</p>
<pre><code>timely_completion(
  id,                       # character vector of student IDs
  ...,
  span = NULL,              # numeric scalar, number of years to define 
                              timely completion, default 6 years
                              
  term_transfer_max = NULL, # numeric scalar, maximum number of terms of
                              transfer credit to offset matriculation,  
                              default 4 terms

  data_students = NULL,     # data frame of student attributes
  data_terms = NULL,        # data frame of term attributes
  data_degrees = NULL       # data frame of degree attributes
)</code></pre>
</div>
<div id="references" class="section level2">
<h2 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h2>
<div id="refs">

</div>
</div>
<div id="appendix" class="section level2">
<h2 class="hasAnchor">
<a href="#appendix" class="anchor"></a>Appendix</h2>
<div id="complete-script" class="section level3">
<h3 class="hasAnchor">
<a href="#complete-script" class="anchor"></a>Complete script</h3>
<p>The vignette code chunks are collected below in a single, condensed script.</p>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Richard Layton, Russell Long, Matthew Ohland, US National Science Foundation.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
